### ISSUE TITLE
Fast writers

### ISSUE THREAD

**Issue by hadley** [hadley/readr#10]
We may also want to consider having fast writers.  `write.table` generates the complete output before saving it to disk, so it's not suitable for saving large files.  For a recent problem I had to write

```R
n <- 10000L
m <- floor(nrow(logs) / n)
for (i in seq(0, m, by = 1)) {
  start <- i * n + 1
  end <- pmin((i + 1) * n, nrow(logs))
  
  write.table(logs[start:end, ], "logs.csv", row.names = FALSE, 
    sep = ",", append = i != 0L, col.names = FALSE, na = "")
  cat(".")
}
```

That's obviously not ideal.

**Comment by GShotwell** [comment]
Re: names how about:

clerk
copyr
muser
scribr

Personal favorite is clerk. You do the analysis, then send the reading and writing to your clerk.

**Comment by hadley** [comment]
Hmmm, I do rather like clerk or scribe.

**Comment by romainfrancois** [comment]
Me too, esp as `readr` implies this is just about reading. btw, this discussion should be in #58 right.
