### ISSUE TITLE
separation with Pipe separator (sep ="|") not working

### ISSUE THREAD

**Issue by pescadra** [hadley/readr#100]
I've been browsing though separation with pipe ("|") delim.
R on my computer doesn't seem to recognize the pipe

Used it in read.delim, read.table, str_split_fixed : sep="|" or tried to sub(pattern="|")

Nothing seems to work. 

when is use sep="|", R separates before the character string. Though nothing is there.
When I use pattern: a substitution happens on the same place.
When i rerun the script, the thing happens on the same place? 

What can be wrong?

2 line of the string you can find below: (is about 115.000 row)

1. LCD- en plasma-televisies|Type scherm
2. LCD- en plasma-televisies|Beeldschermgrootte in cm

it's actually part of a csv. Would it be possible to use double separators pe.: sep =c(";","|") in read.delim?

1. 762093-NZ;LCD- en plasma-televisies|Type scherm;;Type scherm;Type d'Ecran;LCD;LCD
2. 762093-NZ;LCD- en plasma-televisies|Beeldschermgrootte in cm;;Beeldschermgrootte in cm;Taille de l'Ecran en cm;48;48

**Comment by hadley** [comment]
Could you please supply a reproducible example? The following works for me:

```R
library(readr)
read_delim("a|b|c\n1|2|3\n", delim = "|")
```
