### ISSUE TITLE
Segfault crashing R with read_tsv

### ISSUE THREAD

**Issue by ahalterman** [hadley/readr#103]
I'm getting an error in readr's `read_tsv` that crashes my R session when I try to read in a file. My session info and a link to the (large) file in my S3 bucket are below. Other files from the same dataset read in just fine. It's likely to just be a data quality issue with this file, but it would be good for `readr` to fail more gracefully. I'm happy to run any other tests on my end if the error doesn't replicate.

```
> library(readr)
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readr_0.0.0.9000

loaded via a namespace (and not attached):
[1] Rcpp_0.11.5

>  tmp <- read_tsv("~/ICEWS/study_28075/Data/events.2005.20150313083555.tab")
|============================                                                   |36%     
 *** caught segfault ***
address 0x0, cause 'unknown'

Traceback:
 1: .Call("readr_read_tokens", PACKAGE = "readr", sourceSpec, tokenizerSpec,     colSpecs, col_names, n_max, progress)
 2: read_tokens(ds, tokenizer, col_types, col_names, n_max = n_max,     progress = progress)
 3: read_delimited(file, tokenizer, col_names = col_names, col_types = col_types,     skip = skip, n_max = n_max, progress = progress)
 4: read_tsv("~/ICEWS/study_28075/Data/events.2005.20150313083555.tab")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 1
aborting ...
Segmentation fault: 11
```

Here's a link to the file:
https://s3.amazonaws.com/ahalterman-general/new+folder/events.2005.20150313083555.tab (268 MB)

And if you're interested, the rest of the data set is provided and documented here:
http://thedata.harvard.edu/dvn/faces/study/StudyPage.xhtml?globalId=doi:10.7910/DVN/28075

**Comment by hadley** [comment]
Are you sure you have the latest dev version? I get:  `Error: At [371665, 9] expecting delimiter or quote but found ' '` (making that a warning instead of an error is #99)

**Comment by ahalterman** [comment]
I just re-installed `readr` and got the same segfault error as before.

**Comment by ahalterman** [comment]
I just tried on my Ubuntu machine and got the same error you did, so I'm assuming it's something specific to my specific Mac. I'm happy to run any tests on my machine, but only if you think it'll be useful since I think the problem's on my end, not `readr`'s.

```
> tmp <- read_tsv("/home/admin1/R/events.2005.20150313083555.tab")
|============================                                                   |36%     Error: At [371665, 9] expecting delimiter or quote but found ' '
```

**Comment by hadley** [comment]
Hmmm, I'm running on mac too. It's possible it's an Rcpp version mismatch - can you please try reinstalling Rcpp?

**Comment by ahalterman** [comment]
That was it. Re-installing Rcpp from Github, then re-installing readr solved it. I now get the same error you did. Thanks!
