### ISSUE TITLE
ISO 8601 weeks-and-days do not work

### ISSUE THREAD

**Issue by gaborcsardi** [hadley/readr#105]
This is a valid ISO8601 format.

```r
> tests[,1][12:22]
 [1] "2013-W06-5"              "2013-W06-5T09"           "2013-W06-5 09"          
 [4] "2013-W06-5T09:30"        "2013-W06-5 09:30"        "2013-W06-5T09:30:26"    
 [7] "2013-W06-5 09:30:26"     "2013-W06-5T09:30:26.123" "2013-W06-5 09:30:26.123"
[10] "2013-W06-5T09:30:26Z"    "2013-W06-5 09:30:26Z"   
> parse_date(tests[,1][12:22])
 [1] NA NA NA NA NA NA NA NA NA NA NA
```

**Comment by hadley** [comment]
I should've mentioned that this isn't currently supported. Have you seen this format in real life?

**Comment by gaborcsardi** [comment]
Only in the standard. :) But I haven't seen a lot of things and they are still in the standards. :)

**Comment by hadley** [comment]
Any interested in doing a PR? Otherwise I'll tackle it when I do ordinal dates - it'll need much the same machinery

**Comment by gaborcsardi** [comment]
Can't do a PR now, sorry.

**Comment by hadley** [comment]
Thinking about this more, it's probably not super important to add to the default ISO8601 parser.  But it probably is a good idea to add `%W` support to `parse_datetime()`.

It looks like it's going to be a moderate amount of work (especially given that there isn't a standard definition of week number, and cctz doesn't seem to provide helpers). I'll re-open if anyone actually needs this.
