### ISSUE TITLE
Some valid ISO8601 dates that do not work, some invalid dates are parsed

### ISSUE THREAD

**Issue by gaborcsardi** [hadley/readr#106]
Some of these might be covered by #105, but some are surely not.

```r
> tests[,1][is.na(parse_date(tests[,1]))]
 [1] "2009-12T12:34"               "2009"                       
 [3] "2009-05"                     "2009-222"                   
 [5] "2009-001"                    "2009-W01-1"                 
 [7] "2009-W51-1"                  "2009-W511"                  
 [9] "2009-W33"                    "2009W511"                   
[11] "2009-W21-2"                  "2009-W21-2T01:22"           
[13] "2009-139"                    "2010-02-18T16:23:48,444"    
[15] "2010-02-18T16:23:48,3-06:00" "2010-02-18T16:23,25"        
[17] "2010-02-18T16,2283"          "2009-05-19 1439,55"         
```

These are invalid, but they parse:

```r
> tests[,1][!is.na(parse_date(tests[,1]))]
[1] "2007-04-05T24:50"      "2009-05-19T14:3924"    "2009-0519"            
[4] "2009-05-19 14:"        "200912-01"             "2009-05-19 146922.500"
```

**Comment by gaborcsardi** [comment]
Btw. how about a PR with a lot of positive and negative examples? 

Sadly, I don't have time now to fix the ones that do not work, but maybe it is useful just to have the tests. I wrote (and collected) them some time ago for an ISO-8601 parsing project.

**Comment by hadley** [comment]
* I don't currently support dates without months/days because R doesn't have a native data type for date ranges of that type. If you think I should default to first month and first day of month, that's an easy fix

* I don't support julian days either. Is that common? I don't mind adding, but I'd rather wait until someone actually needs it.

* The parser is actually a bit more flexible than iso8601 because (e.g.) making "200912-01" fail is a decent amount of for little gain. Unless you feel really strongly about this, I'd rather fix it the problem with better documentation.

**Comment by gaborcsardi** [comment]
> I don't currently support dates without months/days because R doesn't have a native data type for date ranges of that type. If you think I should default to first month and first day of month, that's an easy fix

I think first day of month is fine.

> I don't support julian days either. Is that common? I don't mind adding, but I'd rather wait until someone actually needs it.

You mean the year and day format? 

> The parser is actually a bit more flexible than iso8601 because (e.g.) making "200912-01" fail is a decent amount of for little gain. Unless you feel really strongly about this, I'd rather fix it the problem with better documentation.

That's fine with me.

> What are the formats with commas in them?

From Wikipedia:

> Decimal fractions may be added to any of the three time elements. However, a fraction may only be added to the lowest order time element in the representation. A decimal mark, either a comma or a dot (without any preference as stated in resolution 10 of the 22nd General Conference CGPM in 2003,[14] but with a preference for a comma according to ISO 8601:2004)[15] is used as a separator between the time element and its fraction.

In summary, I don't mind fixing these in the docs. On the other hand it would be nice to have a fast parser  to validate ISO 8601 dates, however stupid they might look.

**Comment by hadley** [comment]
I'm not against building a better parser, but it's not high priority at the moment. I'm happy to review a pull request if you're interested.
