### ISSUE TITLE
Missing values 

### ISSUE THREAD

**Issue by jrnold** [hadley/readr#111]
When the string "`.`" is used to indicate missing values (in numeric or integer fields?), it causes problems for `read_csv`.

Example: 
```r
democracy <- read_csv("http://faculty.washington.edu/cadolph/503/democracy.csv", na = ".")
```
gives 
```r
There were 50 or more warnings (use warnings() to see the first 50)
```
with all the warning messages being variants of
```r
Warning messages:
1: In read_tokens(ds, tokenizer, col_types, col_names, n_max = n_max,  ... :
```

**Comment by hadley** [comment]
Would you mind creating a self-contained example like this?

```R
read_csv("x,y
1,.
.,2", na = ".")
```

**Comment by jrnold** [comment]
```r
foo <- 'x,y\n"0.1","5"\n"0.89","6"\n".","."'
read_csv(foo, na = ".", col_types = "di")
```

The larger dataset gets `readr:::collectorsGuess` to return doubles and integers for the columns with `.` and numbers even though the column is quoted. I don't get that with the smaller self-contained example and need to specify the column types to get the error.

**Comment by hadley** [comment]
Quoting doesn't actually mean anything in csv - you shouldn't expect it to force columns to be character.

**Comment by hadley** [comment]
More minimal and hopefully revealing example:

```R
read_csv('x\n1\n"."', na = ".", col_types = "d")
read_csv('x\n1\n.', na = ".", col_types = "d")
```

**Comment by hadley** [comment]
So I now think that this behaviour is correct. There is one difference between quoted and unquoted values: quoted values are never turned into missing values (I think this is necessary otherwise there's no way to record a literal "NA" in a file.

**Comment by jrnold** [comment]
Sounds reasonable to me. I was just giving you an example of a csv file I found in the wild that worked for `read.csv` and not `read_csv`. Ugghh, csv files are terrible to parse.
