### ISSUE TITLE
`col_euro_numeric`should exist (decimal comma)

### ISSUE THREAD

**Issue by juancentro** [hadley/readr#113]
It's great to have `col_euro_double`. It would be great to have `col_euro_numeric` as well.

**Comment by smbache** [comment]
It would also be nice to have the option to be able to set e.g. a comma as the default decimal separator (as with `dec = ","` in `read.table`); I encounter this format all the time... And if you have quite a few numeric columns, specifying all of them is a little bit of a mess.

**Comment by hadley** [comment]
@smbache do you have an example where the autodetection fails? If so, could you please file a separate issue.

**Comment by smbache** [comment]
I was unaware that this would be auto detected (and didn't try); my bad. I will try it out and if I encounter an issue I'll let you know. Thanks.

**Comment by hadley** [comment]
@smbache FWIW, one reason I want to stay away from global options and system dependent settings is that it makes code that only works on your computer, and fails mysteriously when you share it with someone who speaks a different language.
