### ISSUE TITLE
Error in problems() after failed file read

### ISSUE THREAD

**Issue by revodavid** [hadley/readr#115]
I was trying to import NYNEWYOR.txt (attached) as follows:

```
> dat <- read_tsv("NYNEWYOR.txt",col_names=c("DAY","MONTH","YEAR","TEMP"))
Error: You have 4 column names, but 1 columns
```

The error message wasn't a surprise, but I was hoping `problems()` would give me a clue as to how to fix the error. Instead:

```
> problems()
Error in withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning")) : 
  argument "x" is missing, with no default
```

[NYNEWYOR.txt | uploaded via ZenHub](https://files.zenhub.io/5527f89b5638c74308d8c4eb)

**Comment by jirilukavsky** [comment]
Your file is not separated by tabs but by multiple spaces. I do not know if it is possible to make readr treat the consecutive separator chars as a single separator. However, the spaces in your file are used to create a fixed width for each field, therefore read_wf works fine:
```
fn <- "NYNEWYOR.txt"
dat <- read_fwf(fn, fwf_empty(fn))
```

**Comment by jirilukavsky** [comment]
The function `problems(x)` needs an argument (your imported datafile with issues attached as an attribute). The function works fine after warnings, but after an error there is no datafile variable returned (therefore no attribute with problems to read and report). 
It would be more informative, if the `problems` function reported error if no argument is provided.

Your file should be read with `dat <- read_fwf(fn, fwf_empty(fn))` (the fields are not separated by tabs but by spaces to make fixed width fields)

**Comment by Ironholds** [comment]
I'm seeing the same issue with problems() at my end, FWIW.
