### ISSUE TITLE
Suppress "" in write_csv

### ISSUE THREAD

**Issue by wdenton** [hadley/readr#116]
write.csv has the quote parameter that controls whether or not the values are wrapped in "quotes". I suggest adding this to write_csv. 

I just used readr (and dplyr) to consolidate a huge data file into something smaller and more useful (thank you!). It's mostly two- and three-letters codes, and they all ended up wrapped in quotes when they didn't need to be. It would be nice to be able to turn this off when desired.

**Comment by hadley** [comment]
I'd rather not have this been an option as it adds complexity and makes it easier to create invalid csv files. It might be possible to only quote if the cell text contains a comma or quote.

**Comment by wdenton** [comment]
A quote-only-when-necessary option would be perfect.

**Comment by hadley** [comment]
But I don't think that would need to be an option - I'd just always do it
