### ISSUE TITLE
DateTime fails

### ISSUE THREAD

**Issue by okumuralab** [hadley/readr#120]
x = read_csv("DateTime\n2013-02-10 12:34:56")
fails. I have to supply col_types:
x = read_csv("DateTime\n2013-02-10 12:34:56", col_types="T")

x = read_csv("DateTime\n2013-02-10 12:34:56 JST")
doesn't fail, but the result is a character string, not POSIXct.

**Comment by okumuralab** [comment]
> parse_datetime("2015-04-12 00:00:00")
[1] "2015-04-12 UTC"
# Oops, I meant JST (Japan Standard Time)
> parse_datetime("2015-04-12 00:00:00", tz="JST")
[1] "2015-04-12 GMT"
 警告メッセージ: 
In as.POSIXlt.POSIXct(x, tz) : unknown timezone 'JST'
# Oops, is it Tokyo or Japan?
> parse_datetime("2015-04-12 00:00:00", tz="Japan")
[1] "2015-04-11 23:00:00 JST"
# Off-by-one hour error!

**Comment by hadley** [comment]
`2013-02-10 12:34:56 JST` isn't a ISO8601 date time because it has the time zone as a string.  I'll look into the off-by-one error.

**Comment by andres-s** [comment]
The off-by-one error appears to be daylight savings related:

```r
# In daylight savings
parse_datetime("2015-04-04 00:00:00", tz="Australia/Melbourne")
#> [1] "2015-04-04 AEDT"

# Not in daylight savings (Japan doesn't do daylight savings)
parse_datetime("2015-04-04 00:00:00", tz="Japan")
#> [1] "2015-04-03 23:00:00 JST"

# Not in daylight savings
parse_datetime("2015-04-06 00:00:00", tz="Australia/Melbourne")
#> [1] "2015-04-05 23:00:00 AEST"

# Not in daylight savings (Japan doesn't do daylight savings)
parse_datetime("2015-04-06 00:00:00", tz="Japan")
#> [1] "2015-04-05 23:00:00 JST"
```

I did some debugging of the `DateTime::localtime` function and it seems the `tm_isdst` member of the `struct tm` object is unassigned and getting filled with junk that just so happens to always be a positive integer, forcing `mktime()` to parse the string as a daylight savings time.

**Comment by hadley** [comment]
@andres-s oops. Would you mind making a couple of formal test cases? It should be an easy fix (`tm.tm_isdst = 0;`).
