### ISSUE TITLE
Multiple strings for missing values

### ISSUE THREAD

**Issue by TonyLadson** [hadley/readr#125]
I'm working on files that use many different strings to specify missing values e.g. "" (blank), NA, na, nr, nd. read_csv seems to only allow a single string.

    read_csv("x,y\n1,2\n3,4\nna,NA", na = c('NA','na'))
    Error: expecting a single value

It would be great if I could include multiple strings in the specification of missing values.

Thank you for all your work on readr.  It is very fast.

**Comment by rpruim** [comment]
I'll second this motion.

**Comment by hadley** [comment]
(This is the flip side of #114)

**Comment by jennybc** [comment]
:+1:

**Comment by mdlincoln** [comment]
:+1: on this, and again on #114 :smile:
