### ISSUE TITLE
parse_datetime support AM/PM indicator

### ISSUE THREAD

**Issue by luckyrandom** [hadley/readr#126]
something similar to '%p' of strptime can be useful.

It can be used to parse [NYC 311 service data](https://nycopendata.socrata.com/Social-Services/311-Service-Requests-from-2010-to-Present/erm2-nwe9). The format is `04/12/2015 02:41:17AM`, and I think such format is widely used.

**Comment by hadley** [comment]
Done in 52bbd20d6d87e5f2f9018ad534ea0cc87fed2c51

**Comment by jmarca** [comment]
Very cool.  Thanks.
