### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by elombardi-cleve** [hadley/readr#131]
I'm using rstudio .98 and RRO 8.0.1 (R version 3.1.2) in windows 8.1, and I'm getting this error:  Warning in install.packages :
  package ‘readr’ is not available (for R version 3.1.2)

I've tried to get the version off of github and I get this error:  
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/RRO/R-31~1.2/etc/x64/Makeconf" -f "C:/PROGRA~1/RRO/R-31~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="readr.dll" WIN=64 TCLBIN=64 OBJECTS="Collector.o DateTimeLocale.o RcppExports.o Source.o Tokenizer.o TokenizerFwf.o connection.o datetime.o parse.o read.o type_convert.o write_csv.o"' had status 127
ERROR: compilation failed for package 'readr'

I don't know what to make of these errors.

**Comment by hadley** [comment]
It's probably because you're using MRAN (http://mran.revolutionanalytics.com), which is date pinned and doesn't have the latest version of packages.   You'll need to contact revo for support.
