### ISSUE TITLE
Columns are read even if not mentioned in col_types in read_tsv

### ISSUE THREAD

**Issue by anders-sjogren** [hadley/readr#132]
From ?read_tsv:
> col_types	
> [...]
> If a list, it must contain one "collector" for each column. If you only want to read a subset of the columns, you can use a named list (where the names give the column names). If a column is not mentioned by name, it will not be included in the output. [...]

Bug reproduction steps

    read_tsv("1\t2\n3\t4\n",col_names=c("X","Y"),col_types=list("X"=col_integer()))

Expected result

      X
    1 1
    2 3

Observed result

      X Y
    1 1 2
    2 3 4

Sidenote: `read_tsv("1\t2\n3\t4\n",col_names=c("X","Y"),col_types=c("i_"))` yields the correct result.

**Comment by anders-sjogren** [comment]
A workaround is to define

    makeColTypesString<-function(colTypes,allColNames) {
      getColChar<-function(collector){
        if(is(collector,"collector_double")) return("d");
        if(is(collector,"collector_integer")) return("i");
        if(is(collector,"collector_character")) return("c");
        if(is(collector,"collector_logical")) return("l");
      }
      chars = sapply(allColNames, function(x){
        if(x %in% names(colTypes)) getColChar(colTypes[[x]]) else "_";
      })
      paste(chars,collapse="")
    }

and to use it as

    cnames=c("X","Y")
    ctypes=list("X"=col_integer())
    read_tsv("1\t2\n3\t4\n",col_names=cnames,col_types=makeColTypesString(ctypes,cnames))

**Comment by hadley** [comment]
Oops, yes, that's a documentation error. See also #72

**Comment by anders-sjogren** [comment]
Ok. IMHO: if it'd work as documented, I think it'd be neat.

**Comment by hadley** [comment]
That's what I had originally planned, but it's a huge pain if you just want to adjust the type of one column. That seems to be more common in practice - but I think it should be possible to have a solution where you just replace `list()` with something like `only()` and then you only get those cols.

**Comment by anders-sjogren** [comment]
Is there some `ignore` collector, that one could use to express that one would want to ignore that column (cf. "Ignore Token Processing" on http://www.codeproject.com/Articles/23198/C-String-Toolkit-StrTk-Tokenizer)

**Comment by anders-sjogren** [comment]
> but I think it should be possible to have a solution where you just replace list() with something like only() and then you only get those cols.

That seems like a good idea.
