### ISSUE TITLE
Multiple characters as delim

### ISSUE THREAD

**Issue by sidjai** [hadley/readr#137]
Would it be possible to have multiple characters for a delimiter? I ask cause I have a case with spaces and scientific notation like,
" 48.93, -81.14, 0.18E+03"

So I can get the first two with numeric parsing but the last one fails because I need that "E".

**Comment by hadley** [comment]
The numeric parsers should ignore leading and trailing spaces. I thought I had written them that way, but maybe I missed something.

**Comment by sidjai** [comment]
Oh they do, but they also ignore the exponential which makes the third column unreadable. With numeric parsing it would return "0.1803" instead of "180". With double parsing it would return a problem with the leading space.

**Comment by hadley** [comment]
Ooops, I was unclear - I meant numeric, double and integer should all ignore spaces.
