### ISSUE TITLE
col_logical()

### ISSUE THREAD

**Issue by plankter** [hadley/readr#141]
Please implement recognition of 1 and 0 as possible values for col_logical()

**Comment by hadley** [comment]
Can you provide a bit context? That seems like something you should fix up
after loading the data

On Saturday, April 18, 2015, Anton Rau <notifications@github.com> wrote:

> Please implement recognition of 1 and 0 as possible values for
> col_logical()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hadley/readr/issues/141>.
>


-- 
http://had.co.nz/
