### ISSUE TITLE
read_fwf fails to understand newlines when given a larger width number for the final column

### ISSUE THREAD

**Issue by justa9** [hadley/readr#146]
I would like to use read_fwf as a  replacement for read.fwf.

However, it seems like read_fwf ignores the newline character when given a larger width number for the final column

So, in a file like this (simplified form):

```
1.1  abcd
1.2  efghijkl
1.3  mnopq
1.4  rstuvwxyz
```

this call:

```
read_fwf(ratingsfile,  fwf_positions(c(1,6) , c(3, 15)), col_types="dc")
```

produces this output:

```
   X1         X2
1 1.1  abcd\n1.2
2 1.3 mnopq\n1.4
```

Is this something that's easy or appropriate to fix or should I just continue using read.fwf?

Thanks!

**Comment by hadley** [comment]
Is this a common format? It's not really fixed width if the last field has variable width.

**Comment by justa9** [comment]
This is not a modern format, however I have seen it many times on some legacy data dumps produced by state institutions (not US); all columns but the last are of fixed width, however the last column is allowed to vary.

Currently read.fwf can take care of this, however I would really like to benefit from the reported speed of read_fwf.
