### ISSUE TITLE
read_delim fails on multibyte delimiters (at least this one.)

### ISSUE THREAD

**Issue by earino** [hadley/readr#147]
Let's say you have to deal with weird data, and that data has basically every printable character under the sun embedded in it. No problem, you think to yourself, i'll just pick a unicode character as my delimiter.

I picked ❤ because I am a romantic at heart. I made this little file to test it:

    $ cat sample.hsv
    id❤name❤age
    1❤ed❤36
    2❤leigh❤NA 
    3❤natha❤14

I then reached for readr's read_delim and used it in such a fashion (after installing the latest version from github):

    > library(readr)
    > dat <- read_delim("/tmp/sample.hsv", "❤")

Unfortunately, it does this:

    > str(dat)
    Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	3 obs. of  3 variables:
     $ id          : int  1 2 3
     $ ��name: chr  "\x9d\xa4ed" "\x9d\xa4leigh" "\x9d\xa4natha"
     $ ��age : chr  "\x9d\xa436" "\x9d\xa4NA" "\x9d\xa414"

Should I not be using multibyte delimiters? (I mean, I know I shouldn't, but I guess I *really* shouldn't?) I also was surprised that it worked to figure out the columns, but it didn't strip them from the data, so I figure perhaps not all is lost?

In a perfect world, of course, this would just return a data frame with the 3 columns: c("id", "name", "age") with the appropriate data.

**Comment by hadley** [comment]
Currently I expect delimiters to be a single byte. I could use more, but it would add a lot of extra overhead for little gain.

**Comment by earino** [comment]
I understand and appreciate. I would think it would be possible that the overhead only be triggered when you have a multi-byte delimiter, but that's me talking and *not* providing a PR, so it's not super-duper valuable. Oh well, back to using <BEL> as a delimiter :) (will verify that it works.)
