### ISSUE TITLE
A easy way to read all columns as character

### ISSUE THREAD

**Issue by TuSKan** [hadley/readr#148]
Hi Hadley,

I couldn't find a easier way to read all columns as a character than this:
*header <- read_csv("file.csv", n_max = 1)*
*read_csv("file.csv", col_types = paste0(rep("c", ncol(header)), collapse = "") )*
I will be great to specify just one type for all columns like that:
*read_csv("file.csv", col_types = "c" )*

**Comment by eolembrain-leo** [comment]
Need one-for-all, auto recycled `col_types` argument setting, too!
It would be very helpful when one doesn't want col type to be imputed, but to keep all the data information as character for following maniputations.

**Comment by hadley** [comment]
You can now do `col_types = cols(.default = "c")`

**Comment by leoluyi** [comment]
```{r}
devtools::install_github("hadley/readr")
x <- "A\tB\n1\tD"
readr::read_tsv(x, col_types = cols(.default = "c"))
```

got this error message

```
Error: not compatible with STRSXP
In addition: Warning message:
Unnamed `col_types` should have the same length as `col_names`. Using smaller of the two. 
```

(readr version 0.1.1.9000)

**Comment by hadley** [comment]
@leoluyi please open a new issue
