### ISSUE TITLE
Problems with read_fwf/read_table regarding data type 

### ISSUE THREAD

**Issue by SebaStad** [hadley/readr#150]
I would like to change the read.fwf with read_fwf for performance reasons but stumbled accross some issues.

Both functions seem to have problems with negative values [or small float numbers ( e.g.4,186575E-05) I sorted this out]. At least thats when the problem occurs: both functions at times wont read the column as double but as character. ....

Also, when using the col_types command and defining "d" for "double" as type for the columns, the data will be seen as "double" but will be displayed as an integer number.

This is an example table:
```
 Col. 1        Col. 2        Col. 3        Col. 4        Col. 5        Col. 6
         01.01.2015 : 00             0 -4,186575E-05            20             0             0
         01.01.2015 : 01             1             0      18,98438     0,9130486    -0,0273375
         01.01.2015 : 02             2             0      18,35938     0,8662333    -0,0264375
         01.01.2015 : 03             3             0      17,65625      0,824937     -0,025425
         01.01.2015 : 04             4             0        16,875     0,8305327       -0,0243
         01.01.2015 : 05             5             0      16,17188     0,7444686    -0,0232875
         01.01.2015 : 06             6             0      15,46875     0,7137597     -0,022275
         01.01.2015 : 07             7           3,3      14,92188     0,5892583   -0,01673469
         01.01.2015 : 08             8           2,2        14,375     0,5842227   -0,01751889 
         01.01.2015 : 09             9           3,3      13,98438     0,5128642    -0,0153086 
         01.01.2015 : 10            10           7,2      13,90625     0,2812282  -0,009476549
```
When i now use:
```
 read_fwf(v.Path,col_positions = fwf_widths(c(24, rep(14,5)), col_names = NULL),skip = 1)
```
all lines with a negative value will be read as character. 
If i try to force it to read as double:
```
 read_fwf(v.Path,col_positions = fwf_widths(c(24, rep(14,5)), col_names = NULL),skip = 1, col_types="cddddd")
```
R will say that the numbers are "double" but they will be floored to integer values. See also
```
read_fwf(v.Path,col_positions = fwf_widths(c(24, rep(14,5)), col_names = NULL),skip = 1, col_types="ciiiii")
```
Thanks in advance :)

**Comment by SebaStad** [comment]
![dau](https://cloud.githubusercontent.com/assets/12084466/7298803/1f5702da-e9d2-11e4-8472-94516aaf6a2e.png)

Goosh... Can somebody help me to get the table in the correct format? in the Picture you should be able to see it...

**Comment by hadley** [comment]
Are you sure that's a fixed width file? It seems to include a combination of tabs and spaces

**Comment by SebaStad** [comment]
We get those tables as output from our programm and it has indeed a fixed format. Though it does not have a set distance between each column. The date column occupies the first 24 spaces, each following column 14 spaces:
```
fwf_widths(c(24, rep(14,5)),...
```
I dont know, if this could be the source of the problem, but i can say that this options do work for the regular read.fwf function.

Thanks a lot :)

**Comment by hadley** [comment]
Could you please upload a sample file somewhere?

**Comment by SebaStad** [comment]
I will on Tuesday. 

Thanks a lot in advance :)

**Comment by SebaStad** [comment]
I have saved a similar file here:
http://s000.tinyupload.com/index.php?file_id=14721550836061411419

This table has 8 columns, with the same properties as the small table.
My commands to read the functions are:
```
read_fwf(test.table, col_positions = fwf_widths(c(24, rep(14,7)), col_names = NULL),skip = 1)
```
and
```
read_fwf(test.table, col_positions = fwf_widths(c(24, rep(14,7)), col_names = NULL),skip = 1  , col_types= "cddddddd" )
```

The first command will give me the following datatypes for the columns:
"character", "integer", "character", "character", "double", "character", "character", "integer"

I dont mind the integer, but all except the first character are wished to be double.
If i then run the second command, i get the following datatypes:
"charcter", "double", "double", "double", "double", "double", "double", "double"

BUT all values are set to integer values :(
I hope this helps.

Once again, thanks a lot in advice :)

**Comment by SebaStad** [comment]
Hi there :)

Im sure youre busy with more important stuff, but can you give me a rough estimation on when or if you are trying to fix this?

Thanks in advance.

**Comment by hadley** [comment]
No, sorry. Probably by the end of the year.

**Comment by SebaStad** [comment]
Thats sad to hear, but thanks a lot nevertheless.

**Comment by hadley** [comment]
The following code now works for me:

```R
read_table("         Col. 1        Col. 2        Col. 3        Col. 4        Col. 5        Col. 6
01.01.2015 : 00             0 -4,186575E-05            20             0             0
01.01.2015 : 01             1             0      18,98438     0,9130486    -0,0273375
01.01.2015 : 02             2             0      18,35938     0,8662333    -0,0264375
01.01.2015 : 03             3             0      17,65625      0,824937     -0,025425
01.01.2015 : 04             4             0        16,875     0,8305327       -0,0243
01.01.2015 : 05             5             0      16,17188     0,7444686    -0,0232875
01.01.2015 : 06             6             0      15,46875     0,7137597     -0,022275
01.01.2015 : 07             7           3,3      14,92188     0,5892583   -0,01673469
01.01.2015 : 08             8           2,2        14,375     0,5842227   -0,01751889 
01.01.2015 : 09             9           3,3      13,98438     0,5128642    -0,0153086 
01.01.2015 : 10            10           7,2      13,90625     0,2812282  -0,009476549",
  locale = locale(decimal_mark = ","))
```

I think the problem was the use of the decimal comma rather than the decimal point, which readr did not previously support well.
