### ISSUE TITLE
If col_names=F col_types can't be used to skip columns

### ISSUE THREAD

**Issue by mikerspencer** [hadley/readr#153]
e.g. if x has 10 columns with no header then:

read_csv(x, col_names=F, col_types="ccd")

generates:

Error: You have 10 column names, but 3 columns

**Comment by hadley** [comment]
If you're using the compact form, you need to use `_` to skip columns.

**Comment by mikerspencer** [comment]
Sorry, I should have written in the original (brain not with it, down with a nasty cold):

read_csv(x, col_names=F, col_types="ccd_______")

I suspect it's generating column names, X1:X10, prior to defining the data frame.
