### ISSUE TITLE
ignores quotes in determining column type?

### ISSUE THREAD

**Issue by dchudz** [hadley/readr#155]
Seems like it would be better to interpret the quotes as indicating that a column has strings (like `read.csv` and `fread` both do):

```
> library(readr)
> 
> my_csv <- 
+ 'Id,Word
+ "34235","mostly"
+ "4234","I"
+ "23533","really"
+ "234323","like"
+ "2323423","readr"'
> 
> df <- read_csv(my_csv)
> str(df)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	5 obs. of  2 variables:
 $ Id  : int  34235 4234 23533 234323 2323423
 $ Word: chr  "mostly" "I" "really" "like" ...
> 
```

**Comment by hadley** [comment]
Is this causing problems for you? Most of the csv specs (such as they are), say that quotes should be ignored for the purposes of typing variables.
