### ISSUE TITLE
read_table corrupts last column names

### ISSUE THREAD

**Issue by coolbutuseless** [hadley/readr#166]
When reading a simple whitespace separated file with read_table()

```
 MAID        TIME        AMT
  1.0000E+00  0.0000E+00  2.5000E+00
  1.0000E+00  0.0000E+00  0.0000E+00
```

The parsed colname for the final column is corrupt:
```r
> read_table("test_nonmem2.txt")
Source: local data frame [2 x 3]

  MAID TIME AMT\n  1.000
1    1    0          2.5
2    1    0          0.0
```

**Comment by hadley** [comment]
That isn't a valid format for `read_table()` - it excepts the whitespace columns to be in consistent positions

**Comment by coolbutuseless** [comment]
(Note: a cut/paste error means the headers in my above example weren't aligned)
So all values must take the same amount of space regardless of whether it's a header row or not?

```
MAID        TIME        AMT
1.0000E+00  0.0000E+00  2.5000E+00
1.0000E+00  0.0000E+00  0.0000E+00
```
The above (with aligned column starts) still causes a column misread:
```r
> read_table("test.txt", col_names=TRUE)
  MAID TIME AMT\n1.0000
1    1    0         2.5
2    1    0         0.0
```

But if I pad the column names they are read correctly:
```
MAIDxxxxxx  TIMExxxxxx  AMTxxxxxxx
1.0000E+00  0.0000E+00  2.5000E+00
1.0000E+00  0.0000E+00  0.0000E+00
```
```r
> read_table("test.txt", col_names=TRUE)
  MAIDxxxxxx TIMExxxxxx AMTxxxxxxx
1          1          0        2.5
2          1          0        0.0
```

So length of column names must match the data width for read_table()?

This is related to issue #121, because read_table() works about 20x faster than read.table() on NONMEM files, with the only problem being the parsing of the header for column names.

**Comment by hadley** [comment]
`read_fwf()` (and hence `read_table()`) expects every row to have the same number of characters

**Comment by hadley** [comment]
If the problem is just reading the header row, maybe you should just skip it and read it yourself?

**Comment by coolbutuseless** [comment]
That's what I've done for now, but I would hazard that the probability that the column names are ever the same width as the data in a FWF is very very low, and the times when the current read_table header parsing works as a user expects would be rare.

Would there be any benefit to parsing the header slightly differently by default for fwf?  Or as an option e.g. `relaxed_headers = TRUE`. 

Or am I an outlier? :)
