### ISSUE TITLE
Growing vector strategy. 

### ISSUE THREAD

**Issue by romainfrancois** [hadley/readr#17]
Sometimes we don't know the final size and it is too expensive or perhaps impossible to calculate it in advance. For example when we read from several files or connections, I don't think we can realistically assume that users will give us the number of lines in each file. 

So we can use `std::vector` to accumulate data or perhaps use `R_alloc` to get some buffer garbage collected memory, or perhaps both (see http://blog.r-enthusiasts.com/2014/01/21/r-transient-allocator.html which can be easily extracted out Rcpp11 if needed).

**Comment by hadley** [comment]
Now (cunningly) implemented in read_csv
