### ISSUE TITLE
using readr then converting to data.table causes unexpected behaviour..

### ISSUE THREAD

**Issue by zeltak** [hadley/readr#173]
Hi
First of all thx for readr i really love it. one thing i have noticed is that when i import with readr a csv then convert to DT and try a DT opertaion it fails
ie:
out<- read_csv("/media/NAS/Uni/Data/MV3/Out/v01.2003.csv")
out<-as.data.table(out)
> out[, day:=as.Date(strptime(date, "%d/%m/%Y"))]
Error in `:=`(day, as.Date(strptime(date, "%d/%m/%Y"))) : 
  Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":=").

any clue? using dplyr which also creates tbl_df data works well, its just happens when i use read_csv

thx!

z

**Comment by hadley** [comment]
That seems like a data table bug to me.
