### ISSUE TITLE
read_csv crashes R session on particular .csv file

### ISSUE THREAD

**Issue by Swarchal** [hadley/readr#175]
I was using read_csv on a batch of similar files, which open fine with read.csv(). One of the files is throwing an error and crashing the R session. I get the error:

> Assertion failed!

> Program: C:\RStudio\bin\x64\rsession.exe
> File: d:/RCompile/CRANpkg/lib/3.2/BH/include/boost/spirit/home/support/detail/pow10.hpp, Line 87

> Expression: dim < sizeof(exponents)/sizeof(double)

With sessionInfo() :

> R version 3.2.0 (2015-04-16)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1

> locale:
> [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
> [3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
> [5] LC_TIME=English_United Kingdom.1252    

> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     

> other attached packages:
> [1] readr_0.1.0

> loaded via a namespace (and not attached):
> [1] tools_3.2.0 Rcpp_0.11.6

This file has the same column names and number of rows as multiple other files that are opening without a problem, so I can't really get my head around it.

**Comment by hadley** [comment]
Can you please provide a link to the csv that causes a problem?

**Comment by Swarchal** [comment]
https://dl.dropboxusercontent.com/u/79810285/mm_mdaImage.csv

**Comment by hadley** [comment]
Hmmm works for me.  Could you please try with the latest dev version?

**Comment by Swarchal** [comment]
Ok, it's working fine with the dev version.

**Comment by iMissile** [comment]
Hi, I have the same issue with another dataset. 
https://www.dropbox.com/s/o9008ju4x9a4aj6/train.csv?dl=0
I've installed dev version.

**Comment by hadley** [comment]
@iMissile please open a new issue
