### ISSUE TITLE
Different results with integers and double numbers

### ISSUE THREAD

**Issue by blaquans** [hadley/readr#176]
I try to read a vector of integer numbers in R. I'm puzzled by the fact that `read_csv()` returns a negative number by default for some big numbers. When I specify the type as double, I don't have the same problem and the outcome is consistent. 

Here is an example with one number : `3520450200013`. 

By default, `read_csv` returns a negative number : 

    > read_csv("siret\n3520450200013")
            siret
    1 -1422982707

When I add `col_types` as double, the outcome is correct : 

    > read_csv("siret\n03520450200013", col_types = "d")
           siret
    1 3.52045e+12

When I add `col_types` as integer, the outcome is negative (ie the same as the first case)

Why do I have a negative number in the first case ? Is it a bug ? I think that it can be really confusing for people. 

Update : I've seen on [StackOverflow](http://stackoverflow.com/questions/14589354/struggling-with-integers-maximum-integer-size) that there is a maximum value for integers in R. I think it would be nice to coerce integers to be treated as double when they are greater than the maximum value.

**Comment by hadley** [comment]
Both now give the correct answer for me.
