### ISSUE TITLE
problems() missing tbl_df print limit

### ISSUE THREAD

**Issue by JakeRuss** [hadley/readr#177]
I think the `tbl_df` print method hasn't been imported to `readr`.

If I load `readr` alone and I look at `problems(df)` it prints all of the rows to the console. I started to suggest limiting the feedback, but then once I loaded `dplyr` also, `problems(df)` behaved as I expected 
and printed only the first 10.

**Comment by hadley** [comment]
Yeah, that's by design.

**Comment by JakeRuss** [comment]
I'm sure you have a good reason(s). It just clashed with the set of expectations I've built using your other packages. And now I see this issue is already covered in the README. Sorry to make you repeat yourself!
