### ISSUE TITLE
skip lines after the header

### ISSUE THREAD

**Issue by MySchizoBuddy** [hadley/readr#179]
In most engineering data sets we have a row of units after the header. I would like the ability to skip rows after the header and then read in data. I know I can do this
 
    cec.modules <- read_csv("CEC Modules.csv") %>% slice(3:nrow(.))

But because the second row is character of units it reads all numeric columns as characters. Example of dataset

```
Source: local data frame [13,955 x 22]

                     Name BIPV       Date     T_NOCT      A_c     N_s
1                   Units                          C       m2        
2                     [0]                 cec_t_noct cec_area cec_n_s
3  BEoptCA Default Module    Y 12/17/2008         65     0.67      18
4          Example Module    Y  4/28/2008         65     0.67      18
5     1Soltech 1STH-215-P    N  10/7/2010       47.4    1.567      60
6     1Soltech 1STH-220-P    N  10/4/2010       47.4    1.567      60
```
I want to skip rows 1 and 2 and then autodetect the column type. T_NOCT, A_c and N_s have to be numeric.

**Comment by hadley** [comment]
It's hard to think what a general specification should be and it's pretty easy to work around

```R
col_names <- names(read_csv("CEC Modules.csv", n_max = 0))
read_csv("CEC Modules.csv", col_names = col_names, skip = 3)
```

**Comment by e-clin** [comment]
It would be great for `read_csv()` to have `read.csv()`'s `blank.lines.skip` argument to skip blank lines after the header.

**Comment by e-clin** [comment]
@jimhester Thanks for your reply.

Yes it does, but it stops working when there are metadata before the header, for which `skip = _n_` is also required.

In my case, such a file resulted in the header being duplicated as Row 1 in the data, and all column types being mis-identified as characters. I tried toggle `col_names` but it did not help.

`read.csv()` with `skip = n` and `blank.line.skip = T` read the data in correctly, but it is a pity that it does not parse date and time automatically.

**Comment by cataclysmic** [comment]
I have a blank line at the end of a csv which is read using read_csv2...
