### ISSUE TITLE
write_*(..., append = TRUE) creates new file

### ISSUE THREAD

**Issue by npjc** [hadley/readr#181]
if I try to `append` to a __non-existing file__ it creates the file (_silently_).

```r
does_not_exist <- "dne.tsv" # this file/connection does not exist in my working directory
readr::write_tsv(mtcars, does_not_exist, append = TRUE, col_names = TRUE)
```
from `?write_tsv`:
```r
append	  If FALSE, will create a new file. If TRUE, will append to an existing file.
```

I think three options here:

1. simply note the behaviour more precisely in the documentation (this was unexpected for me based on reading it).
2. message / warn user if file did not exist and was created. (my least favourite).
3. additional argument in `write_delim` to make the user declare if they want to _both append if the file exists and create if it does not.

if @hadley thinks this is a thing I can have a go at a PR if that would help.

**Comment by hadley** [comment]
I think improved docs would be best, and a PR would be awesome.
