### ISSUE TITLE
Orphaned

### ISSUE THREAD

**Issue by wibeasley** [hadley/readr#182]
I noticed that CRAN designated this package as 'orphaned'.  
![image](https://cloud.githubusercontent.com/assets/1372890/7891968/6f216a34-0616-11e5-881f-8a2a321ec511.png)

Since I think this field is the main way humans are notified, I wondered if their system was able to notify you successfully.

**Comment by hadley** [comment]
No, it's an unrelated problem :/

**Comment by wibeasley** [comment]
Cool.  Just wanted to make sure you were aware of a CRAN problem.  Have fun with that.

By the way, I'm  enjoying readr, especially not having to write `stringsAsFactors=F` everywhere.
