### ISSUE TITLE
read_csv versus read.csv for pushing data chunks to sqlite

### ISSUE THREAD

**Issue by vnijs** [hadley/readr#185]
It seems read_csv slows down quite a bit compared to read.csv when reading a csv file in chunks and pushing to an sqlite file. The main advantage for read.csv seems to be that it can avoid skipping through the file each time by using an open file connection (i.e., open(file(...)) ). See gist below.

https://gist.github.com/vnijs/e53a68c957747e82c2e3

In the simulation using read_csv to read the whole file in one go is actually faster than read.csv working in chunks but for files that are close to or larger than system memory reading the data in chunks would be useful.

**Comment by hadley** [comment]
This would require a complete rewrite of quite large chunks of readr, so it's low priority for now.

**Comment by hadley** [comment]
Duplicate of  #76

**Comment by vnijs** [comment]
Makes sense. Thanks for the update @hadley
