### ISSUE TITLE
na for write_csv would be cool

### ISSUE THREAD

**Issue by ckluss** [hadley/readr#187]
write_csv(..., na="")

**Comment by npjc** [comment]
Why not do:

```r
df[is.na(df)] <- ""
write_csv()
```

IMHO this is clearer to understand at a glance and you keep data output and data mutation as distinct as possible.

**Comment by andres-s** [comment]
That's neat! I didn't know `is.na` worked sensibly with data frames. However, this approach doesn't seem to play well with factors:
```r
d <- data.frame(x = as.factor(c('foo', NA)))
d[is.na(d)] <- " "
#> Warning message:
#> In `[<-.factor`(`*tmp*`, thisvar, value = " ") :
#>   invalid factor level, NA generated
```
and it also has the side effect of type casting integer, double and logical columns to character:
```r
e = data.frame(i = as.integer(c(1, NA)), d = c(0.5, NA), l = c(T, NA))
e[is.na(e)] = " "
str(e)
#> 'data.frame':	2 obs. of  3 variables:
#>  $ i: chr  "1" " "
#>  $ d: chr  "0.5" " "
#>  $ l: chr  "TRUE" " "
```
I'm with @ckluss on this one, I think an `na` option would be helpful--I often get clients requesting specific missing encodings ("", " ", "NULL", but not "NA" so far). @hadley, what do you think? I'd be happy to implement it if you think it's a good idea.

**Comment by akhmed1** [comment]
+1.
This feature is very important. Say, PostgreSQL is expecting "\N" as NULLs when importing. MySQL is looking for "NULL" as NULL and so on. (One can use that trick suggested by @npjc above for character types but not for integers.)
