### ISSUE TITLE
support UTF-8 fules, allow the 'encoding' option in read_csv

### ISSUE THREAD

**Issue by lucasmation** [hadley/readr#191]
read_csv is great. But does not allow me to read my UTF-8 (portuguese caracters) correctly. That would be great. Tks!

**Comment by larmarange** [comment]
This issue seems general, as the same problem occurs with `read_file` or `read_delim`

**Comment by larmarange** [comment]
This issue seems to be a duplicate of https://github.com/hadley/readr/issues/40
