### ISSUE TITLE
add `text` argument à la read.table

### ISSUE THREAD

**Issue by jennybc** [hadley/readr#192]
This would be very useful: add something like the `text` argument of `read.table()`:

> character string: if file is not supplied and this is, then data are read from the value of text via a text connection. Notice that a literal string can be used to include (small) data sets within R code.

**Comment by jennybc** [comment]
OK I now see that I can provide text via the `file` argument iff I preprocess with `paste(my_text_vector, sep = "\n")`. So the functionality is here already. Feel free to close if you're not interested in pursuing any further.

**Comment by jennybc** [comment]
Related … I feel like I must be doing something silly, but am struggling to read data in from a literal string. I've tried moving the whitespace around every which way in this example but can't get the behaviour I'd expect from my years with `read.table()`.

```
modat <-
"month days
jan   31
feb   28
mar   31"
```

```
> read_table(modat)
  month  days
1   jan 31\nf
2   mar    31
> read.table(text = modat, header = TRUE)
  month days
1   jan   31
2   feb   27
3   mar   31
```

**Comment by hadley** [comment]
The definition of `read.table()` and `read_table()` are a bit different - `read_table()` looks for the same columns of whitespace in every row

**Comment by npjc** [comment]
why not?
```r
readr::read_tsv(modat)
#> month days
#> 1   jan   31
#> 2   feb   28
#> 3   mar   31
```

**Comment by jennybc** [comment]
Because I had assumed that `read_tsv()` would, um, be looking for *tabs* as separators. But I'm glad to know it's a flexible option for the literal string case.

**Comment by npjc** [comment]
haha... I actually assumed the seps were tabs... so why did that work (it shouldn't right?)?

I copied and pasted `modat` and it's definition from your post into __RStudio__...did it convert it for me?...(my tab width is set to 2 spaces)... seems it did not --> if i then paste it into sublime it is indeed spaces:

![screen shot 2015-06-16 at 9 52 49 am](https://cloud.githubusercontent.com/assets/6063192/8188892/7b6b9710-140d-11e5-84cb-4601ddd30ec7.png)

![screen shot 2015-06-16 at 9 53 56 am](https://cloud.githubusercontent.com/assets/6063192/8188931/b6ae42f0-140d-11e5-97ed-c8c0e758908b.png)

**Comment by npjc** [comment]
I have deleted the embarrassment as `str()` reveals i need to stay away from programming when sleep deprived...

```r
readr::read_tsv(modat) %>% str()
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	3 obs. of  1 variable:
 $ month days: chr  "jan   31" "feb   28" "mar   31"
```

this is definitely not what's wanted.
