### ISSUE TITLE
unexpected parsing results for: 6e5

### ISSUE THREAD

**Issue by npjc** [hadley/readr#197]
Consider:
```r
tmp <- "590452\t592968\n594741\t6e+05" #N.B. 6e+05
```

##### I get unexpected results (one WITHOUT warning) depending on the parser:

If I don't specify or use `col_types = "id"`:
```r
readr::read_tsv(tmp, col_names = F) # col_types = "id" gives this result also.
#> Source: local data frame [2 x 2]
#> 
#> X1     X2
#> 1 590452 592968
#> 2 594741 600000
```

where `X1` is (int) and `X2` is (num).

But if i specify but if I ask for `parse_numeric()`:

```r
read_tsv(tmp, col_names = F, col_types = "nn")
#> Source: local data frame [2 x 2]
#> 
#> X1     X2
#> 1 590452 592968
#> 2 594741    605
```

__SILENT AND DEADLY `605 != 6e5`__

If I ask for integer:

```r
read_tsv(tmp, col_names = F, col_types = "ii")
#> Source: local data frame [2 x 2]
#> 
#> X1     X2
#> 1 590452 592968
#> 2 594741      6
#> Warning message:
#>   1 problems parsing literal data. See problems(...) for more details.
problems(.Last.value)
#> Source: local data frame [1 x 4]
#> 
#> row col               expected actual
#> 1   2   2 no trailing characters   e+05
```

Here I get a warning (which is good because `6` is definitely incorrect. But I would expect that since:
```r
as.integer('6e+05')
#> [1] 600000
as.integer(6e+05)
#> [1] 600000
```
I should get `600000` _not_ `6`.

**Comment by hadley** [comment]
Here's a minimal reprex:

```R
parse_numeric("6e+05")
parse_integer("6e+05")
```

The behaviour for `parse_numeric()` is expected (and documented). But it's a bit confusing so I might make the parser less flexible.

And I think using `6e+05` for integers is non-standard, so I don't plan to support it.
