### ISSUE TITLE
problems() warning workflow with skip

### ISSUE THREAD

**Issue by npjc** [hadley/readr#198]
if I ever call `problems()` I tend to call `read_lines()` on the file and pull out the lines of interest to see what's what. However, if I had specified `skip` in `read_tsv()` to get the actual lines I want I need to add `skip` to `problems()$row`. 

This is fine if I am reading in one file but in reality I'm reading in 100s and `skip` is actually computed for each file according to a simple guessing function (see end of this post)...which means I have to keep `skip` around for each file.

__issues:__

1. Would be possible to add to `problems()` so that I could have the `$row` and the `read_lines()[row_idx]` equivalent right there. An alternative solution would be to have a `skip` parameter in `read_lines(..., skip = )` (I prefer this actually since it's consistent with all the other `read_*`.

2. It would be awesome to be able to pass the problematic line indices directly to `read_lines()`; so that you could do `read_lines(..., sub = 10:20)` and `read_lines(..., sub = c(1,5))` to get lines 10:20 and c(1,5), respectively. A naive implementation could be where `n_max` is computed from `max(sub)` and `sub` is just used to subset the result e.g.:`read_lines(n_max = max(sub))[sub]`.

_________ 

the simple guessing function:
```r
#' guess how many lines to skip by looking for the first line that has the expected number of
#' delimiters. 
#'
#' @param expect_delim delimiter to expect
#' @param expect_n_vars number of vars (cols) to expect
#' @param n_max passed to read_lines's n_max
guess_skip <- function(file, expect_delim, expect_n_vars, n_max = 100) {
  lines <- readr::read_lines(file, n_max = n_max)
  delims_per_line <- stringi::stri_count_fixed(lines, expect_delim)
  first_data_line <- which.max(delims_per_line)
  stopifnot(delims_per_line[first_data_line] == expect_n_vars - 1)
  first_data_line - 1
}
```

**Comment by npjc** [comment]
A note about `guess_skip()` and `count_fields()`: 

I am aware of `count_fields()` which is really useful but if I have to read the whole file just to check a header that I know can't be more than say 100 lines it gets pricey... it would be sweet if it had `n_max` and `sub` params to limit the total number of records (rows) and count fields on only a subset of records (see #199 ), respectively.

From what I can tell modifying `count_fields_` (see diff screenshot below) to gain `n_max` seems to work:

![screen shot 2015-06-17 at 10 22 11 pm](https://cloud.githubusercontent.com/assets/6063192/8224684/9b41674e-153f-11e5-8a19-3f65e433793f.png)

**Comment by hadley** [comment]
@npjc want to do a PR to add `n_max` to count_fields?

**Comment by npjc** [comment]
@hadley sure will have a go this weekend.

**Comment by hadley** [comment]
I think the first part of this issue is a no go - I think it's more important to be able to match up the `problems()` with the data that you loaded, not the original rows. But I'd consider a pull request if you wanted to add a variable line = `row + skip`

**Comment by npjc** [comment]
@hadley see #243 added `n_max` and test file for `count_fields()`. I think your comment is right on for `problems()` and makes me think really the appropriate way to deal with it would be through #199 where you investigate the problems based on the rows you read in. But it's just a wish!
