### ISSUE TITLE
read a subset of a file

### ISSUE THREAD

**Issue by npjc** [hadley/readr#199]
(see also: #198 2.)

It would be very useful to have the ability to `read_*` a subset of rows according to a vector which specifies the indices of a row where `sub = c(1:10, 20)` would get you the first 10 lines and the 20th lines parsed as a tbl.

 ...so that I could for example, `sample(...)` to get a subset of a (2-230ish Gigs) file:
```r
n_lines <- # system("wc -l file.tsv") ...to get number of lines
subset_size <- n_lines / 100
vector_of_rows <- sample(1:n_lines, subset_size)
read_tsv("file.tsv", sub = vector_of_rows)
```

But generally speaking where you could read in a subset of a file based on a vector of indices you provide (this means if you know something about the file and can compute the row indices which are of interest you can supply them into `read_*`).

**Comment by hadley** [comment]
I'd rather implement reservoir sampling directly inside readr. But this requires some fairly big thinking about how to make readr more internally extensible, so I'm going to close for now.
