### ISSUE TITLE
read_delim slows down significantly after reading in about 10+ files in a row within a R session

### ISSUE THREAD

**Issue by ajjeon** [hadley/readr#203]
It's just a phenomenon i'm reporting here. I have 18 files to read in (each of 1.5G to 3.5G in size) and read_delilm works beautifully and very quickly (each file take a couple of minutes). However, it slows down significantly when it reaches 15th file (takes hours). On the other hand, in another fresh R session read_delim on the file (about 1G in size) works wonderfully and quickly again. So i think the issue is not within the file to be imported but something about read_delim. I wonder if there's any reason behind it and any way to improve on it?

**Comment by hadley** [comment]
No idea, sorry.
