### ISSUE TITLE
Cover all variations of csv formats

### ISSUE THREAD

**Issue by joehl** [hadley/readr#208]
It would be nice if read_csv could cover the great variety of (fuzzily) defined csv formats, at least if the filespec is known. Automatic detection is less important and can build on this. Here is what I know about csv-file variation:

- BOM or not
- character encoding
- row separator[s] (one or two and which ones, file might come from unix/win/mac)
- list separator
- decimal separator
- quoting character {",'}
- how to escape the quoting character in strings (\" \' "" '' etc. )
- whether strings are quoted {never|always|only if needed}
- whether numbers are quoted
- whether row- and column-separators are escaped within strings
- allow/disallow multi-lines in quoted strings (disallowing is a precondition for skipAbytes= and abytes below)
- different ways to code multi-lines in quoted strings {hard break, soft break}
- different NA strings, possible with multiple of them possible each with more than one character
- header {yes|no}
- header {quoted|unquoted}
- comment characters marking lines to skip
- whether to interpret (and count) empty lines as completely missing record or to skip it. 
- whether to strip white space around unquoted strings

**Comment by hadley** [comment]
It already covers many of those options. I'm happy to add more, but only as people actually use them.
