### ISSUE TITLE
Define NA when reading the table

### ISSUE THREAD

**Issue by MySchizoBuddy** [hadley/readr#210]
If a column contains TRUE, FALSE and ? for NA. readr generates warning that it doesn't understand ? on a logical column. 
Allow an option to define NA so that when it hits ? or -9999 it reads it as NA

**Comment by hadley** [comment]
See the `na` argument

**Comment by MySchizoBuddy** [comment]
na argument takes only one value. allow it to take more than one values. the tmy3 weather dataset uses both ? and -9900 to represent NAs.

**Comment by mdlincoln** [comment]
Duplicate of #190
