### ISSUE TITLE
col_percent

### ISSUE THREAD

**Issue by hadley** [hadley/readr#211]
Should automatically be able to detect percentages

**Comment by jennybc** [comment]
Is this purely aspirational or is the ability to deal with percentages already here -- and it's just the "automatic detection" part that's missing? I can't find any evidence of percentage-handling code from searching the repo. [I need this too](http://stackoverflow.com/questions/31520605/read-cell-values-without-formatting-into-r-with-googlesheets) and would be happy to rely on `readr`.

**Comment by hadley** [comment]
Purely aspirational - it's probably a ~30 min job

**Comment by jennybc** [comment]
What is conversion rate of Hadley minutes to other people's minutes?

Related Q: Is this a pure R task?

**Comment by hadley** [comment]
It's pretty much a pure C++ task :/
