### ISSUE TITLE
col_euro_double and parse_euro_double don't work with negative value

### ISSUE THREAD

**Issue by Titolondon** [hadley/readr#213]
Hey, 

detection do not work with negative value for `.` decimal separator.
`parse_double("-16.5")` gives:
```
[1] -16.5
```
 but `parse_euro_double("-16,5")` gives :
```
[1] NA
attr(,"problems")
  row col expected actual
1   1  NA a double  -16,5
Warning message:
1 problems parsing input. See problems(...) for more details. 
```
Is this a known issue ? 
I think it is related with issue #174 

Thanks

**Comment by hadley** [comment]
Took me a while to find this one character error!

**Comment by Titolondon** [comment]
Thank you Hadley!
