### ISSUE TITLE
allow write_csv to be nested into pipe flow

### ISSUE THREAD

**Issue by hankinslu** [hadley/readr#220]
For the purpose of documenting progress through multiple piped functions it would be convenient if write_csv() would invisibly return what it saved. This idea was inspired by the recent addition of a similar feature to how print handles the tbl_df structure.

**Comment by hankinslu** [comment]
Using the tee-pipe %T>% was suggested as an elegant work around. Clearly the write_csv operation does not modify the data.frame and so the %T>% just allows the flow to continue past the write_* function.

**Comment by hadley** [comment]
Yeah, I think that's the best solution.  Otherwise it's a bit hard to implement because `read_csv()` returns the output as a string when `file = ""`
