### ISSUE TITLE
Data package support?

### ISSUE THREAD

**Issue by psychemedia** [hadley/readr#226]
Whilst CSV etc is in part so flexible is because it's easy to use informally, the wide variety of conventions associated with X delimited files, and the lack of semantics or typing associated with column definitions, (though conventions can go someway to addressing that, informally at least) means that parsers have to use all sorts of heuristics to parse the files sensible.

Tools like `readr` go a long way towards providing a means of getting data into a structured and typed data frame in a painless way (things like `pandas` provide similar tools in the `scipystack`) but more often than not we lose the typing and semantics when we save the data out again.

I wonder though if we should also be thinking about supporting and using packaging formats such as [data packages](http://data.okfn.org/doc/data-package) that augment CSV exports with JSON metadata files. I don't for one minute imagine that folk would start to use them widely, but as a transport format moving data files between systems and opendata portals such as CKAN powered ones, they do provide a relatively lightweight "progressive enhancement" to CSV files that can make it easier to load in a file that has already been saved from a structured, typed representation such as a dataframe.

There are already a few packages out there that seem to support this format - [RODProt](https://github.com/QBRC/RODProt) and [dpmr](https://github.com/christophergandrud/dpmr). Perhaps including support for the format in `readr` would be useful?

*Disclaimer - data packages and CKAN are Open Knowledge activities; I'm occasionally affiliated with that organisation.*

**Comment by hadley** [comment]
I am thinking about it, but it's not high on my priority list. I would review a PR that added support (if I was convinced that the format was good enough to gain wide traction in the R community)
