### ISSUE TITLE
read_csv reads strings with "-" as date

### ISSUE THREAD

**Issue by felixhaass** [hadley/readr#228]
`read_csv()` reads a string that contains a `-` always as a date, e.g. `3-19`, but throws an error because the date is not complete. In the dataset I'm using, this denotes an ID string, however, and should be preserved as a string.

Here's a minimal working example:

```
fileConn<-file("test.csv")
writeLines(c("id, value","3-19, 5.0"), fileConn)
close(fileConn)

df <- read_csv("test.csv")
```
This produces:
```
> df <- read_csv("test.csv")
Warning message:
1 problems parsing 'test.csv'. See problems(...) for more details. 
> problems(df)
Source: local data frame [1 x 4]

  row col           expected actual
1   1   1 date like %Y-%m-%d   3-19
```
Now, this ends up as `NA`:

```
> df
Source: local data frame [1 x 2]

    id value
1 <NA>     5

```

**Comment by hadley** [comment]
More minimal reprex:

```R
readr::read_csv("x,y
1989-90,1
1990-91,2")
```

Likely because `CollectorDate::canParse()` is accepting partial matches

**Comment by Huade** [comment]
Works if specify `col_types` as character:
```r
readr::read_csv("period\n2008-2012\n2009-2013", col_types = "c")
```

**Comment by hadley** [comment]
Even more minimal reprex

```R
collectorGuess(c("1989-90", "1990-91"))
```
