### ISSUE TITLE
timezone and format as optional arguments to read_csv, etc.?

### ISSUE THREAD

**Issue by ijlyttle** [hadley/readr#230]
The proposal is to be able to specify a timezone and/or format for the date-times in a file, without having to specify anything explicitly in `col_datetime()` in `col_types`.

This would relieve the user (error-prone user, in this case) from having to count columns and specify the rest of the column parsers.

This would require that all date-times in a file have the same format, and impose the same timezone on all parsed date-times, which may be reasonable.

Maybe something like:

```
read_csv(..., opt_datetime(format = "", tz = "UTC"), ...)
```

Is this worth considering?

**Comment by hadley** [comment]
I think it's worth considering, but passing down options so they get to the right place is going to be tricky. Maybe `col_types_standardise()` could take an additional list of options? I think the space of parameter names is going to be distinct enough that something like this will be ok:

```R
read_csv(..., options = list(tz = "US/Central"))
```

(Although currently `format` would affect both `date` and `datetime` which we probably want to avoid)

**Comment by hadley** [comment]
Maybe I should pull out everything related to "locale" so you can specify in one place:

* Character encoding
* Time zone
* Decimal point vs. decimal comma
* Spelling of month/day names

**Comment by ijlyttle** [comment]
This sounds like the more-comprehensive approach.

I know this will only muddy the waters further, but you seem to be in the mode of "let's get it all out there", so here goes:

I have found that there can be two independent timezone contexts - the timezone expressed/implied in the file (let's call that `tz_file`), and the timezone I ultimately want to work with (let's call that `tz_local`).

Use case 1: The datetime in the file is: `2011-01-01 00:00:00` but written as Paris time. I want to send the dataframe to a function that expects UTC. In this case I would specify, `tz_file = "Europe/Paris"` and `tz_local = "UTC"`.

Use case 2: The datetime in the file is in ISO8601: `2014-03-05T00:15:00.000-0500`. Here, the parser will parse this into UTC (rightly) regardless of any directive for `tz_file`, but then I would want to specify `tz_local = "America/New_York"`.  

How much of this stuff "wants" to be a part of `readr` - I don't know. I get the sense that `readr` is concerned more with `tz_file`.

My current approach for `tz_local` is to use my own utility function that takes a dataframe and a timezone as args, then applies `lubridate::with_tz` to all the time columns. I would propose such a function, but it seems to occupy this weird space between lubridate, dplyr, and readr.

I'm happy to make other issues, PR's, or shut up as needed :)

**Comment by hadley** [comment]
Yeah, I think readr is just about `tz_file` - once you have it correclty parsed, changing the tz in R is trivial (and is just a cosmetic change).  I could default `tz_local` to "UTC". That would be somewhat analogous to always converting to utf-8, or always displaying dates as YYYY-MM-DD. (And UTC is safest to work with if you don't know anything about time zones)

**Comment by ijlyttle** [comment]
I'm probably restating a lot of what you just said - 

Explicitly specifying `tz_local` is out-of-scope for readr.

`tz_file` (or whatever it would be called in real-life) would default to UTC

There are a couple of design choices for implicitly specifying `tz_local`:

1. Return all times as UTC.
2. Return all times as `tz_file`

I like (2), as this might surprise the user less, and the default `tz_file = "UTC"` might split the difference here. Of course, this is strictly a matter of taste.

For the edge case of specifying `tz_file != "UTC"` and there being a column parsed using ISO8601, perhaps a warning could be thrown that `tz_file` is being ignored.

As for a way to deal with `tz_local` explicitly, maybe I'll go start some trouble at lubridate to see if `with_tz` could be made to accept dataframes as well as vectors.

**Comment by hadley** [comment]
I'm going to close this - it's not totally done, but the idea is there in the new `locale()` function.  I'll be thinking through the default tz behaviour as I think about dates and encodings.

**Comment by ijlyttle** [comment]
Thanks!

**Comment by ijlyttle** [comment]
Just a quick note to give 👏on the locale timezone behavior - especially with ISO8601 - it manages to capture the user's intent on the `tz` argument and figures out the right thing to do. Timezones are fraught with peril; this is an elegant way through. Excellent!
