### ISSUE TITLE
Omitting missing col_names when col_skip exists

### ISSUE THREAD

**Issue by SoccerGeek** [hadley/readr#233]
When passing col_names and skipping columns, there are checks on equal length vectors, but shouldn't col_names length be only length of non-skipped columns?

    inp <- "1,\"a\",2\n2,\"b\",3\n3,b,4"
    df <- read_csv(inp,  col_names=c('x','z'),col_types = "n_n")
    # works
    df <- read_csv(inp,  col_names=FALSE,
               col_types = list(col_integer(),
                                col_skip(),
                                col_integer())
    )
    #works
    df <- read_csv(inp,  col_names=c('x','z'),
               col_types = list(col_integer(),
                                col_skip(),
                                col_integer())
    )
    # Error: Unnamed columns must have the same length as col_names

The named col_types list also fails.  I would prefer to use this method so the skipped columns can have the names kept in synch.  Using the unnamed list is more error prone, but a work around.

    df <- read_csv(inp,  col_names=FALSE,skip=0,
               col_types = list(x=col_integer(),
                                y=col_skip(),
                                z=col_integer())
    )
    # Error: The following named parsers don't match the column names: x, y, z

**Comment by hadley** [comment]
The point of supply the names is so you can do (e.g):

```R
read_csv(... col_names = c("x", "y", "z"), col_types = list(y = col_skip())
```

I don't think it's possible to do and what you want.
