### ISSUE TITLE
cannot allocate victor size 6 GO

### ISSUE THREAD

**Issue by selmiyoussef** [hadley/readr#236]
hello i have this error: can not allocate victor size ..please any help consedering that i have 32 go of RAM , you find below the program and the issue of error and sessioninfo() thanks in advance for your help
# Program
T1=Sys.time()
#install.packages("reshape2") like require(reshape2)
#require(data.table)
#require(reshape2)
#install.packages("data.table")
#library(Rserve)
library(data.table)
library(reshape2)

table1 <- read.table("analyse/ppv-item/basecf.csv", sep=";", quote="\"",colClasses = c("numeric","numeric"), header=TRUE)

table1=as.data.table(table1)
#aggregation + binary matrix of table1
table2 <- dcast.data.table(table1, id_customer ~ product_id,value.var="product_id", fun.aggregate=length)

table2=as.data.frame(table2)

data.stat=table2

options(digits=4)

data.stat.ibs <- (data.stat[,!(names(data.stat) %in% c("id_customer"))])

data.stat.ibs.similarity  <- matrix(NA, nrow=ncol(data.stat.ibs),ncol=ncol(data.stat.ibs),dimnames=list(colnames(data.stat.ibs),colnames(data.stat.ibs)))

getCosine <- function(x){
  as.matrix(t(x[,c(1:ncol(x))])%*%x[,c(1:ncol(x))]/(sqrt(colSums(x^2) %*% t(colSums(x^2)))))
}

data.stat.ibs.similarity<-getCosine(as.matrix(data.stat.ibs))

hello i have this error :cannot allocate.. consedering that i have 32 GO of RAM

data.stat.ibs.similarity <- as.data.frame(data.stat.ibs.similarity)

data.stat.neighbours <- matrix(NA, nrow=ncol(data.stat.ibs.similarity),ncol =11,dimnames=list(colnames(data.stat.ibs.similarity)))

for(i in 1:ncol(data.stat.ibs)) 
{
  data.stat.neighbours[i,] <- (t(head(n=11,rownames(data.stat.ibs.similarity[order(data.stat.ibs.similarity[,i],decreasing=TRUE),][i]))))
}

data=data.stat.neighbours
data=data[,-1]
colnames(data)=c("best1","best2","best3","best4","best5","best6","best7","best8","best9","best10")

write.csv(data,file="analyse/ppv-item/export.csv",row.names=TRUE)

Sys.time()-T1

#error:
> data.stat.ibs.similarity<-getCosine(as.matrix(data.stat.ibs))
Erreur : impossible d'allouer un vecteur de taille 6.3 Go
Called from: as.matrix(t(x[, c(1:ncol(x))]) %*% x[, c(1:ncol(x))]/(sqrt(colSums(x^2) %*% 
    t(colSums(x^2)))))
R version 3.2.0 (2015-04-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 7 (wheezy)

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8     LC_MONETARY=fr_FR.UTF-8   
 [6] LC_MESSAGES=fr_FR.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] odfWeave_0.8.4   XML_3.98-1.3     lattice_0.20-31  dplyr_0.4.1      magrittr_1.5     reshape2_1.4.1   data.table_1.9.4

**Comment by hadley** [comment]
This doesn't appear to be a readr issue

**Comment by selmiyoussef** [comment]
ok thank you very much for your help
