### ISSUE TITLE
Compile error on gcc 4.9

### ISSUE THREAD

**Issue by nerdcha** [hadley/readr#240]
Thanks very much for this package!

Unfortunately the latest master isn't building for us. We're using gcc 4.9.3 (Debian 4.9.3-1) and getting a compile error at [read.cpp line 165](https://github.com/hadley/readr/blob/master/src/read.cpp#l165). 

Some details from the log:

    g++ -I/usr/share/R/include -DNDEBUG   -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/usr/local/lib/R/site-library/BH/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c read.cpp -o read.o
    In file included from /usr/include/c++/4.9/tr1/unordered_map:35:0,
                     from /usr/local/lib/R/site-library/Rcpp/include/Rcpp/platform/compiler.h:172,
                     from /usr/local/lib/R/site-library/Rcpp/include/Rcpp/r/headers.h:48,
                     from /usr/local/lib/R/site-library/Rcpp/include/RcppCommon.h:29,
                     from /usr/local/lib/R/site-library/Rcpp/include/Rcpp.h:27,
                     from read.cpp:1:
    /usr/include/c++/4.9/bits/stl_algobase.h: In instantiation of ‘typename __gnu_cxx::__enable_if<(! std::__is_scalar<_Tp>::__value), void>::__type std::__fill_a(_ForwardIterator, _ForwardIterator, const _Tp&) [with _ForwardIterator = CollectorCharacter*; _Tp = CollectorCharacter; typename __gnu_cxx::__enable_if<(! std::__is_scalar<_Tp>::__value), void>::__type = void]’:
    /usr/include/c++/4.9/bits/stl_algobase.h:740:14:   required from ‘void std::fill(_ForwardIterator, _ForwardIterator, const _Tp&) [with _ForwardIterator = CollectorCharacter*; _Tp = CollectorCharacter]’
    /usr/include/c++/4.9/bits/vector.tcc:470:16:   required from ‘void std::vector<_Tp, _Alloc>::_M_fill_insert(std::vector<_Tp, _Alloc>::iterator, std::vector<_Tp, _Alloc>::size_type, const value_type&) [with _Tp = CollectorCharacter; _Alloc = std::allocator<CollectorCharacter>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<CollectorCharacter*, std::vector<CollectorCharacter> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = CollectorCharacter*; std::vector<_Tp, _Alloc>::size_type = long unsigned int; std::vector<_Tp, _Alloc>::value_type = CollectorCharacter]’
    /usr/include/c++/4.9/bits/stl_vector.h:1073:44:   required from ‘void std::vector<_Tp, _Alloc>::insert(std::vector<_Tp, _Alloc>::iterator, std::vector<_Tp, _Alloc>::size_type, const value_type&) [with _Tp = CollectorCharacter; _Alloc = std::allocator<CollectorCharacter>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<CollectorCharacter*, std::vector<CollectorCharacter> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = CollectorCharacter*; std::vector<_Tp, _Alloc>::size_type = long unsigned int; std::vector<_Tp, _Alloc>::value_type = CollectorCharacter]’
    /usr/include/c++/4.9/bits/stl_vector.h:716:42:   required from ‘void std::vector<_Tp, _Alloc>::resize(std::vector<_Tp, _Alloc>::size_type, std::vector<_Tp, _Alloc>::value_type) [with _Tp = CollectorCharacter; _Alloc = std::allocator<CollectorCharacter>; std::vector<_Tp, _Alloc>::size_type = long unsigned int; std::vector<_Tp, _Alloc>::value_type = CollectorCharacter]’
    read.cpp:165:36:   required from here
    /usr/include/c++/4.9/bits/stl_algobase.h:693:11: error: no match for ‘operator=’ (operand types are ‘CollectorCharacter’ and ‘const CollectorCharacter’)
      *__first = __value;
               ^
    /usr/include/c++/4.9/bits/stl_algobase.h:693:11: note: candidate is:
    In file included from read.cpp:8:0:
    CollectorCharacter.h:7:7: note: CollectorCharacter& CollectorCharacter::operator=(CollectorCharacter&)
     class CollectorCharacter : public Collector {
           ^
    CollectorCharacter.h:7:7: note:   no known conversion for argument 1 from ‘const CollectorCharacter’ to ‘CollectorCharacter&’

**Comment by blaquans** [comment]
I also have compiling error : 

<pre>
g++ -I/usr/share/R/include -DNDEBUG   -I"/home/debian/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/home/debian/R/x86_64-pc-linux-gnu-library/3.2/BH/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c read.cpp -o read.o
In file included from /usr/include/c++/4.9/tr1/unordered_map:35:0,
                 from /home/debian/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/platform/compiler.h:172,
                 from /home/debian/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/r/headers.h:48,
                 from /home/debian/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/RcppCommon.h:29,
                 from /home/debian/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp.h:27,
                 from read.cpp:1:
/usr/include/c++/4.9/bits/stl_algobase.h: In instantiation of ‘typename __gnu_cxx::__enable_if<(! std::__is_scalar<_Tp>::__value), void>::__type std::__fill_a(_ForwardIterator, _ForwardIterator, const _Tp&) [with _ForwardIterator = CollectorCharacter*; _Tp = CollectorCharacter; typename __gnu_cxx::__enable_if<(! std::__is_scalar<_Tp>::__value), void>::__type = void]’:
/usr/include/c++/4.9/bits/stl_algobase.h:740:14:   required from ‘void std::fill(_ForwardIterator, _ForwardIterator, const _Tp&) [with _ForwardIterator = CollectorCharacter*; _Tp = CollectorCharacter]’
/usr/include/c++/4.9/bits/vector.tcc:470:16:   required from ‘void std::vector<_Tp, _Alloc>::_M_fill_insert(std::vector<_Tp, _Alloc>::iterator, std::vector<_Tp, _Alloc>::size_type, const value_type&) [with _Tp = CollectorCharacter; _Alloc = std::allocator<CollectorCharacter>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<CollectorCharacter*, std::vector<CollectorCharacter> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = CollectorCharacter*; std::vector<_Tp, _Alloc>::size_type = long unsigned int; std::vector<_Tp, _Alloc>::value_type = CollectorCharacter]’
/usr/include/c++/4.9/bits/stl_vector.h:1073:44:   required from ‘void std::vector<_Tp, _Alloc>::insert(std::vector<_Tp, _Alloc>::iterator, std::vector<_Tp, _Alloc>::size_type, const value_type&) [with _Tp = CollectorCharacter; _Alloc = std::allocator<CollectorCharacter>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<CollectorCharacter*, std::vector<CollectorCharacter> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = CollectorCharacter*; std::vector<_Tp, _Alloc>::size_type = long unsigned int; std::vector<_Tp, _Alloc>::value_type = CollectorCharacter]’
/usr/include/c++/4.9/bits/stl_vector.h:716:42:   required from ‘void std::vector<_Tp, _Alloc>::resize(std::vector<_Tp, _Alloc>::size_type, std::vector<_Tp, _Alloc>::value_type) [with _Tp = CollectorCharacter; _Alloc = std::allocator<CollectorCharacter>; std::vector<_Tp, _Alloc>::size_type = long unsigned int; std::vector<_Tp, _Alloc>::value_type = CollectorCharacter]’
read.cpp:181:36:   required from here
/usr/include/c++/4.9/bits/stl_algobase.h:693:11: error: no match for ‘operator=’ (operand types are ‘CollectorCharacter’ and ‘const CollectorCharacter’)
  *__first = __value;
           ^
/usr/include/c++/4.9/bits/stl_algobase.h:693:11: note: candidate is:
In file included from read.cpp:8:0:
CollectorCharacter.h:7:7: note: CollectorCharacter& CollectorCharacter::operator=(CollectorCharacter&)
 class CollectorCharacter : public Collector {
       ^
CollectorCharacter.h:7:7: note:   no known conversion for argument 1 from ‘const CollectorCharacter’ to ‘CollectorCharacter&’
/usr/lib/R/etc/Makeconf:143: recipe for target 'read.o' failed
make: *** [read.o] Error 1
ERROR: compilation failed for package ‘readr’
</pre>

**Comment by hadley** [comment]
Fixed now :)

**Comment by nerdcha** [comment]
:+1:  Thanks very much!
