### ISSUE TITLE
Up type to numeric when including overflowing integers

### ISSUE THREAD

**Issue by Ironholds** [hadley/readr#253]
If I read in a field of non-floating-point numbers, readr correctly classifies it as "integer" and treats it accordingly - the problem with this is that if an integer value is greater than 2^31-1 or whatever it produces an NA and complains in problems(...).

What if, when the problem is that a number is too large, readr simply converted the column type to numeric? (I appreciate that this may be non-trivial)

**Comment by hadley** [comment]
Can you provide a reprex please? (automatic up typing is very unlikely to happen)

**Comment by kevinushey** [comment]
It looks like automatic up-casting does happen in the development version, though:

```
> str(readr::read_delim("a\tb\n1\t2\n3\t4\n", delim = "\t"))
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':       2 obs. of  2 variables:
 $ a: int  1 3
 $ b: int  2 4
 - attr(*, "problems")=Classes ‘tbl_df’ and 'data.frame':       0 obs. of  4 variables:
  ..$ row     : int
  ..$ col     : chr
  ..$ expected: chr
  ..$ actual  : chr

> str(readr::read_delim("a\tb\n1\t2\n3\t400000000000000000000000\n", delim = "\t"))
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':       2 obs. of  2 variables:
 $ a: int  1 3
 $ b: num  2e+00 4e+23
 - attr(*, "problems")=Classes ‘tbl_df’ and 'data.frame':       0 obs. of  4 variables:
  ..$ row     : int
  ..$ col     : chr
  ..$ expected: chr
  ..$ actual  : chr
```

**Comment by hadley** [comment]
Yeah, readr looks at the first 1000 rows to infer types

**Comment by Ironholds** [comment]
Makes sense, because the cost of dumping that and going over isn't tremendously high at that point - which it would be if up-typing could happen literally anywhere in the file processing. On that basis I imagine yeah, it's unlikely to be resolved (and those of us who pay close attention to performance thank you for that :D)
