### ISSUE TITLE
read_delim ignores malformed field

### ISSUE THREAD

**Issue by kevinushey** [hadley/readr#255]
```r
> readr::read_delim("foo\tbar\n1\t2\n3\t4*5\n", delim = "\t")
  foo bar
1   1   2
2   3   4
```

It seems to me that the second column should be interpreted instead as character, or some kind of warning should be issued.

For what it's worth, it seems like some thresholding comes into play as this works:

```r
> readr::read_delim("foo\tbar\n1\t2\n3\t4*51152\n", delim = "\t")
  foo     bar
1   1       2
2   3 4*51152
```

**Comment by hadley** [comment]
More minimal reprex:

```R
readr::read_tsv("foo\tbar\n1\t2\n3\t4*5\n")
```

Even more minimal

```
collectorGuess("4*5", default_locale())
```

the problem is that this triggers the number collector. I think I can make it stricter by ensuring that the same number of characters is skipped for all strings.
