### ISSUE TITLE
Warning message "In col_euro_double() : Deprecated: please set local" generated when using concise `col_type`

### ISSUE THREAD

**Issue by dewittpe** [hadley/readr#257]
The warning message that `col_euro_double()` has been deprecated is returned to the user when using the concise `col_type` in `read_`.  Example:

    read_csv("x,y,z\n1,1,2\n3,4,5", col_type = "iid")
    ##   x y z
    ## 1 1 1 2
    ## 2 3 4 5
    ## Warning message:
    ## In col_euro_double() : Deprecated: please set locale

**Comment by dewittpe** [comment]
Added a check for `e` in the `col_type` within `col_types_concise(col_types, guessed_types)`.

Will send pull request.

    read_csv("x,y,z\n1,1,2\n3,4,5", col_type = "iid")
    ##   x y z
    ## 1 1 1 2
    ## 2 3 4 5

    read_csv("x,y,z\n1,1,2\n3,4,5", col_type = "iie")
    ##   x y z
    ## 1 1 1 2
    ## 2 3 4 5
    ## Warning message:
    ## In col_types_concise(col_types, guessed_types) : 
    ##   col_euro_double() has been deprecated.  Please set locale.  ##   Substituting `d` for `e`.

**Comment by jennybc** [comment]
I get this message too.
