### ISSUE TITLE
Horrible CSV: Can readr deal with the full spectrum of horrible files?

### ISSUE THREAD

**Issue by dbuijs** [hadley/readr#262]
Originally posted as a comment to https://github.com/hadley/readr/issues/94. Opened new issue as requested. 

Fantastic package! Please excuse if this is out of scope, but there are all sorts of horrible source CSV that I find myself having to deal with by pre-processing outside of R with something like Perl. Totally ok if you think that's still probably the best way to do this.

The way you've got this package set up however, makes me think that perhaps other forms of CSV lunacy could be dealt with by simply writing a new tokenizer.

The specific things that I have trouble dealing with entirely within R include:

1. Mismatched encoding/locale, usually something that has been declared explicitly or implicitly as UTF-8 but is actually ISO-8859-1, which has consequences for interpreting newlines and EOF. (There are R solutions for this, including the excellent `rvest` package, but this really needs to be dealt with right at the file level before throwing it at a parser.)

2. Embedded but unescaped newlines.

3. Embedded but unescaped delimiters.

4. Embedded but unescaped quotes.

5. Undeclared/inconsistent padding whitespace (Pretty sure `readr` can handle this already, but included in the list for completeness)

If you've already got or are working on auto-detect/guessing for the number of fields, the delimiter, the quote character and the newline code, you can potentially fix all of these annoying issues (with or without fanfare, as the case may be).

On a high level, you would add a check (probably just for string or unknown col types) for the number of fields in the current line and if it doesn't match what was auto-detected or declared in the call, jump to a special tokenizer for that line and any subsequent lines until you get a single parsed record that makes sense, then jump back to your standard tokenizer. Optionally, you spit out a warning (or error) for the line(s) and the problem.

If the file is so messy that it can't even get past auto-detect, then you exit and throw an error that the file isn't valid CSV (or delimited) of any flavour, and this is also useful information.

Are my assumptions here about how readr works and/or is planned reasonable?

**Comment by hadley** [comment]
1 and 5 are already solved in the dev version. 

I think your strategy for dealing with 2-4 is a bit simplistic. How are you supposed to figure out what's a real quote/newline and what's a quote/newline that the user forgot to escape? How do know a "single parsed record that makes sense" isn't just the combination of two or more errors?

**Comment by hadley** [comment]
I'd be willing to think about this idea, but you need to provide a couple of worked examples.

**Comment by dbuijs** [comment]
No problem. Let me think about it a bit more. 

I can feel that there is a solution in there, having to do with the assumption that the data is rectangular and we know how many fields there are. 

Is my assumption about how `readr` works internally valid? Do we need a test for a valid row, followed by a special tokenizer that does its thing and returns a valid row?

**Comment by hadley** [comment]
I wouldn't worry about how stringi works internally at this point.
