### ISSUE TITLE
parse_integer() and col_integer() are unable to handle commas

### ISSUE THREAD

**Issue by lazarillo** [hadley/readr#265]
Perhaps this is how it is meant to work, but here is the behavior I find:
`R.version`:

`platform       x86_64-apple-darwin13.4.0`
`version.string R version 3.2.2 (2015-08-14)`

    > parse_integer("1,000")
    [1] 1
    attr(,"problems")
    Source: local data frame [1 x 4]

        row   col               expected actual
      (int) (int)                  (chr)  (chr)
    1     1    NA no trailing characters   ,000
    Warning message:
    1 problems parsing input. See problems(...) for more details. 

Whereas,

    > parse_numeric("1,000")
    [1] 1000

I noticed the same behavior with `col_integer()`  I presume it is calling the same functions under the hood, I did not dig deep enough.

    > read_csv("this\nis\na\ntest\n4\n4,000.", col_types = list(col_integer()))
    Source: local data frame [5 x 1]

       this
      (int)
    1    NA
    2    NA
    3    NA
    4     4
    5     4
    Warning message:
    4 problems parsing literal data. See problems(...) for more details. 

None of this is show-stopping, since I can just use `col_numeric()` for everything instead of `col_integer()` when appropriate.

Also, I'm happy to fork the repo & fix it by mirroring how you handled `col_numeric()`, if that sounds good.

-----

I was playing around with the euro one, to see if it had "opposite" problems.  I did not dig particularly deep, but I noticed the following here, too:

    > parse_euro_double("3.350")
    [1] NA
    attr(,"problems")
    Source: local data frame [1 x 4]

        row   col expected actual
      (int) (int)    (chr)  (chr)
    1     1    NA a double  3.350
    Warning message:
    1 problems parsing input. See problems(...) for more details. 

Hopefully a European can chime in here to validate (or maybe New Zealand works similarly), but when I've worked with European data, the dot [.] is used as a "thousands" (millions, etc.) placeholder.  So I think that 3.350 should be three thousand three hundred fifty.

**Comment by hadley** [comment]
If you want to ignore the grouping mark, you should use `parse_number` (make sure you have dev version)

**Comment by michielb77** [comment]
And at the risk of stating the obvious: you can use col_number to work with read_csv().
