### ISSUE TITLE
Leading zeroes

### ISSUE THREAD

**Issue by jennybc** [hadley/readr#266]
I wonder if leading zeroes should cause a column to come in as character? I know I can force the variable to be character and will do so in my current example.

But I suspect that numbers with leading zeroes should be treated as character more often than not. Examples: social security numbers, zip codes, phone numbers with country exit codes, numbers written written for alphalexical sorting, and agent identifiers in the 00 Section of MI6.

**Comment by hadley** [comment]
Seems reasonable to me

**Comment by hadley** [comment]
Hmmm, this is easy enough to do for integers, but what's the rule for doubles? Should `001.1234` be parsed as a double? What about `0.1`?  Is the rule that if there's an initial zero, it must be followed by a period?

**Comment by jennybc** [comment]
I think if it just worked for integers that would still be really nice. All my real-life examples are umambiguously integer (last x digits of student IDs, player numbers such as `00` or `06`, etc.).

**Comment by hadley** [comment]
You have to think about doubles because `00001` is both an integer and a double, so if I fix it so readr doesn't think it's an integer, it'll just get detected as a double, which isn't a big improvement.

**Comment by hadley** [comment]
This is what I have so far

``` r
collector_guess("0")
#> [1] "integer"
collector_guess("0.")
#> [1] "double"
collector_guess("0001")
#> [1] "character"
```
