### ISSUE TITLE
Guesser very assertive about numeric

### ISSUE THREAD

**Issue by jennybc** [hadley/readr#271]
I keep getting surprised by variables I think of as factor or character coming in as numeric, if I don't explicitly specify column types.

``` r
library(readr)

## what I'm expecting
hwdat <- frame_data(
  ~hw, ~course,
  "hw01", "STAT545",
  "hw13", "STAT547"
)
hwdat
#> Source: local data frame [2 x 2]
#> 
#>      hw  course
#>   (chr)   (chr)
#> 1  hw01 STAT545
#> 2  hw13 STAT547

## real life = repeated surprise
writeLines(c("hw,course", "hw01,STAT545", "hw13,STAT547"), "hwdat.txt")
hwdat2 <- read_csv("hwdat.txt")
hwdat2
#> Source: local data frame [2 x 2]
#> 
#>      hw course
#>   (dbl)  (dbl)
#> 1     1    545
#> 2    13    547
```

I see in the tests that you want something like `"USD 1,300"` to come in as numeric. I just wonder if this behavior is going to surprise alot of other people? I'm accumulating quite a lot of this: `read_csv(..., col_types = "???c??????c???")`. Feel free to close this.

PS Do you want `frame_data()` to produce the same as `read_csv()` in the case above?

**Comment by jennybc** [comment]
Ironically, at the moment it's easier to bring the homework identifiers in as character if I remove the leading `hw`:

``` r
writeLines(c("hw,course", "01,STAT545", "13,STAT547"), "hwdat.txt")
hwdat3 <- read_csv("hwdat.txt")
hwdat3
#> Source: local data frame [2 x 2]
#> 
#>      hw course
#>   (chr)  (dbl)
#> 1    01    545
#> 2    13    547
```

**Comment by hadley** [comment]
Yeah, I'm having second thoughts about this too. The heuristic is already about as complicated as I want to make it, and I still keep finding exceptions. I think I'll make much stricter (i.e. so it doesn't guess for currencies or percentages any more, but does still work for (`1,000,000.00`) - it's not like it's hard to opt in (especially now that you can do col_types = cols(x = "n")`)

**Comment by hadley** [comment]
FWIW you can simplify that example a bit to:

```R
read_csv("
  hw,course
  hw01,STAT545
  hw13,STAT547
", skip = 1)
```

**Comment by jennybc** [comment]
Ooh glad to learn about THIS: `col_types = cols(x = "n")`.
