### ISSUE TITLE
Changed behaviour for col_names when skipping columns

### ISSUE THREAD

**Issue by hmalmedal** [hadley/readr#274]
In the CRAN version it is OK to only specify the names of the columns you want to keep. In the development version you have to specify the names of all columns. Is this change intentional?

CRAN version:

``` r
library(readr)
read_csv("1,2,3\n4,5,6", col_names = c("a", "b"), col_types = "i_i")
```

    ##   a b
    ## 1 1 3
    ## 2 4 6

Development version:

``` r
library(readr)
read_csv("1,2,3\n4,5,6", col_names = c("a", "b"), col_types = "i_i")
```

    ## Warning: Unnamed `col_types` should have the same length as `col_names`.
    ## Using smaller of the two.

    ## Warning: 1 parsing failure.
    ## row col    expected      actual
    ##  --  -- 3 col names 2 col names

    ##   a X3
    ## 1 1  3
    ## 2 4  6

``` r
read_csv("1,2,3\n4,5,6", col_names = c("a", "x", "b"), col_types = "i_i")
```

    ##   a b
    ## 1 1 3
    ## 2 4 6

**Comment by hadley** [comment]
Doh, knew I missed something.

**Comment by hadley** [comment]
Hmmmm, I think this is intentional because it makes this consistent:

```R
read_csv("1,2,3\n4,5,6", col_names = c("a", "c"), col_types = "i_i")
read_csv("a,b,c\n1,2,3\n4,5,6", col_types = "i_i")
```

But maybe I need to special case guessed vs. supplied column names.

**Comment by hadley** [comment]
Pretty sure I've now captured all the variations.
