### ISSUE TITLE
read_tsv, read_delim : comment = "#"

### ISSUE THREAD

**Issue by thierrygosselin** [hadley/readr#278]
Not sure if it's an issue with argument 'comment'  but in the example below, I'm not able to skip or ignore the lines that starts with a comment "#"

 "test.tsv":

```r
##fileformat=VCFv4.0
##fileDate=20150913
##source="Stacks v1.34"
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of Samples With Data">
##INFO=<ID=AF,Number=.,Type=Float,Description="Allele Frequency">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=AD,Number=1,Type=Integer,Description="Allele Depth">
##FORMAT=<ID=GL,Number=.,Type=Float,Description="Genotype Likelihood">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	EST-BUR-ADU-2013-003	EST-BUR-ADU-2013-004
un	14	1	T	G	.	PASS	NS=277;AF=0.957,0.043	GT:DP:AD:GL	0/0:10:10,0:.,13.86,.	0/0:17:17,0:.,23.57,.
un	22	1	G	A	.	PASS	NS=239;AF=0.603,0.397	GT:DP:AD:GL	./.:10:.,.:.,.,.	./.:17:.,.:.,.,.
```

Usually, I just skipped the first 9 lines, but some vcf files have more header lines and the 'comment = "#" ' argument was a welcomed addition to read_delim or read_tsv().

trying this doesn't work:

```r
vcf <- read_delim(
  "test.tsv",
  delim = "\t",
  comment = "#",
  col_names = TRUE,
  progress = interactive()
) 
```
Thierry

**Comment by hadley** [comment]
Hmmm, I didn't think through how leading comments interact with `skip`. I'll take another stab it at early next week (or later today, if I get time).  Here's a test case to get started:

```R
test_that("leading comments are ignored", {
  out <- read_csv("#a\n#b\nx\n1", comment = "#")

  expect_equal(dim(out), c(1, 1))
  expect_equal(out$x, 1L)
})
```

Probably also need pass comment down to source, and modify `skipLines()` to understand comments.
