### ISSUE TITLE
log tokenizer broke unexpectedly

### ISSUE THREAD

**Issue by Ironholds** [hadley/readr#279]
The `webreadr` example datasets haven't changed since the initial release (and the introduction of the log tokeniser). Using them now, however:

    library(webreadr)
    file <-  system.file("extdata/log.clf", package = "webreadr")
    read_clf(file)

    Warning: 17 parsing failures.
    row        col  expected        actual
    1 NA         7 columns 1 columns    
    1 NA         7 columns 1 columns    
    1 ip_address           embedded null
    1 NA         7 columns 1 columns    
    1 ip_address           embedded null
    ... .......... ......... .............
    .See problems(...) for more details.
    ip_address remote_user_ident local_user_ident timestamp request status_code bytes_sent
    1       3401              2326             <NA>      <NA>    <NA>          NA         NA

For some reason it's only recognising the last column.

**Comment by hadley** [comment]
Oops, that was a dumb mistake

**Comment by Ironholds** [comment]
I've made many of them. Cool; I'll try and run webreadr against the new version this afternoon and hopefully it'll be resolved!
