### ISSUE TITLE
use custom allocators

### ISSUE THREAD

**Issue by romainfrancois** [hadley/readr#28]
Suppose we have a binary file of some sort where each vector of the data frame are contiguous. I'm pretty sure we could leverage R custom allocators (https://github.com/wch/r-source/commit/ebf11b0f86d1bc28d5add438eed42f8ada252ebf)

```
/* R_allocator_t typedef is also declared in Rinternals.h 
   so we guard against random inclusion order */
#ifndef R_ALLOCATOR_TYPE
#define R_ALLOCATOR_TYPE
typedef struct R_allocator R_allocator_t;
#endif

typedef void *(*custom_alloc_t)(R_allocator_t *allocator, size_t);
typedef void  (*custom_free_t)(R_allocator_t *allocator, void *);

struct R_allocator {
    custom_alloc_t mem_alloc; /* malloc equivalent */
    custom_free_t  mem_free;  /* free equivalent */
    void *res;                /* reserved (maybe for copy) - must be NULL */
    void *data;               /* custom data for the allocator implementation */
};
```

So we would need to come up with a `custom_alloc_t` function that would return the appropriate location in the binary mmaped file rather than allocate. 

Perhaps we can maintain a count of the vectors that are coming from this mmaped file and then unmap when `mem_free` is used on the last of them. 

@s-u does that sound like a potential use case for this feature ? It seems that with this we could load data pretty instantly (just a bit more than cost of mmap I guess).

**Comment by hadley** [comment]
@romainfrancois I've just pushed a big update that I think obviates the need for this. The parser now makes very very few copies.
