### ISSUE TITLE
write_csv sigfigs

### ISSUE THREAD

**Issue by pinkplatypus** [hadley/readr#281]
Hi Hadley,

Is it possible to specify the number of significant figures that write_csv writes?

Currently, it only writes to 6 significant figures, but my use cases require 8.  My workarounds have been to use write.csv, which supports up to 8 significant figures for numerics, or to first convert to the field to a character, then write_csv, which is faster.

**Comment by hadley** [comment]
It does the same thing as as.character. I'm pretty sure that's more like 17 digits, so a reprex would be helpful.

**Comment by pinkplatypus** [comment]
data.frame(data = c(1, 12, 123, 1234, 12345, 123456, 1234567, 12345678, 123456789)) %>% write_csv("test.csv")

1234567 is represented as 1.23457 e1

data.frame(data = c(1, 12, 123, 1234, 12345, 123456, 1234567, 12345678, 123456789)) %>% write.csv("test.csv")
1234567 is fully represented as 1234567.

**Comment by hadley** [comment]
Looks ok to me, so must be fixed in dev:

``` r
cat(write_csv(data.frame(x = c(1, 12, 123, 1234, 12345, 123456, 
    1234567, 12345678, 123456789)), ""))
#> x
#> 1
#> 12
#> 123
#> 1234
#> 12345
#> 123456
#> 1234567
#> 12345678
#> 123456789
```
