### ISSUE TITLE
read_csv: Set collector for column with first 100 rows blank as character collector

### ISSUE THREAD

**Issue by pinkplatypus** [hadley/readr#282]
Hi Hadley,

Is it possible to either (1) create an option to set all column collectors as character collectors or (2) when imputing 100 blank rows, set the collector as a character collector instead of a logical collector?

Often times my data has the first 100 rows blank; there are also too many columns for me to set each column type manually, so I use the default column collection imputer. What I found is that with 100 blank rows, read_csv interprets these as NA, a logical, and thus uses the logical collector. However, the actual data (characters) are not logicals and are coerced into NAs because they're not TRUE or FALSE. Thus, the entire column is read in as NAs, which may not be a bug but is an insidious effect that's not immediately obvious because suddenly a column of expected data of unknown type is read in as a blank column.

Thus, can you either make it such that it is easy to set all column collectors as character collectors, or edit the imputer such that 100 blank rows triggers the character collector and not the logical collector?

My current workaround has been to first read in 0 rows, count the number of columns, and read in all the data with col_types = str_dup("c", [number of columns]).

Thanks!

**Comment by hadley** [comment]
Try the dev version
