### ISSUE TITLE
consider decimal_mark for write_delim()?

### ISSUE THREAD

**Issue by ijlyttle** [hadley/readr#284]
Would you consider adding support for specifying the decimal mark for the write_delim() family of functions?

Does this beg the use of `locale()`?

Is there something in `output_column()` I should currently use?

Thanks for accepting barrage of questions!

**Comment by hadley** [comment]
Hmmmm. Is there a compelling reason? I'd prefer to stick to postel's law as much as possible.

**Comment by ijlyttle** [comment]
I'm thinking about the European usage of the comma as the decimal mark. (I'll know in a week or so if it's compelling)

No problem to use write.table for this case - I just prefer to use readr wherever I can.

**Comment by ijlyttle** [comment]
I'm closing this because my use case involves making an Excel-friendly CSV for Europeans. The comma remains compelling, but it Excel does not like 8601 - so there would have to be even more of abuse of Postel's law.

For me, for this case, I'm OK using write.table.

**Comment by tklebel** [comment]
I'd prefer to use `readr` too. Currently I am using `write.csv2` to create csv-files which are being imported to Excel with a european locale. I'd prefer to be able to write something like this:

```R
write_delim(x, "file", delim = ";", decimal = ",")
```

@ijlyttle To what are you referring with "8601"?

**Comment by ijlyttle** [comment]
@tklebel 8601 refers to time formatting: https://en.wikipedia.org/wiki/ISO_8601

**Comment by hadley** [comment]
@tklebel can you confirm that Excel in a European locale can not read standard csv files?

**Comment by tklebel** [comment]
It can read them. Although it takes one more step, specifying the decimal mark in an extra menu, which is not obvious at first glance. I wasn't aware of that possibility, just found it after some digging. :/

In that case, there is probably no need to add such a parameter to `readr`. I will just tell my coworker to use Excel properly.

**Comment by cbrnr** [comment]
Although it is certainly possible to read CSV files with decimal marks different from the current locale into Excel, my experience shows that many people have a hard time with such files. If `write_delim` had a `locale` argument (similar to `read_delim`, where you can just set this to e.g. `locale=locale(decimal_mark=",")` in combination with e.g. `delim=";"`), things would be a lot easier for many people.
