### ISSUE TITLE
read_csv2 can't handle custom col_types

### ISSUE THREAD

**Issue by zelite** [hadley/readr#286]
When trying to specify col_types for a european style CSV file, the read_csv2 function gets in trouble. It seems it forgets how to handle the commas.

    my_csv <- "A;B\n0,04;0,05"
    
    read_csv2(my_csv)
    ## Source: local data frame [1 x 2]
    ## 
    ##       A     B
    ##   (dbl) (dbl)
    ## 1  0.04  0.05
    
    
    read_csv2(my_csv, col_types = "dd")
    ## Source: local data frame [1 x 2]
    ## 
    ##       A     B
    ##   (dbl) (dbl)
    ## 1     0     0
    
    Warning message:
    2 problems parsing literal data. See problems(...) for more details.

The problems on the dataframe are the following:

    Source: local data frame [2 x 4]
    
        row   col               expected actual
      (int) (int)                  (chr)  (chr)
    1     1     1 no trailing characters    ,04
    2     1     2 no trailing characters    ,05

**Comment by hadley** [comment]
Already fixed in dev version.
