### ISSUE TITLE
parse_date & col_date treat NA as Invalid token

### ISSUE THREAD

**Issue by shrektan** [hadley/readr#287]
Firstly, I really love this package.

However, in the dev version, the `parse_date` will treat `NA` as Invalide token (so is `col_date`)

Here's an example:

```r
readr::parse_date(NA_character_)
```

I've tried it on both my Mac and PC.

PS: Tried to figure out the reason from the source code, but I think the way that you building this package is kind of beyond my ability...

**Comment by shrektan** [comment]
hahahahah, what a funny thing! I just located the bug by searching `Invalid Token` and found you missed type `return` in `CollectorDate`. And I think, wow, I can make a PR for @hadley... But I just fork the git, downloaded in my rstudio, opened the `Collector.cpp`, but found the missing `return` has been added 33 seconds ago... 

Oops.

**Comment by hadley** [comment]
Haha, sorry!
