### ISSUE TITLE
Help page for read_delim() doesn’t mention all compact string representations for column types

### ISSUE THREAD

**Issue by huftis** [hadley/readr#293]
The help page for `read_delim()` currently (`readr` version 0.1.1) says:

    Alternatively, you can use a compact string representation
    where each character represents one column:
    c = character, d = double, i = integer, l = logical and _ skips the column.

It looks like this is is a complete list of possible values. However, several other characters are supported (taken from `col_types.R` of the the current Git version):

    "_" = ,
    "-" = col_skip(),
    "?" = col_guess(),
    c = col_character(),
    D = col_date(),
    d = col_double(),
    e = col_euro_double(),
    i = col_integer(),
    l = col_logical(),
    n = col_number(),
    T = col_datetime(),
    t = col_time(),

**Comment by huftis** [comment]
Thanks for the fix, but it looks like you forgot ’e’, for numbers with comma as a decimal separator (which actually also works in the released version of dplyr, BTW). It’s also not very clear what’s the difference between number and double. (I guess intuitively, I would expect number to handle both numbers with decimal and period as separator.)

**Comment by hadley** [comment]
That is deprecated

**Comment by huftis** [comment]
> That is deprecated

What do you mean? Is ‘e’ deprecated? How is one supposed to read numbers where the decimal separator is a comma (i.e. CSV files from European version of MS Excel)?

**Comment by hadley** [comment]
See the README or NEWS or the locale vignette...

On Mon, Oct 19, 2015 at 1:19 PM, Karl Ove Hufthammer <
notifications@github.com> wrote:

> That is deprecated
>
> What do you mean? Is ‘e’ deprecated? How is one supposed to read numbers
> where the decimal separator is a comma (i.e. CSV files from European
> version of MS Excel)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hadley/readr/issues/293#issuecomment-149303310>.
>



-- 
http://had.co.nz/
