### ISSUE TITLE
corrupt data frame when using dplyr::bind_rows after updating readr form 0.1.1 to 0.2.2

### ISSUE THREAD

**Issue by M-E-Steiner** [hadley/readr#296]
I reccently asked this question:

http://stackoverflow.com/questions/33255646/error-corrupt-data-frame-when-using-dplyrbind-rows-after-updating-readr-form

It seems to be some kind of a bug. I updated `readr` from 0.2.0 to 0.2.2 this morning but the issue is still there. I don't know if it's caused by `readr`. If you need the original csv to reproduce the error, I am willing to send it to you privately.

Thanks

**Comment by hadley** [comment]
Can you please try to create a minimal reproducible example? The simpler you can make it the faster I can fix the problem.

**Comment by M-E-Steiner** [comment]
I think its best, if I sent you the data (2 csv files)  + the code, so you can reproduce using the exact same data. Would that be ok? Where should I sent it?

**Comment by hadley** [comment]
It would be best if you could recreate the problem without requiring the files. You can read inline data with (e.g.)

```R
read_csv("a,b,c
1,2,3")
```

**Comment by M-E-Steiner** [comment]
ok I'll try

**Comment by M-E-Steiner** [comment]
Ok,  while trying to reproduce the example without the data I think I found the reason for the error. One of my columns headers was `EMPTY` in the original file. Apparently `dplyr:: bind_rows()` doesnt - understandably - like column headers to be NA. If I remember correctly `read_csv2` in `readr` version `0.1.1` did not convert empty cells to `NA` but left them as is, so `bind_rows()` hat no reason to complain. Hence, this causes my error:

       dframe_1 <- data_frame("NA" = 1, 
                       "A" = 123, 
                       "B" = "Some text")

       dframe_2 <- data_frame("NA" = 1, 
                       "A" = 23, 
                       "B" = "Some text")


       data.list <- list(dframe_1, dframe_2)
       end.result <- bind_rows(df.list) # here i get: "Error: corrupt data frame"

While I think it is a good choice to automatically convert empty cells to NA when reading csv files, I feel there should be an exception for headers (or at least a warning, since in my case column 227 had no header, which is not easly spotted at first glance). Maybe empty headers should just get names like `X1`, `X2`, etc. (preferably combined with a warning).

**Comment by M-E-Steiner** [comment]
hmmm I am sorry this wasnt right... I had the variable in bind_rows().... i keep looking. However, while this does not reproduce the error, I think the NA in the header IS indeed causing my error since after deleting this column from my data set, the error was gone. I'll try to find another minimal example the works.

**Comment by M-E-Steiner** [comment]
**Follow-up:**

If the orginial .csv contains a column header that is EMPTY the `col_types` to `read_csv` argument causes an error. 

Here is a minimal reproducible example

    library(readr)
    library(dplyr)

    dpath <- getwd()

    # Generate data with 

    dframe_1 <- data_frame("A"  = "1.", 
                                           "B"  = "123", 
                                           "C"  = "Some text")
    colnames(dframe_1) <- c("", "B", "C")

    dframe_2 <- data_frame("A"  = "2.", 
                                           "B"  = "023", 
                                           "C"  = "Some text")
    colnames(dframe_2) <- c("", "B", "C")

    # Write to csv

    write_csv(dframe_1, "csv_1.csv")
    write_csv(dframe_2, "csv_2.csv")

    file.list <- list.files(dpath, pattern='*.csv')

    df.list1 <- file.list %>% 
        lapply(read_csv) # works correctly (still bind_rows causes an error)

    # Lets try to change some column type:

    df.list2 <- file.list %>% 
         lapply(read_csv, col_types = cols("B" = col_double()))
      Error: not compatible with STRSXP

I think this is even more reason add a warning or some appropriate way of dealing with those empty headers (maybe there is already a way I am just not aware of?)

**Comment by hsheikha1429** [comment]
I did receive the same error when I was combing couple of imported excel files (using bind_rows()) and seems there was some columns with NA name...(Column name was empty...cleaning the original excel file empty cells and run the combined again solved the problem)... I hope that the function bind_rows() has an addition/optional parameter setting that allow omitting the columns that had Empty names, line omit.NA.Col = True that will be good.   

Thanks to the awesome dplyr developer team, especially Hadely.

**Comment by hadley** [comment]
Empty headers now get a default column name:

``` r
read_csv(",b,c\n1,2,3")
#> Source: local data frame [1 x 3]
#> 
#>      X1     b     c
#>   <int> <int> <int>
#> 1     1     2     3
```
