### ISSUE TITLE
read_csv coerces character column to double, but no NA?

### ISSUE THREAD

**Issue by icj** [hadley/readr#299]
In readr 0.1.1, read_csv does the following:

``` r
# with readr 0.1.1
file <- "X1\n1\n2\n2X"
read_csv(file)

# Source: local data frame [3 x 1]
# 
#      X1
#   (chr)
# 1     1
# 2     2
# 3    2X
```

But in readr 0.2.2, read_csv does something unexpected:

``` r
# with readr 0.2.2
file <- "X1\n1\n2\n2X"
read_csv(file)

# Source: local data frame [3 x 1]
# 
#      X1
#   (dbl)
# 1     1
# 2     2
# 3     2
```
Seems like the 2X should have been NA if it thought it was a numeric column. Subbing it to 2 could be dangerous.

**Comment by hadley** [comment]
Hmmm, the numeric guesser is being too aggressive. I'll have another look at it.

**Comment by hadley** [comment]
Duplicate of #308
