### ISSUE TITLE
Speed vs LaF for pulling a few columns from a large file, FYI

### ISSUE THREAD

**Issue by donboyd5** [hadley/readr#301]
Hi,

Thank you for readr. It is almost always my goto tool for getting data from csv files. Recently I have had a need to pull selected columns from large csv files (the Census Bureau's American Community Survey for the U.S., 5-year data). I have compared readr to the package LaF (Large Ascii Files) and found LaF to be about 2-4 times as fast as readr for this purpose. This is not an issue or a problem, of course, but I thought I should let you know, in case you want to investigate what makes LaF faster for this purpose.

Here is a small reproducible example, once you download the Census file (url given below); it uses one of the 4 files that make up the 2013 5-year sample. On my machine, the LaF version reads the file in 53 seconds and the readr version reads it in 117 seconds.

Again, not a problem or issue, but enough of a difference for me to use LaF for this purpose. I would rather use readr for everything.

Many thanks.

Don

````
# comparison of readr and LaF - reading a few columns from a large file

# get the data ####
fnz <- "csv_pus.zip"
webdir <- "http://www2.census.gov/acs2013_5yr/pums/"

localdir <- "e:/temp/"

fna <- "ss13pusa.csv" # about 4.4gb, 4.6m rows, 295 columns - 1 of 4 files in zip archive

# uncomment this next line to download the data
# not tested because I did this manually
# download.file(paste0(webdir, fnz), paste0(localdir, fnz), mode="wb")
unzip(paste0(localdir, fnz), files=fna, exdir="e:/temp")

library("dplyr")
library("readr")
library("LaF")


# first, LaF ####
cnames <- names(read_csv(paste0(localdir, fna), n_max=1)) # get the column names using readr
cnames

dat.laf <- laf_open_csv(paste0(localdir, fna), column_names=cnames, column_types=rep("string", length(cnames)), skip=1)
keepvars <- c("serialno", "PUMA10", "ST", "ADJINC", "PWGTP", "AGEP", "WAGP", "HISP", "RAC1P", "SEX", "SCHL")
dat.laf[1:20, keepvars]
system.time(df.laf <- dat.laf[, keepvars])
glimpse(df.laf)


# now readr ####
system.time(df.rr <- read_csv(paste0(localdir, fna), col_names=TRUE, 
                col_types=cols_only(serialno="c", PUMA10="c", ST="c", ADJINC="c", PWGTP="c",
                                    AGEP="c", WAGP="c", HISP="c", RAC1P="c", SEX="c", SCHL="c")))
glimpse(df.rr)

````

**Comment by hadley** [comment]
Thanks - but I don't have time to explore performance issues in detail at this point.
