### ISSUE TITLE
Need write_file and write_lines

### ISSUE THREAD

**Issue by hadley** [hadley/readr#302]
To do reverse of `read_file()` and `read_lines()`  (should always write as utf-8)

**Comment by jennybc** [comment]
Could these return the path to the file they just wrote?

But I also see that would be inconsistent with `write_delim()` et al, which return the data frame they just wrote.

**Comment by hadley** [comment]
@jennybc I'm pretty confident now that the general principle is that if a function is called primarily for its side-effects, then it should invisibly return it's first argument.
