### ISSUE TITLE
col_types specifications different between read_excel and read_csv - vector vs. list/string

### ISSUE THREAD

**Issue by sfirke** [hadley/readr#304]
I use `read_excel` from readxl often and I was surprised that I couldn't use a vector for `col_types` when calling `read_csv` from readr.  The options of a list or a character string both seem more complex than a character vector, which would be consistent with `read_excel` as well as `read.csv` (and I think many users will come to `read_csv` when updating code from `read.csv` so this will be a common stumbling block).

I know readxl is a different package but is this different approach to `col_types` intentional / would you consider letting `read_csv` take a vector for `col_types`?

**Comment by jjcad** [comment]
+1 `read_*` should support option to specifyc `col_types` the same as `colClasses` in `read.table()`.

**Comment by hadley** [comment]
Part of #237
