### ISSUE TITLE
col_number() drops negatives

### ISSUE THREAD

**Issue by gregmacfarlane** [hadley/readr#308]
If I don't request specific column types, then `read_csv` treats negative numbers appropriately.

```r
readr::read_csv("A,B\n-4,5G")

##    A B
## 1 -4 5
```

If I specify that the column is numeric, then `read_csv` drops the negative signs.
```r
readr::read_csv("A,B\n-4,5G", col_types = "nn")

##   A B
## 1 4 5
```

**Comment by dyndna** [comment]
Specifying `col_types= "d"` will fix it, although I thought that `n` should be numeric and should not convert negative to positive values. 

@hadley: Thanks for detailed documentation which I did not read until I noticed `col_types` issue in my data set. Following helped me to understand col_types.

`?read_tsv` and ` vignette("column-types") `

**Comment by rkarimi** [comment]
Had the same problem, and was not sure what is the difference between n and d!

**Comment by ctmann** [comment]
This introduces a new problem; d converts a number with commas to NA, but at least it warns the user. To confirm, please try the code below using the data on the attached spreadsheet, importing it using three different techniques (base R, readr without explicitly decaring coltypes, and finally, using your solution)


```
unzip_folder <- "~/R/TestBed/"
file <- "testbed.csv"
filename <- paste0(unzip_folder,file)


read.csv(filename)


library(readr)
read_csv(filename)


read_csv(filename, col_types = cols(
  Name = "c",
  Amounts = "d"))
```


[testbed.zip](https://github.com/hadley/readr/files/196245/testbed.zip)

**Comment by hadley** [comment]
This issue actually illustrates two problems:

1. `parse_number("-1)` returns 1
1. `collector_guess("1G")` returns "number"

**Comment by ctmann** [comment]
Thank you for fixing this critical bug!

**Comment by jtr13** [comment]
col_number / parse_number doesn't work with negative currencies. (I'm using the dev version.) Thanks.

> parse_number("$3")
[1] 3
> parse_number("-$3")
Warning: 1 parsing failure.
row col expected actual
  1  -- a number     -$
[1] NA
attr(,"problems")
Source: local data frame [1 x 4]

    row   col expected actual
  <int> <int>    <chr>  <chr>
1     1    NA a number     -$
>

**Comment by ctmann** [comment]
This fails:
parse_number("-$3,000)

..but this works:
parse_number("$-3,000")
