### ISSUE TITLE
read_lines craches on big gzipped file

### ISSUE THREAD

**Issue by dselivanov** [hadley/readr#309]
I'm trying to read big text file (~4.5gb in gzipped form, english wikipedia dump)
`read_lines` produce following error:
> Error in read_lines_(ds, locale_ = locale, n_max = n_max, progress = progress) : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:137

EDIT: I'm doing it on machine with 250gb ram, so ram is not an issue.

**Comment by dselivanov** [comment]
Also I'm using Rcpp_0.12.1, see https://github.com/RcppCore/Rcpp/issues/302.

**Comment by MagicForrest** [comment]
I can report the same thing.  Trying to read a large text file with read_fwf(), 220 MB gzipped, 2.5 GB uncompressed.  It reads fine when uncompressed but fails with the "long vectors not supported" error above.  I am using readr 0.2.2, Rcpp 0.12.3, R 3.02.

Just let me know if there is any more info I can provide or testing.

**Comment by dselivanov** [comment]
`data.table::fread` works fine.

**Comment by MagicForrest** [comment]
Indeed.  But I switched from ` data.table::fread` to `read::read_fwf` because it was very much faster, and that makes quite a difference to my workflow.  

In general I have a lot of time for `data.table` though ;-)

**Comment by dselivanov** [comment]
Never tried to read fixed width files. On plain CSV files, `fread` almost always 2-3x faster.

**Comment by MagicForrest** [comment]
Hey, thanks for the tip. The reason `fread` was slow was that I needed to use `awk` to strip out the multiple whitespaces, but I just realised that was solved in v1.9.6.  And yes, now it is very fast!  But it doesn't read gzipped files, so I'll need to to test manually ungzipping the files and using `fread` against using `read_fwf` - although the bug above implies that I'll need to manually ungzip the files anyways, so `read_fwf` loses that advantage.

I'll check it out tomorrow, but cheers again for the reminder on `fread`

**Comment by dselivanov** [comment]
Not everybody remembers, that `fread` can use unix pipe as input: `fread("zcat < path/to/file.gz")` will solve your problems :-) see https://github.com/Rdatatable/data.table/issues/717.
You can even use it to read from hdfs. See my [post](http://dsnotes.com/articles/r-read-hdfs) for example.

**Comment by hadley** [comment]
Deleting all the data.table stuff which is peripheral to this issue. @dselivanov can you please provide a reproducible example?

**Comment by dselivanov** [comment]
```r
library(readr)
# works
txt = rep(paste(rep('a', 2 ^ 16), collapse = ''), 2 ^ 15 - 1)
writeLines(txt, con = gzfile('~/temp/test_read_lines.gz', open = 'w+', compression = 1))
rm(txt)
txt = read_lines("~/temp/test_read_lines.gz")
rm(txt)
# not works
txt = rep(paste(rep('a', 2 ^ 16), collapse = ''), 2 ^ 15)
writeLines(txt, con = gzfile('~/temp/test_read_lines.gz', open = 'w+', compression = 1))
rm(txt)
txt = read_lines("~/temp/test_read_lines.gz")
```

**Comment by hadley** [comment]
Minimal reprex

```R
tmp <- tempfile(fileext = ".gz")

x <- rep(paste(rep('a', 2 ^ 16), collapse = ''), 2 ^ 15)
writeLines(txt, con = gzfile(tmp, open = 'w+', compression = 1))
y <- readr::read_lines(tmp)
```

**Comment by hadley** [comment]
@jimhester this should be fairly straightforward - will just require using the long vector API.
