### ISSUE TITLE
read_csv: currently types are guessed based on first 1000 lines. Could that number be made adjustable?

### ISSUE THREAD

**Issue by akhmed1** [hadley/readr#310]
The data that I work with has a large number of variables (up to 700 and more) so specifying the types manually is not a good option. 

`guess_types` is doing an amazing job of guessing the column types based on [the first 1000 lines](https://github.com/hadley/readr/blob/f219c3821ff46033347d78db9717a39aea4752bf/R/col_types.R#L221) but 1000 lines are frequently not enough: When the first 1000 is all NULLs it resorts to "character" while the true type could be, say, numeric. 

Could that number 1000 be made adjustable (Say, as a parameter or environmental variable)?

**Comment by hadley** [comment]
No, it's unlikely. At some point, you're better off just specifying the column types.

**Comment by akhmed1** [comment]
Thanks for the quick reply! Unfortunately, it is not feasible. 
I will need to fork I guess.

**Comment by ajdamico** [comment]
duplicate of https://github.com/hadley/readr/issues/216

i'm curious why it's a problem to give users the option?

at the point we have to sit down and figure out the column types, reverting to `read.csv` becomes the most painless solution?  but i might be an extreme use-case because i spend a disproportionate amount of time figuring out how to get csv files into databases.  thanks for all your hard work, hadley

**Comment by hadley** [comment]
Because options are bad, and there are existing work arounds. e.g. load as character and then call `type_convert()`

**Comment by akhmed1** [comment]
@hadley Regarding `type_convert`: good point (considering #148 as well) but this requires loading everything as characters first. Wouldn't that require having 2 copies of the full data in memory (at least at some instance in time)?

If yes, is it really preferred to double the memory requirements vs just adding the option? (considering `readr` emphasis on performance and memory footprint)

I can't escape that feeling that `1000` is just an arbitrary number and the user is in a better position to tune the appropriate value for a given use-case.

**Comment by hadley** [comment]
@akhmed1 what do you think the initial column parsing does? It also reads into memory and then figures out the correct column type.

**Comment by akhmed1** [comment]
@hadley it [does not go through the **full** file](https://github.com/hadley/readr/blob/0f0d1266b9db0be8aa4b9c1b03ef7487de85dbac/src/read.cpp#L231) when guessing, does it?

Here is some simple profiling

```r
library(lineprof)
library(readr)

set.seed(42)
N <- 10000000L
raw_text <- paste0(c("x,y,z",
                     paste0(1:N,",",1:N,",",1:N)), 
                   collapse="\n")

read_csv_hadley <- function() {
  df <- type_convert( read_csv(raw_text, 
                                col_types = cols(.default = "c")))
  summary(df)
}

read_csv_akhmed <- function() {
  df <- read_csv(raw_text)
  summary(df)
}

# Akhmed
prof_akhmed <- lineprof(read_csv_akhmed())
print(prof_akhmed)

# Hadley
prof_hadley <- lineprof(read_csv_hadley())
print(prof_hadley)
```

Your solution:
```r
> print(prof_hadley)
Reducing depth to 2 (from 18)
   time   alloc release dups                                ref
1 1.599 642.128  14.033  133        c("type_convert", "vapply")
2 2.175 129.100 142.180  169        c("type_convert", "lapply")
3 0.332  90.701  52.521  192 c("summary", "summary.data.frame")
                         src
1 type_convert/vapply       
2 type_convert/lapply       
3 summary/summary.data.frame
```

Mine:
```r
> print(prof_akhmed)
Reducing depth to 2 (from 16)
   time  alloc release dups                                ref
1 0.982 54.556   0.000  244    c("read_csv", "read_delimited")
2 0.245 91.192  63.954  173 c("summary", "summary.data.frame")
                         src
1 read_csv/read_delimited   
2 summary/summary.data.frame
```

**Comment by coolbutuseless** [comment]
I really (really!) think the number of rows for col_types imputation should be user adjustable.  The inflexibility here is a real pain point with `readr::read_csv`.

Like many others, I encounter sets of csv files that need to be read programmatically - not every CSV file can get individual treatment - there's just too many of them!

So you `readr::read_csv` a set of CSV files and then have to go back and write individual lines with custom `col_types` arguments for those which fail.

... And then I fallback to `base::read.csv` to read the whole file for those with problems, use the classes of the column of that file to create a col_types string to store for later use.

So I end up writing wrapper code that reads a csv twice (once with `base::read.csv` and once with `readr::read_csv`) just so you can impute the types correctly without manual intervention.  But this is a crazy workaround for not having an argument to set the number of imputation rows in `read_csv`.

My 2 cents.

**Comment by Breza** [comment]
Hadley's new book has updated information about how readr parses columns: http://r4ds.had.co.nz/data-import.html
