### ISSUE TITLE
Make it easy to catch mutations in the data by emitting col_types string

### ISSUE THREAD

**Issue by earino** [hadley/readr#314]
One of the nice features of readr is that it introspects column types and gives you data frames with columns of "appropriate" data types. This is cool. It does so heuristically by reading a bunch of rows (but not all) and guessing.

This is very nice for interactive use, however I think it could be made into a neat feature to catch data schema mutation.

I would like to propose a new function which reads a *whole* CSV file, and from the entire file returns a col_types string. A user can then take that string and put it in their production script's read_csv ca;;, so that in the future, if a new data file comes in which has different data types, instead of (for example) silently returning a data frame which has chars where a date once was, it will now give a proper error.

**Comment by hadley** [comment]
This is a great idea :)

**Comment by jennybc** [comment]
If implemented, it might be nice to comply with something like csvy: <http://csvy.org>, <http://dataprotocols.org/json-table-schema/>. The rio package just accommodated csvy (https://github.com/leeper/rio/issues/52).

**Comment by hadley** [comment]
I'm thinking that the default behaviour should be to spit out the code that you can copy and paste into the `col_types` in order to repeat the exact same parsing in the future.

**Comment by jimhester** [comment]
Addressed by #437

**Comment by drolejoel** [comment]
is it OK to add a comment to this completed enhancement, or should I add a new enhancement request?

While spitting out the column specification (I like this) is a great feature as a default, it gets a tad tedious to see the same red text on the screen once the spec has been figured out. My suggestion is to add a "silent = TRUE" option to suppress the column specifications if they are not wanted.
Thank you for your consideration.

**Comment by hadley** [comment]
It's always better to submit a new issue.  (But this one is already handled: just do `col_types = col()`)

**Comment by drolejoel** [comment]
ok  thank you
