### ISSUE TITLE
read_csv() error: could not find function "cols"

### ISSUE THREAD

**Issue by csrvermaak** [hadley/readr#315]
I'm getting this error when I use read_csv, using the example on cran:

```
read_csv("iris.csv", col_types = cols(
  Sepal.Length = col_double(),
  Sepal.Width = col_double(),
  Petal.Length = col_double(),
  Petal.Width = col_double(),
  Species = col_factor(c("setosa", "versicolor", "virginica"))
))


Error in col_types_standardise(col_types, col_names, types(ds, tokenizer)) : 
  could not find function "cols"
>
```

Please advise?

**Comment by csrvermaak** [comment]
Fixed, manually downloaded tarball from CRAN.

I was on 0.1.1, installed via RStudio->packages->Install, and then checked for updates using RStudio->Update.. Both of these methods didn't pick up the new release? Should I raise this issue in the RStudio repo, or is that readr specific?

**Comment by hadley** [comment]
You might be using a bad CRAN mirror

**Comment by csrvermaak** [comment]
Thanks @hadley
