### ISSUE TITLE
Problem with read_csv - Error

### ISSUE THREAD

**Issue by bluepill5** [hadley/readr#320]
I need help please, whe i run:

> read_csv("iris.csv", col_types = cols(
     Sepal.Length = col_double(),
     Sepal.Width = col_double(),
     Petal.Length = col_double(),
     Petal.Width = col_double(),
     Species = col_factor(c("setosa", "versicolor", "virginica"))
 ))

I get:

*Error: Unknown TZ UTC*

And if i try with this:

> read_csv("iris.csv", col_types = cols(
     Sepal.Length = col_double(),
     Sepal.Width = col_double(),
     Petal.Length = col_double(),
     Petal.Width = col_double(),
     Species = col_factor(c("setosa", "versicolor", "virginica"))
 ), locale = locale(tz = "America/Mexico_City"))

i get:

*Error: not compatible with STRSXP*

But i don't know what is the problem.

Additional Info:

> packageVersion("readr")
[1] ‘0.2.2’
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Spanish_Mexico.1252  LC_CTYPE=Spanish_Mexico.1252    LC_MONETARY=Spanish_Mexico.1252
[4] LC_NUMERIC=C                    LC_TIME=Spanish_Mexico.1252

**Comment by bluepill5** [comment]
The problem is that in my file there is an empty column, when i don't specify the types of columns i get an empty column:

 $ NA         : chr  NA NA NA NA ...

But i don't know how ommit this column, or in col_types specify some random type.

**Comment by bluepill5** [comment]
The solution that i found was don't specify the names of headers and use col_skip(). There is other solution?

**Comment by hadley** [comment]
Could you please provide a reproducible example?
