### ISSUE TITLE
Parsing commas inside double and single quotes

### ISSUE THREAD

**Issue by nwstephens** [hadley/readr#324]
I'm reading data in from the audit file, and I noticed that I get the "desired" behavior from read.csv, but I get warnings and undesirable output from read_csv.

> f <- tempfile()
> cat('myheader\n', file = f)
> cat('dat <- \"read.csv(\'myfile\', as.is = T)\"\n', file = f, append = T)

> read.csv(f) # no warning
                              myheader
1 dat <- read.csv('myfile', as.is = T)

> read_csv(f) # warning: 1 parsing failure; expected 1 column; actual 2 columns
Warning: 1 parsing failure.
row col  expected    actual
  1  -- 1 columns 2 columns
                   myheader
1 dat <- "read.csv('myfile'

**Comment by hadley** [comment]
Yes, because the csv spec (such as it is) only uses `"` for quoting. You'll need to use `read_delim(quote = "'")`
