### ISSUE TITLE
Lubridate problems

### ISSUE THREAD

**Issue by csrvermaak** [hadley/readr#325]
Hi - thank you for a fantastic set of packages. One issue that we seem to encounter is when using lubridate with readr.

We have standardised our dates to always be lubridate dates, but when we save a tbl_df() to .csv using write_csv(), the resulting column is saved in lubridate format, which cannot then be read by read_csv.

At the moment, we insert a %>% mutate(date=as.Date(date)) in the write_csv() call to save the column as Date format, and we can then specify "D" type when reading back with read_csv().

Would it be possible to add a e.g. "L" column type to read_csv, that reads "lubridate" columns?

Regards

**Comment by hadley** [comment]
Could you please provide a reproducible example?

**Comment by csrvermaak** [comment]
Sure - apologies:

```
library(readr)
library(lubridate)
library(dplyr)


### ============ FAILING EXAMPLE - generates Warnings ====================
dfExampleNotWorking <- data_frame(date = c(ymd(20020131),ymd(20020131)),value = c(10,11)) %>% 
  tbl_df() %>% 
  write_csv("C:/temp/ExampleNotWorking.csv")

dfReadNotWorking <- read_csv("C:/temp/ExampleNotWorking.csv",col_types = "Di")


### ============WORKING EXAMPLE (using mutate as.Date()) ===================
dfExampleWorking <- data_frame(date = c(ymd(20020131),ymd(20020131)),value = c(10,11)) %>% 
  tbl_df() %>% 
  mutate(date = as.Date(date)) %>% 
  write_csv("C:/temp/ExampleWorking.csv")

dfReadWorking <- read_csv("C:/temp/ExampleWorking.csv",col_types = "Di")

```

**Comment by hadley** [comment]
Both of those work fine for me. Here's a more minimal reprex:

```R
library(lubridate)
library(dplyr)

data_frame(date = c(ymd(20020131),ymd(20020131))) %>% 
  format_csv()

data_frame(date = c(ymd(20020131),ymd(20020131))) %>% 
  mutate(date = as.Date(date)) %>% 
  format_csv()
```
