### ISSUE TITLE
read_csv warnings

### ISSUE THREAD

**Issue by wenbostar** [hadley/readr#329]
Hi All,

Does anyone know what's the problem?

> read_csv("test.csv")->a
|================================================================================| 100%  547 MB
Warning: 1566 parsing failures.
row col     expected       actual
  3  -- 1586 columns 1582 columns
  4  -- 1586 columns 1583 columns
  5  -- 1586 columns 1583 columns
  6  -- 1586 columns 1583 columns
  7  -- 1586 columns 1583 columns
... ... ............ ............
.See problems(...) for more details.
> head(problems(a))
  row  col     expected       actual
1   3 <NA> 1586 columns 1582 columns
2   4 <NA> 1586 columns 1583 columns
3   5 <NA> 1586 columns 1583 columns
4   6 <NA> 1586 columns 1583 columns
5   7 <NA> 1586 columns 1583 columns
6   8 <NA> 1586 columns 1583 columns

Best regards!
Bo

**Comment by hadley** [comment]
Is the message not self explanatory? You can 1582 or 1583 columns but readr expected 1586
