### ISSUE TITLE
Readr can't recognise scientific notation properly

### ISSUE THREAD

**Issue by Ironholds** [hadley/readr#330]
Example file:

>1357899297.363953	CkX1wf3ZdXNvYRVMwb	192.168.27.10	68	192.168.27.1	67	00:20:18:eb:ca:1b	192.168.27.10	4.294967e+09	3301577506
>1357899310.838000	CkX1wf3ZdXNvYRVMwb	192.168.27.10	68	192.168.27.1	67	00:20:18:eb:ca:1b	192.168.27.10	4.294967e+09	2393222756

So we do:

>  col_types <- "nccncnccnn"
>  col_names <- c("timestamp", "uid", "origin_host", "origin_port", "response_host",
                 "response_port", "mac_address", "assigned_ip", "lease_time",
                 "transaction_id")
>  nas <-c("","(empty)", "-","NA")
> data <- readr::read_tsv(file, col_types = col_types, col_names = col_names, comment = "#", na = nas)

And then:

> data$lease_time
> [1] 4.29 4.29

4.294967e+09	is definitely not 4.29. I'm just going to read them in as character strings and convert them base-R-side, but it would be good to have at least numeric types (since that's what people are more likely to use with large numbers, which are the ones likely to be in scientific notation) support it.

**Comment by hadley** [comment]
You want d for double, not n for (flexible) number
