### ISSUE TITLE
Error about negative vector lengths reading large file

### ISSUE THREAD

**Issue by elbamos** [hadley/readr#331]
I get this:  

Error in .Call("readr_read_tokens", PACKAGE = "readr", sourceSpec, tokenizerSpec,  : 
  negative length vectors are not allowed

About 41% into reading an 8GB space-delimited text file with read_delim().  

The command that fails is:  vecs <- read_delim("./GoogleNews-vectors-negative300.txt", skip = 1, n_max = 3100000, delim = " ")

read-table() will read the file, but it doesn't get the columns right.

**Comment by hadley** [comment]
Fixed by #433
