### ISSUE TITLE
read_table is a misleading name

### ISSUE THREAD

**Issue by antoine-lizee** [hadley/readr#332]
It took me a while to get up to speed with the difference between `read_table` and `read.table`, the former being way stricter on the actual formatting of the file (fwf). It seems that the drop-in replacement for the latter is rather something like 
```
read_table2 <- function(..., sep = " ") {
   read_delim(..., delim = sep)
}
```
`read_table`, for instance, is absolutely not compatible with `write.table` currently.

For clarity purposes to the new users of the `readr` package, I propose a change in function names (since there is the very close `read_fwf` already) or at least a clarification in the doc of `read_table`.

**Comment by hadley** [comment]
I think the docs are already fairly clear:

```R
#' This is designed to read the type of textual data where each column is
#' separate by one (or more) columns of space. Each line is the same length,
#' and each field is in the same position in every line. It's similar to
#' \code{\link{read.table}}, but rather parsing like a file delimited by
#' arbitrary amounts of whitespace, it first finds empty columns and then
#' parses like a fixed width file.
```
