### ISSUE TITLE
Implement comment skipping for read_fwf()

### ISSUE THREAD

**Issue by yportier** [hadley/readr#334]
I have fixed width text files with headers, the size of which (the amount of lines to skip) varies greatly from file to file. I could first read a file and figure out the amount of lines to skip before reloading it with the skip value set, but it feels clumsy and it would be nice to be able to do that in one go. Headers/Comments being often identifiable by the first few characters (in my case, the line starts by the letter H).
It would also be nice to have the possibility to save those skipped lines (the whole header) in a variable or a file at the same time as one may need to parse it further to collect some information from it.

**Comment by jennybc** [comment]
I was about to say that the new-ish argument `comment` should work for the header skipping (as long as data lines don't start with H). See https://github.com/hadley/readr/issues/68, now closed/fixed. But now I see that `comment` is not (yet?) available for `read_fwf()`.

**Comment by yportier** [comment]
Something like `comment` could definitely work, yes.
It may be worth nothing though that in the case of a header, it might no be necessary to test every single line as it is clear that after we've encountered the first row of data, there is no more header.

**Comment by holstius** [comment]
Two suggestions for interested parties (not just Hadley!)

1. Assign comments to the returned object using 'comment()<-'. 
2. Design an API for a more general 2-part approach. Maybe 'meta=list(prefix="#", parser=as.character, simplify=FALSE)' would accomplish the above? Support for emerging CSV metadata conventions could be implemented as extensions.

**Comment by hadley** [comment]
@holstius that's unfortunately rather difficult to do without losing the performance benefits of the way that readr is structured.
