### ISSUE TITLE
Option to disable time parsing?

### ISSUE THREAD

**Issue by mkiang** [hadley/readr#335]
I will occasionally get this error when using `read_csv()`
```
Error: Unknown TZ UTC
Called from: check_tz(tz)
```
I cannot consistently reproduce the error (so no example dataset), and the `read_csv()` will usually work if I just run everything again. Given the inconsistency, it's been hard to test, but I assume the error is because a column will sometimes look like a `datetime` even though they are all float.

Is it possible to add an option to just disable time parsing completely? 

Also, as far as I can tell from the documentation, it's not possible to directly specify that all columns should be a certain type (e.g., all `double`). I've been using `c_types <- paste0(rep("d", n_cols), collapse = "")` as my work around, but I imagine it's a common enough scenario to warrant a its own option. Did I miss it somewhere?

**Comment by hadley** [comment]
I'd rather fix the bug instead of disabling date-time parsing.  There are some big changes coming that should resolve this issue.
