### ISSUE TITLE
issue handling data read in as time format (t) using read_csv

### ISSUE THREAD

**Issue by nickbond** [hadley/readr#337]
I have a dataset with seperate date and time columns, with time in H:M:S. My initial reading of the documentation was to read this in as time format (lower case t) in the column specification for read_csv. The data are then correctly read in, but as integer seconds. However, it's not obvious how to convert these back to H:M:S representation. Perhaps this is undesirable. 

In any case, suggesting how users should deal with time columns such as this somewhere in the documentation would be really useful. I find numerous datasets have separate date and time columns necessitating treatment other than via the standard Date (D) and date time (T) formats.

Thanks for some great tools!

Best regards

Nick

**Comment by hadley** [comment]
Why you do want to time as a string formatted like "H:M:S"?

**Comment by nickbond** [comment]
Exporting to csv etc for use by non R users. As an aside, when reading in separate date and time columns, it also seems easier to convert them to POSIXct datetime by first reading both date and time in as character, and then combining via paste before conversion outside read_csv. In the later case the time format (t) looks more useful than it is to the uninitiated. In both cases, it's about dealing with data in/out in a common format (separate date and time columns) used outside R.

**Comment by hadley** [comment]
This behaviour seems correct to me:

```R
tibble::data_frame(x = hms::hms(1:5 * 1000)) %>% 
  format_csv("") %>% 
  cat()
#> x
#> 00:16:40
#> 00:33:20
#> 00:50:00
#> 01:06:40
#> 01:23:20
```
