### ISSUE TITLE
Allow read_lines to gracefully skip null values

### ISSUE THREAD

**Issue by nathanielng** [hadley/readr#338]
Unlike `readLines()`, readr::read_lines() doesn't have a `skipNul=TRUE` option. Hence it either chokes on null characters, or strings get truncated at the null character. Could a `skipNul=TRUE` option be implemented?

**Comment by hadley** [comment]
Is there some reason that even needs to be an option? Why shouldn't it always do so?

**Comment by nathanielng** [comment]
Come to think of it, I don't really see any need to be an option (even for backward compatibility).  Perhaps Nuls should **always** be skipped, i.e. skipNul=TRUE always and skipNul=FALSE isn't allowed.

**Comment by hadley** [comment]
Can copy what `CollectorCharacter::setValue()` does
