### ISSUE TITLE
col_date or col_datetime does not support %I hour format for AM/PM tagged hours

### ISSUE THREAD

**Issue by bdb67** [hadley/readr#340]
For example, parsing date "12/31/1991 6:00:00 PM", given date format  = "%m/%d/%Y %I" will return an error. 

readr::parse_datetime("12/31/1991 6:00 PM", "%m/%d/%Y %I")

**Comment by hadley** [comment]
You mean

```R
readr::parse_datetime("12/31/1991 6:00 PM", "%m/%d/%Y %I:%m %p")
```

right?

Adding `%I` support should be pretty easy
