### ISSUE TITLE
datetime variables in the format %H:%M:%OS %p that are between 12.00 PM and 12.59 PM

### ISSUE THREAD

**Issue by nevermiss** [hadley/readr#341]
Hi Hadley

I’m having trouble parsing datetime variables in the format %H:%M:%OS %p that are between 12.00 PM and 12.59 PM. All other dates work fine. Here is an example:

parse_datetime(“06/JUN/15 06:49:00.000000000 PM”, “%d/%b/%y %H:%M:%OS %p”) # Works
parse_datetime(“06/JUN/15 12:49:00.000000000 PM”, “%d/%b/%y %H:%M:%OS %p”) # Errors
parse_datetime(“06/JUN/15 12:49:00.000000000”, “%d/%b/%y %H:%M:%OS”) # Removing the PM Works

I’ve been removing the ‘PM’ as a work-around for now, but would be great to hear your thoughts.

Regardless, this is an amazing package so thank you for it!

**Comment by jimhester** [comment]
This is now fixed by supplying '%I' instead of '%H', which should not be used with '%p'. from `?strptime` entry for '%p'

> ‘%p’ AM/PM indicator in the locale.  Used in conjunction with ‘%I’
          and *not* with ‘%H’.
