### ISSUE TITLE
readr/tbl_df followed by base::reshape produces odd tables when moving from long to wide

### ISSUE THREAD

**Issue by DerekYves** [hadley/readr#343]
Apologies in advance that I cannot provide a reproducible example (I tried with smaller sets like mtcars but didn't notice the issue). I recently switched my daily batch process to readr/read_csv and then found that subsequent calls to base::reshape performed on a number of different files later in the script produced oddly formed dataframes. For example, reshaping a file of IDs with various text descriptor columns from long to wide (where a row is now a unique id followed by a series of text value columns (e.g. ID, code_1, description_1, code_2, description_2...etc.)) no longer works. Instead I get a df/tble_df with the following structure (note how all the reshaped variables are collapsed into two oddly named columns filled with NAs: `code_c(1, 2, 3, 4, 5, 6, 7, 8, 9)` and `description_c(1, 2, 3, 4, 5, 6, 7, 8, 9)`):

> str(x)
Classes ‘tbl_df’ and 'data.frame':	6461 obs. of  3 variables:
 $ ID                                       : int   ...
 $ code_c(1, 2, 3, 4, 5, 6, 7, 8, 9): chr  NA NA NA NA ...
 $ description_c(1, 2, 3, 4, 5, 6, 7, 8, 9)  : chr  NA NA NA NA ...

Removing the tbl_df attribute before the reshape fixes the problem, and the code runs as expected, creating a frame such as this:

> str(x)
'data.frame':	6461 obs. of  19 variables:
 $ ID            : int  
 $ code_1: chr  [various text values deleted from example]
 $ description_1  : chr  [various text values deleted from example]
 $ code_2: chr  [various text values deleted from example]
 $ description_2  : chr  [various text values deleted from example]
 $ code_3: chr [various text values deleted from example]
 $ description_3  : chr [various text values deleted from example]
...

Anyone seen this and have any idea why this is happening? I'd like to keep the tbl_df attribute but also find base:reshape to be a very good tool for these kind of non-aggregating reshape operations I do in many, many places with my data; but can't find similar issues reported on the forums. Thanks so much for any help with this!

**Comment by hadley** [comment]
You might need to use `as.data.frame()` but I've got no idea why reshape would have a problem with the extra classes.
