### ISSUE TITLE
parsing something like 12:05 PM

### ISSUE THREAD

**Issue by johngoldin** [hadley/readr#345]
I had some data from a blood pressure cuff with some readings such as "12:05 PM".  parse_time doesn't like that:
> parse_time(c("0:05 PM", "12:05 PM"), format = "%H:%M %p")
Warning: 1 parsing failure.
row col   expected   actual
  2  -- valid date 12:05 PM
[1] 12:05:00 NA  

parse_time has a point. I understand that technically it should be 0:05 PM.  But a bit of googling can demonstrate that there's a fair amount of data out there that doesn't follow the rules.  See http://www.timeanddate.com/time/am-and-pm.html.  One can find lots of examples of schedules that correctly or incorrectly have times such as 12:05 PM. What they mean isn't really ambiguous even if it's technically incorrect. Given that the philosophy behind readr is to smooth out data processing problems, it would be best if parse_time would gracefully handle things like 12:05 PM.

**Comment by Dulani** [comment]
@johngoldin , I just ran into this too: 
`parse_datetime("12/30/2015 11:59:00 PM","%m/%d/%Y %H:%M:%S %p") #works`
`parse_datetime("12/30/2015 12:01:00 PM","%m/%d/%Y %H:%M:%S %p") #error`  

From my perspective, 12:XX PM is a perfectly valid time if you aren't using a 24 hour clock (which is what the PM says to me).  So, I think this is truly a bug, not a result from strictly parsing something that is ambiguous.

**Comment by Dulani** [comment]
Just realized that this is the same issue as #341.

**Comment by jimhester** [comment]
With https://github.com/hadley/readr/pull/426 and changing `%H` to `%I` as expected this now work as expected

``` r
parse_datetime("12/30/2015 12:01:00 PM","%m/%d/%Y %I:%M:%S %p")
#> [1] "2015-12-30 12:01:00 UTC"
```
