### ISSUE TITLE
read_csv fails on Linux with large files when invoked via Rscript without the methods library

### ISSUE THREAD

**Issue by DerekYves** [hadley/readr#347]
Not sure if this is a "bug" but I notice that readr/read_csv crashes in my daily batch process when it is invoked via Rscript -- vanilla. Adding the methods library to the command as in Rscript -e "library(methods)"... solves the issue. This is beyond my technical expertise but it made me wonder if read_csv should require the methods library if it does not already? Here's the segmentation fault output I get:

 *** caught segfault ***
address 0x7fcf66149540, cause 'invalid permissions'

Traceback:
 1: .Call("readr_guess_types_", PACKAGE = "readr", sourceSpec, tokenizerSpec,     locale_, n)
 2: guess_types_(datasource, tokenizer, locale, n = n)
 3: guess_types(ds, tokenizer, locale, n_max = n_max)
 4: col_spec_standardise(data, skip = skip, comment = comment, n_max = n_max,     col_names = col_names, col_types = col_types, tokenizer = tokenizer,     locale = locale)
 5: read_delimited(file, tokenizer, col_names = col_names, col_types = col_types,     locale = locale, skip = skip, comment = comment, n_max = n_max,     progress = progress)
 6: read_csv(paste0(i, t), na = c(flags), col_types = cols(ATTRIBUTE = "c",     SDATE = "D", EDATE = "D"))
 7: data.frame(read_csv(paste0(i, t), na = c(crdb_flags), col_types = cols(ATTRIBUTE = "c", SDATE = "D", EDATE = "D")))
aborting ...
Segmentation fault (core dumped)

**Comment by hadley** [comment]
I can't imagine what would be causing this because readr doesn't use S4.

Could you please supply a reproducible example?
