### ISSUE TITLE
Problem with reading from https

### ISSUE THREAD

**Issue by ltorgo** [hadley/readr#349]
I'm currently trying to download a data set from the UCI repository using read_csv but I'm getting an error I cannot understand, which does not happen with the standard read.csv function. Here is the reproducible example:
```
dataF <-  "https://archive.ics.uci.edu/ml/machine-learning-databases/audiology/audiology.standardized.data"
data <- read_csv(dataF, col_names=FALSE, na="?")
```
The above code gives me the error:
```
Error in open.connection(con, "rb") : 
  Problem with the SSL CA cert (path? access rights?)
```
If I run `read.csv(dataF, header=FALSE, na.strings=c("?"))` no errors appear and the data is downloaded... Any help/suggestion is most welcome.
Thank you!

**Comment by ltorgo** [comment]
Incidentally, I've manage to overcome the problem doing:
```
data <- read_csv(url(dataF), col_names=FALSE, na="?")
```
But I'm still wondering whether there is a way to avoid this extra `url()`function call...

**Comment by hadley** [comment]
It's likely to be a curl issue which you can reproduce with `curl::curl(dataF)`. If you're still having a problem, can you please file an issue on the https://github.com/jeroenooms/curl ?
