### ISSUE TITLE
read_csv2 removing decimals from values in column

### ISSUE THREAD

**Issue by mamaya881** [hadley/readr#351]
When attempting to use read_csv2 (),  the values in the column "Voltage" are loaded with the decimal points removed automatically(dangerous, as it does not give a warning in this (dev) version that it is doing that). If i attempt to convert the other columns with parse_number, the columns also lose their decimal points but at least these aren't done automatically.

Dataset:
Date;Time;Global_active_power;Global_reactive_power;Voltage;Global_intensity;Sub_metering_1;Sub_metering_2;Sub_metering_3
16/12/2006;18:12:00;3.730;0.144;235.780;16.400;0.000;27.000;17.000
16/12/2006;18:13:00;2.308;0.160;237.430;9.600;0.000;1.000;17.000
16/12/2006;18:14:00;2.388;0.158;237.260;10.000;0.000;1.000;17.000
16/12/2006;18:15:00;4.598;0.100;234.250;21.400;0.000;20.000;17.000

Code below:
```R
hh_power_data <- read_csv2("Date;Time;Global_active_power;Global_reactive_power;Voltage;Global_intensity;Sub_metering_1;Sub_metering_2;Sub_metering_3
                           16/12/2006;18:12:00;3.730;0.144;235.780;16.400;0.000;27.000;17.000
                           16/12/2006;18:13:00;2.308;0.160;237.430;9.600;0.000;1.000;17.000
                           16/12/2006;18:14:00;2.388;0.158;237.260;10.000;0.000;1.000;17.000
                           16/12/2006;18:15:00;4.598;0.100;234.250;21.400;0.000;20.000;17.000",
                           col_types = cols(Time=col_time()))
```
I have tested on a windows, mac  and Ubuntu machine.

SessionInfo()
```
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.2 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readr_0.2.2.9000

loaded via a namespace (and not attached):
 [1] httr_1.0.0     R6_2.1.1       magrittr_1.5   tools_3.2.3    curl_0.9.4     Rcpp_0.12.3    memoise_0.2.1  stringi_1.0-1  knitr_1.12     stringr_1.0.0 
[11] digest_0.6.9   devtools_1.9.1
```

**Comment by hadley** [comment]
Can you please provide a minimal reproducible example? A couple of lines should be sufficiniet to reproduce the problem.

**Comment by mamaya881** [comment]
@hadley Hopefully this is what you need to reproduce the example, let me know if you need anything else.

**Comment by hadley** [comment]
You can use the text data as the first argument to `read_csv2`

**Comment by mamaya881** [comment]
@hadley Thanks for the suggestion, I have done that now. Hopefully, this recreates the issue for you.

**Comment by jkrijthe** [comment]
I think this behaviour was introduced with 7e183e3e1791b67235742c5b456d18cbc63ff68c, which fixed #268, although I am not sure why that is the desired behaviour.

**Comment by hadley** [comment]
I don't think you want `read_csv2()` for this data, as you don't have a "csv2" (i.e. semicolons for separators and `,` as decimals). You should use `read_delim(delim = ";")`

**Comment by jkrijthe** [comment]
I see, that makes sense. Thanks.

**Comment by mamaya881** [comment]
Alright, Thanks
