### ISSUE TITLE
Reading multiline fixed width files

### ISSUE THREAD

**Issue by tchakravarty** [hadley/readr#352]
Hadley, 

I was wondering if it is possible to read in multiline fixed width format files using one of the `readr` functions. The file I am trying to read is [here](http://qed.econ.queensu.ca/jae/1995-v10.4/sueyoshi/). 

Here is a [sample of the data](http://qed.econ.queensu.ca/jae/1995-v10.4/sueyoshi/sueyoshi.zip):

```
4 1 17 1 1
 -5.1536 -0.1668 -2.3412 -0.5062  0.9621  0.3640  0.3678 -0.5081 -0.2227
  0.8142 -0.0389 -0.0445 -0.0578 -0.1175 -0.1232  0.8673 -0.1033 -0.0796
 -0.0341 -0.1716 -0.1801 -0.7014  0.6578  0.5611
4 1 17 2 1
 -5.1536 -0.1668 -2.3412 -0.5062  0.9621  0.3640  0.3678 -0.5081 -0.2227
  0.8142 -0.0389 -0.0445 -0.0578 -0.1175 -0.1232  0.8673 -0.1033 -0.0796
 -0.0341 -0.1716 -0.1801 -0.7014  0.6578  0.5611
4 1 17 3 1
 -5.1536 -0.1668 -2.3412 -0.5062  0.9621  0.3640  0.3678 -0.5081 -0.2227
  0.8142 -0.0389 -0.0445 -0.0578 -0.1175 -0.1232  0.8673 -0.1033 -0.0796
 -0.0341 -0.1716 -0.1801 -0.7014  0.6578  0.5611
4 1 17 4 1
 -5.1536 -0.1668 -2.3412 -0.5062  0.9621  0.3640  0.3678 -0.5081 -0.2227
  0.8142 -0.0389 -0.0445 -0.0578 -0.1175 -0.1232  0.8673 -0.1033 -0.0796
 -0.0341 -0.1716 -0.1801 -0.7014  0.6578  0.5611
4 1 17 5 1
 -5.1536 -0.1668 -2.3412 -0.5062  0.9621  0.3640  0.3678 -0.5081 -0.2227
  0.8142 -0.0389 -0.0445 -0.0578 -0.1175 -0.1232  0.8673 -0.1033 -0.0796
 -0.0341 -0.1716 -0.1801 -0.7014  0.6578  0.5611
```
The [Readme](http://qed.econ.queensu.ca/jae/1995-v10.4/sueyoshi/readme.gs.txt) file provides the FORTRAN and SAS formats: 

**FORTRAN**:
> Fortran Format Statement
> 
>  100  format(5i2/3(9(f8.4)/))

**SAS**: 
> SAS output statement
> put id fail durat period synfail2 /
>    (sage ssex seduc srace sdepend sui smarry
>     slabor scraft scleric sprofess smanage smetals stranseq
>     sodurab sndurab strade stransp smining sservice
>     sconstr sunemp swife shome) (9*8.4/);

Any ideas?

**Comment by ghaarsma** [comment]
Not the most elegant, but it does get the data loaded in:

```R
l <- read_lines('~/SUEYOSHI.DAT')
cat(l,file = '~/SUEYOSHI.FWF',sep = c(' ',' ',' ','\n'))
col_positions <- fwf_widths(c(rep(2,5),rep(8,24)))
dat <- read_fwf('~/SUEYOSHI.FWF',col_positions = col_positions)
```
Since a single line is folded over 4 times, that cat command cycles through 3 spaces and than a linefeed. If you don't want to write to an itermediate file, you can also do the following:
```R
l <- read_lines('~/SUEYOSHI.DAT')
l <- paste0(l,c(' ',' ',' ','\n'),collapse = '')
col_positions <- fwf_widths(c(rep(2,5),rep(8,24)))
dat1 <- read_fwf(l,col_positions = col_positions)
```

**Comment by hadley** [comment]
I'd say this is out of scope for now, sorry.

**Comment by jsta** [comment]
@ghaarsma @tchakravarty I believe there is a base R function for this: `?read.fortran`

**Comment by ghaarsma** [comment]
`read.fortran` uses `read.fwf` under the hood, which works OK but only for small files. `read.fwf` can take hours for a medium to large file.

Reason for this is that `read.fwf` generates a large temporary file with a very inefficient repeat loop which then gets red with `read.table`. Thank goodness for readr.
