### ISSUE TITLE
%b not recognizing month in all caps when reading a date like 29-DEC-15

### ISSUE THREAD

**Issue by wlasenek** [hadley/readr#355]
Hi Hadley & Team! Many thanks for a great package. 

I've noticed a small issue when parsing dates, which readr can't handle while strptime can. Here're the details:

> parse_date("29-Dec-15", "%d-%b-%y") 
[1] "2015-12-29"

> parse_date("29-DEC-15", "%d-%b-%y")
[1] NA

So when the month is in all caps, readr will have problem parsing it.

But on the other hand, when the original datetimes look like: 
29-DEC-15 10.47.36
30-DEC-15 23.56.42
I can parse them into POSIXct by going:

> d.online$creation_date = as.POSIXct(strptime(d.online$creation_date, format='%d-%b-%y %H.%M.%S', tz='UTC'))
> d.online$creation_date
  [1] "2015-12-29 10:47:36 UTC" "2015-12-30 23:56:42 UTC"

All the best,
Michal

**Comment by hadley** [comment]
This works for me:

``` r
parse_date("29-DEC-15", "%d-%b-%y")
#> [1] "2015-12-29"
```
