### ISSUE TITLE
Error "long vectors not supported yet" for files >152Mb

### ISSUE THREAD

**Issue by smgogarten** [hadley/readr#359]
I am trying to read in several files that have identical format, and differ only in file size (both in number of rows and length of strings in the columns). Files below a certain threshold work fine, but for larger files I get the error

```
annot <- read_tsv(annot.file, col_types="ci_cc__c", comment="##")
Error in guess_header_(datasource, tokenizer, locale) :
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:137
Calls: read_tsv ... col_spec_standardise -> guess_header -> guess_header_ -> .Call
```

The largest file that works is 158977246 bytes and 3875905 lines. The smallest file that fails is 194827397 bytes and 2657330 lines.

**Comment by jlegewie** [comment]
I have the same problem with a file that is 3.31GB (about 5.2 million rows). BUT it only happens when the file is zipped. Same file unzipped is not a problem.

**Comment by oldirtybasti** [comment]
I have the same problem. Thanks to both of you for analysing the issue in depth. I use a workaround to use read.table for large files now. I hope this issue can be fixed soon.

**Comment by jlegewie** [comment]
Just adding my most recent error message for a 990MB zipped, 5.4 GB unzipped file here. Same as above but with additional warning just in case it's relevant. Manually unzipping continues to work.

```
Error in guess_header_(datasource, tokenizer, locale) :
  long vectors not supported yet: ../../../../R-3.2.2/src/include/Rinlinedfuns.h:137
In addition: Warning message:
In (function (con, what, n = 1L, size = NA_integer_, signed = TRUE,  :
  possible truncation of >= 4GB file
```

**Comment by dselivanov** [comment]
duplicate #309
