### ISSUE TITLE
Option to write UTF-8-BOM in write_csv() (for excel)

### ISSUE THREAD

**Issue by zross** [hadley/readr#375]
I've converted from write.csv to write_csv for a few projects and am finding that write_csv handles special characters differently and results in very odd looking results when opened in Excel. I'm guessing it's related to writing to UTF-8? Here is an example where the dash is an en dash:

```r
dat <- data.frame(a=1:2, b=c("reported – estimate", "updated – estimate"))

write.csv(dat, "d:/junk/writecsv.csv")
readr::write_csv(dat, "d:/junk/readr.csv")
```

The file from write.csv looks perfect in Excel and when looking at the raw data. The example from readr looks like this in raw:

![image](https://cloud.githubusercontent.com/assets/1395177/13433772/57cfeefe-dfa1-11e5-96a2-211f04c6dcc7.png)

and this in Excel:

![image](https://cloud.githubusercontent.com/assets/1395177/13433787/638a7fde-dfa1-11e5-81ed-7899e8419799.png)

In my own use case I'm taking advantage of the format_csv function so it's not an easy conversion to go back to `write.csv` -- I'd love to continue using `readr`.

**Comment by hadley** [comment]
This seems to be a bug in excel: http://stackoverflow.com/questions/6002256/is-it-possible-to-force-excel-recognize-utf-8-csv-files-automatically

But we should add an option to write a BOM to help excel. Possible either an argument `write_BOM` or a new function: `write_excel_csv()`.

**Comment by hadley** [comment]
Probably should do in conjunction with #263

**Comment by jimhester** [comment]
Fixed by https://github.com/hadley/readr/pull/448
