### ISSUE TITLE
export `readr:::collectorGuess`

### ISSUE THREAD

**Issue by njtierney** [hadley/readr#377]
Hi Hadley, 

As discussed in the [visdat issue](https://github.com/tierneyn/visdat/issues/7), it would be great if you could export `readr:::collectorGuess`.

Thanks again for your help!

**Comment by hadley** [comment]
Or better `collector_guess()`

**Comment by njtierney** [comment]
Heck yes! Who doesn't love snake_case.

**Comment by njtierney** [comment]
Thank you!
