### ISSUE TITLE
Reading milliseconds with read_csv and col_time

### ISSUE THREAD

**Issue by PhillipUT** [hadley/readr#379]
I have times that look like this with hours, minutes, seconds and milliseconds:
6:19:43.722

When I use read_csv in readr to read them using col_time("%H:%M:%OS") it reads hours, minutes, and seconds just fine, but there are no milliseconds. I pulled  getOption("digits.secs") to see how many digits on seconds should be displayed, but it says 3, as I’d like. 

When I print out what I’ve read, it looks like
         DATE  TIME_M PRICE
1  2014-01-02 6:19:43 75.10
2  2014-01-02 6:19:49 75.10
3  2014-01-02 7:00:07 75.07

When I assign that first time to a variable and print it, I get 22783 which is the number of seconds since midnight—so no milliseconds. 

strptime does work on the character strings:
d<-"6:19:43.722"
> strptime(d,"%H:%M:%OS")
[1] "2016-03-07 06:19:43.722 EST"

Thanks!

**Comment by hadley** [comment]
Minimal reprex:

```R
str(parse_time("6:19:43.722", "%H:%M:%OS"))
```

This is probably just a simple fix - time should generate a double, not an integer.

**Comment by jimhester** [comment]
As of https://github.com/hadley/readr/pull/425 we now return a hms object which is a double under the hood.

Unfortunately it needs some tweaks to hms to work with partial seconds as `format.hms()` just calls `as.character.hms()`, which has a hard coded format string. But you can get the desired output by coercing to a POSIXct first.

```r
time <- parse_time("6:19:43.722", "%H:%M:%OS")
format(as.POSIXct(time), "%H:%M:%OS3")
#> [1] "06:19:43.722"
```

I am going to close this issue and open one in hms to allow specifying the format for as.character and format.

**Comment by jimhester** [comment]
Turns out devel hms has the partial second printing built in, so using it the partial seconds are printed by default

```r
parse_time("6:19:43.722", "%H:%M:%OS")
#> 06:19:43.722
```

**Comment by thanosgatos** [comment]
I've just run into a similar issue:

```
parse_datetime("2018-07-04 10:33:15.064859", format = "%Y-%m-%d %H:%M:%OS")
[1] "2018-07-04 10:33:15 UTC"
```

`parse_time()` does work as @jimhester describes in his last comment, but `parse_datetime()` does not work as expected. Is this a known issue? How should I deal with this? My datetimes are in the format I've used in my example.

**Comment by hadley** [comment]
@thanosgatos please file a new issue

**Comment by thanosgatos** [comment]
@hadley I'm on it.
