### ISSUE TITLE
feature: Set one column type for all columns

### ISSUE THREAD

**Issue by antoine-lizee** [hadley/readr#382]
I would like to have a way to basically turn off automatic detection of fileds, by specifying one type for all columns.
It feels like the best way to let that happen is to use the `col_types` field when using the string specification, and recycle this, at least when the length is one.

This need arises when using `readr` in a bigger scope, like a framework that has partial knowledge of the structure of the file (number of columns unknown for instance).

The ultimate solution would be to have better control over the parsing, like specifying the number of rows to estimate the column type over, or exclude certain types. My main use case is doubles that are mis-parsed as integers because of round numbers first.

**Comment by hadley** [comment]
Use `cols(.default = "c")` ?

**Comment by antoine-lizee** [comment]
Exactly what I'm looking for - thanks.
