### ISSUE TITLE
Parsing time with format 04:00:00

### ISSUE THREAD

**Issue by dantalus** [hadley/readr#384]
Hello. 

When time is entered in the format of HH:MM:SS, I think readr wants to parse this as a date, which in turn leads to a parsing error. 

```
x <- c("04:00:00", "04:30:00", "14:00:22")
	
parse_time(x) # OK

>  [1]  4:00:00  4:30:00 14:00:22

parse_date(x) # Parsing error

>  Warning: 3 parsing failures.
>  row col           expected   actual
>    1  -- date like %Y-%m-%d 04:00:00
>    2  -- date like %Y-%m-%d 04:30:00
>    3  -- date like %Y-%m-%d 14:00:22

write.table(x, "times.csv", sep = ",", row.names = FALSE)

read_csv("times.csv") # Parsing error

>  Warning: 3 parsing failures.
>  row  col   expected   actual
>   1 time valid date 04:00:00
>   2 time valid date 04:30:00
>   3 time valid date 14:00:22

```

The problem is resolved by specifying the column type. 

`read_csv("times.csv", col_types = cols(.default = "c"))`

This means I either need to know what the col_types are in advance (which is often not the case when working with collaborators who have sent me a large number of large spreadsheets), or to make them all character, which then creates more work on the other side and defeats the purpose of the smart things that readr does. type_convert is useful, but will still set the offending column to NA. Is it possible in the presence of this kind of parsing error for readr to set that col_type to character as a default? Perhaps this is working as intended, but I thought I would point it out. 

Many thanks.

**Comment by hadley** [comment]
The root cause is:

```R
collector_guess(c("04:00:00", "04:30:00", "14:00:22"))
```

probably because the default is to allow any non-numeric separate between year, month, and day components.

I think the right way to fix this is to add a guessor for time that is checked before date.
