### ISSUE TITLE
read_csv check names

### ISSUE THREAD

**Issue by jtaveras** [hadley/readr#388]
Hi, I love that read_csv preserves column names, but unfortunately for column names starting with numbers or underscores (and possibly other characters) ... dplyr functions like group_by don't work.  So I have to replace those characters with a letter.

I see as.tbl in dplyr does replace that leading special character ... so I suppose read_now et al should do the same ... ?

**Comment by hadley** [comment]
Just surround the special names with backticks `` df`x + y` ``

**Comment by jtaveras** [comment]
But I'm accessing these variables programmatically like group_(data, var)
where var the field name. Your dplyr functions don't like names that are
not standard (like with numbers in front, or spaces) when using them
programmatically.

**Comment by hadley** [comment]
Just convert them to names with `lapply(x, as.name)`

**Comment by bbolker** [comment]
If you  prefer sanitized names:

```
data_frame(`x 1`=2,`1 a`=3) %>% rename_all(make.names)
```

**Comment by bbolker** [comment]
Could we have an argument that allows sanitization of names (analogous to `read.csv()`'s `check.names` argument, but with default `FALSE`) ? This would reduce friction if people want to use `read_csv` in a workflow that assumes sanitized names (without the extra workaround that I gave above)

**Comment by batpigandme** [comment]
See https://github.com/tidyverse/readr/issues/826
