### ISSUE TITLE
Discrepancy in documentations: Number of rows read for heuristic

### ISSUE THREAD

**Issue by Make42** [hadley/readr#391]
It says in https://cran.r-project.org/web/packages/readr/vignettes/column-types.html that "To recognise these columns, readr inspects the first 1000 rows of your dataset." while it says in https://blog.rstudio.org/2015/04/09/readr-0-1-0/ that "Readr heuristically inspects the first 100 rows to guess the type of each columns."

Which one is it? The wrong documentation should be fixed.

**Comment by hadley** [comment]
1000 - it changed from version 0.1 to 0.2
