### ISSUE TITLE
read_delim comment: invert, vector, or regex

### ISSUE THREAD

**Issue by r2evans** [hadley/readr#394]
Use cases:

A. Multiple comment characters present in the file, perhaps due to inconsistent file creation formatting.

B. (Specific to me, not the majority use.) Some of my input files (that I don't control) are technically not proper CSV: the first field indicates the number and type of the remaining fields. I need to eventually read all of them (into separate data.frames), so multiple reads are required.

My current workaround is via `grep` and/or `sed` with tempfiles, and though this is generally safe for all dev systems except Windows without Rtools, it also introduces an external pipe.

Options:

1. Provide an `invert_comment` option to *only* accept the "commented" lines (which seems a little counter-intuitive, perhaps). This is perhaps the simplest to implement.

2. Allow a vector for `comment`. A little more work, this has a broader use-case I think with poorly-constructed CSV files. (I don't know that anybody else has the pleasure of dealing with the poorly-constructed data files I'm dealing with ... ;-)

3. Regular expressions. This is a *lot* more work, I admit. Since you're already using Boost, it should be feasible to use `boost/regex.hpp` ([example at Rcpp](http://gallery.rcpp.org/articles/boost-regular-expressions/)).

I don't know that I'm the best to work on it, but I'm familiar enough with Rcpp to give the first two a try. I can try the third, but I admit it will take perhaps more Rcpp expertise than I have. If you are amenable and think one of these is the right direction, I can work on a PR.

**Comment by hadley** [comment]
I think this is probably out of scope of readr for now, although I may consider adding a callback API to give more control over which rows are read (that would make it possible to add random row sampling, for example)

**Comment by r2evans** [comment]
With the callback concept, wouldn't you be concerned about performance? My from-the-hip assumption is that it would be call *per row*, which will get expensive in the long term. (I guess your assumption is that somebody goes outside of the norm by providing a callback, they are knowingly accepting the performance consequences.)

I understand that it's out of scope for the moment. Thanks for the consideration.
