### ISSUE TITLE
read_fwf : dealing with non-integers in fwf data

### ISSUE THREAD

**Issue by lucasmation** [hadley/readr#399]
Can read_fwf deal with non-integer variables, whose decimal point positions is defined by the import dictionary? 

I posted a reproducible example in [this Stack  Overflow question](http://stackoverflow.com/questions/36852032/import-fixed-width-file-read-fwf-that-has-decimal-places-defined-by-dictionary).

**Comment by hadley** [comment]
No - you'll need to do the division yourself.

**Comment by lucasmation** [comment]
Yes, I had done that. 
Since the number of the decimal places is an integral part of most fwf dictionaries, I suggest adding a "decimal_places" argument which would receive a vector of decimal places for each column and do the division (if the position of the column in the vector is not 0 or NA).
