### ISSUE TITLE
Should be able to supply encoding

### ISSUE THREAD

**Issue by hadley** [hadley/readr#40]
Output should always be utf-8

**Comment by hadley** [comment]
I think I have a handle on how to do this now - need to use iconv

**Comment by blaquans** [comment]
Actually, there is no automatic conversion to UTF-8. I think we could automatically detect the encoding of a file using the [chardet command line](https://github.com/chardet/chardet). 

    > system("chardet sources/DE_PF_et_FA.txt")
    sources/DE_PF_et_FA.txt: windows-1252 with confidence 0.73

It seems to work pretty well. The fileEncoding option would still be useful to me.

**Comment by hadley** [comment]
@blaquans right, there's no automatical conversion because this is an open issue. Character encoding detection is difficult to do well automatically and I think is dangerous to turn on by default.

**Comment by okumuralab** [comment]
Base functions accept encodings such as read.csv(..., fileEncoding="SJIS").

**Comment by hadley** [comment]
The interface will probably get nicer, but this now works :)

``` r
x <- c("こんにちは")
Encoding(x)
#> [1] "UTF-8"

y <- iconv(x, "UTF-8", "shift-jis")
Encoding(y)
#> [1] "unknown"

ja <- locale("ja", encoding = "shift-jis")
z <- parse_character(y, locale = ja)
z
#> [1] "こんにちは"
```
