### ISSUE TITLE
How use read_csv precisely separate by comma?

### ISSUE THREAD

**Issue by sulaxd** [hadley/readr#402]
### --- In read.csv case --- (correct)
```
read.csv(text='"A","B","C","D"
+ "1"1"","2","3","4"')
```
Result:
|  A|  B|  C|  D|
| 11|  2|  3|  4|

### --- In read_csv case --- (wrong)
```
read_csv('"A","B","C","D"
+ "1"1"","2","3","4"')
```
_Warning: 3 parsing failures.
row col           expected    actual
  1  A  delimiter or quote 1
  1  A  delimiter or quote 2
  1  -- 4 columns          3 columns_

Result:
|A------|  B|  C|D--|
|11","2 |  3|  4|NA |

### --- In read_delim case --- (surplus double quotes)
```
read_delim('"A","B","C","D"
+ "1"1"","2","3","4"', quote = "", delim = ",")
```
Result:
|"A"----|"B" |"C" |"D" |
|"1"1"" |"2" |"3" |"4" |

**Comment by hadley** [comment]
The behaviour of `read.csv()` seems clearly incorrect to me.
