### ISSUE TITLE
negative length vectors are not allowed

### ISSUE THREAD

**Issue by steverowe** [hadley/readr#403]
When reading the .gz version of the data from the Expedia Kaggle competition, I get this error:
Error in .Call("readr_read_connection_", PACKAGE = "readr", con, chunk_size) : 
  negative length vectors are not allowed

File link: https://www.kaggle.com/c/expedia-hotel-recommendations/download/train.csv.gz

**Comment by hadley** [comment]
Can you provide a link that doesn't require a login?

**Comment by steverowe** [comment]
Try https://1drv.ms/u/s!AlqswdwIdiVGttAxS6r3RyBxQlvT0g.  This will let you download the file and then you could open it from there.

I just used a simple
`x <- read_csv("train.csv.gz")`

**Comment by randomgambit** [comment]
Hello! I am getting the same error on a large zipped file. I use the latest version of `dplyr`

```
Error in .Call("readr_read_connection_", PACKAGE = "readr", con, chunk_size) : 
  negative length vectors are not allowed
```

Is there anything I could do to read it with `read_csv` ?

Thanks!

**Comment by hadley** [comment]
@randomgambit please file a reproducible example in a new issue.

**Comment by randomgambit** [comment]
@hadley thanks for the quick feedback. Unfortunately I cannot post the data. This is tick by tick trading data from a major exchange. Is there any test I can do to figure out what is the error? The variable names contain spaces (if that matters) thanks!
