### ISSUE TITLE
write_csv(): `0.` vs. `0` for doubles?

### ISSUE THREAD

**Issue by ijlyttle** [hadley/readr#410]
Given that you'll be thinking more about write_csv in #387, I thought would bring up an edge case:

In write_csv, would you consider writing (for example) `0.` instead of `0` for those doubles that happen to take integer values?

I recently came across this issue when using write_csv() on a dataframe where the first (at least 1000) values of a variable were `0`. Subsequently, read_csv() chose integer, then encountered problems when the non-zero observations appeared later on.

As you might imagine, my workaround is to use the column specification string in read_csv() - so this is more of an inconvenience than a problem.

**Comment by hadley** [comment]
I'd rather work around this by improving the column guesser - I have some ideas for how to make that easier to use.
