### ISSUE TITLE
Feature: Make "col_currency" available in readr / RStudio 1200+ "Import CSV"

### ISSUE THREAD

**Issue by znmeb** [hadley/readr#411]
I'm testing the new RStudio Preview (0.99.1200 as of this writing). I have a file that contains US dollars and cents, and I'd like to be able to have that parsed to "double" in an "Import CSV" operation in RStudio. I see there was a proposed "col_currency" option (issue #212) ... is this a "readr" feature or an RStudio feature?

**Comment by hadley** [comment]
`col_currency()` become `col_numeric()` I think so maybe it's already exposed? @javierluraschi can you comment?

(I'm closing this issue since it's really an RStudio issue. @javierluraschi should be able to suggest a best place to file it, if necessary)

**Comment by znmeb** [comment]
@javierluraschi I think I tried "col_numeric" and it didn't work - IIRC it had a column of "NA". But yeah, "col_numeric" would work for my use case.

**Comment by javierluraschi** [comment]
@znmeb correct, this is an RStudio feature request... currently, for a CSV that looks like:

```
id,name, amount
1,test,$12
2,other,$12.4
```

You would be able to import the currency column as `numeric` field, see bellow. Would this work for you? 

<img width="1158" alt="screen shot 2016-06-02 at 6 30 23 pm" src="https://cloud.githubusercontent.com/assets/3478847/15766122/54e75734-28f0-11e6-86d7-dc627d09d595.png">

**Comment by znmeb** [comment]
@javierluraschi as long as it can handle getting rid of currency symbols and embedded thousands symbols it'll work ... the datasets I have are always $US and sometimes have commas like 
"$10,000.00". I personally don't need internationalization but I'm sure others will.

**Comment by hadley** [comment]
@javierluraschi 

```R
readr::col_numeric()
#> <collector_number>
#> Warning message:
#> In readr::col_numeric() : Deprecated: please use `col_number()`
```

I changed the name because "numeric" was too confusing.

**Comment by javierluraschi** [comment]
K, updating the IDE to use `col_number`
