### ISSUE TITLE
error:Invalid multibyte sequence

### ISSUE THREAD

**Issue by lixinyao** [hadley/readr#438]
Hi,
I am a chinese user of `readr`. Can you help me? Thanks!

```
> mydata1 = read_csv("/Users/lixinyao/Desktop/20160502.InputContract.SE.ByWeek.csv",
+ locale = locale(encoding="gbk"))
错误: Invalid multibyte sequence
```

But

```
> mydata = read.csv("/Users/lixinyao/Desktop/20160502.InputContract.SE.ByWeek.csv",
+                   header = TRUE,
+                   sep = ",",
+                   stringsAsFactors = FALSE,
+                   fileEncoding = "gbk")
Warning messages:
1: In scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  :
  输入链结'/Users/lixinyao/Desktop/20160502.InputContract.SE.ByWeek.csv'内的输入不对
2: In scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  :
  EOF within quoted string
```

It contains some specific symbols. What should I do?  Thank you very much!

**Comment by hadley** [comment]
Can you please make a minimal version of that file available online somewhere?

**Comment by lixinyao** [comment]
Thank your very much for you reply. I send a email . Thanks !

**Comment by hadley** [comment]
It doesn't appear to be in GBK encoding but in GB18030.

This code worked for me:

```R
read_csv("~/Desktop/20160502.InputContract.SE.ByWeek.csv", locale = locale(encoding = "GB18030"))
```

BTW when I print that dataset out, the column names don't seem to align with the columns. I think that's probably a bug in tibble. Is it ok to share the column names in another bug report? (but not the values of the columns)

**Comment by hadley** [comment]
Oh, I just google translated them and they seem pretty innocuous - I think I can probably share "completion date" and "contract entry date"!

**Comment by hadley** [comment]
Filed issue here https://github.com/hadley/tibble/issues/100
