### ISSUE TITLE
reading data with formulas

### ISSUE THREAD

**Issue by alanpaulkwan** [hadley/readr#440]
In read_excel, if I read something like =DATE(2001,01,01) the data evaluates to 0 or NULL, which is not optimal

The ideal behavior would be to preserve the formula or to parse it where possible. XLConnect does this well but is slow and does not handle memory well.

**Comment by hadley** [comment]
I think you filed this in the wrong repo.  Please file in readxl along with a reproducible example - readxl should read the values of cells, even when computed by a formula.
