### ISSUE TITLE
Doubles not recognized when reading a file with the read_csv2 function

### ISSUE THREAD

**Issue by polmath** [hadley/readr#455]
Hi, 

(I already described the issue on stackoverflow here: http://stackoverflow.com/q/37172389/3902976)

When I read csv files with semi-colon separator: 

    library(readr)
    read_csv2("A;B\n1.3;alpha\n2.345;beta", col_types = "dc")

here is the answer I get: 

    Warning: 2 parsing failures.
    row col               expected actual
      1   A no trailing characters   .3  
      2   A no trailing characters   .345
       A     B
    1 NA alpha
    2 NA  beta

In other words, the numbers 1.3 and 2.345 are not recognized. 
With comma separator everything is fine: 

    read_csv("A,B\n1.3,alpha\n2.345,beta", col_types = "dc")
          A     B
    1 1.300 alpha
    2 2.345  beta

Are you able to reproduce this? Do you know where it comes from? 
Thanks for your help. 

Here is my session info: 

    sessionInfo()
    R version 3.2.4 Revised (2016-03-16 r70336)
    Platform: i386-w64-mingw32/i386 (32-bit)
    Running under: Windows 7 x64 (build 7601) Service Pack 1
    
    locale:
    [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
    [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
    [5] LC_TIME=English_United States.1252    
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] readr_0.2.2
    
    loaded via a namespace (and not attached):
    [1] Rcpp_0.12.4

**Comment by hadley** [comment]
`read_csv2()` is for files with `;` separator and `,` decimal point. Try `read_delim()` instead.

**Comment by engie-paul-poncet** [comment]
Thanks, it works indeed! I thought the decimal point was recognized automatically.

**Comment by polmath** [comment]
Thanks it works indeed! I initially thought that the decimal point was recognized automatically.
