### ISSUE TITLE
Sign loss in a mixed numerical column

### ISSUE THREAD

**Issue by rsuhada** [hadley/readr#487]
I've stumbled on this corner case with read_csv in reader readr_0.2.2: 

A numerical column in a csv file which was dumped from excel including thousands separator:

> ...
> 0.00
> -0.70
> "3,276.28"
> 0.00
> ....

There are no negative numbers in the first 1000 (in fact there is only a single negative number: -0.7).
Readr "looses" its sign:

> > x1 = read_csv("~/tmp/test.csv")
> > x1[7501, ] %>% glimpse
> Observations: 1
> Variables: 1
> $ x (dbl) 0.7

Builting read.csv casts everything to string and includes the sign (i.e. this is not a file encoding issue, but something with the parser).

> > x2 = read.csv("~/tmp/test.csv", stringsAsFactors=FALSE)
> > x2[7501, ] %>% glimpse
>  chr "-0.70"
> 

Thank you for the amazing package, saves so much time!

**Comment by hadley** [comment]
Already fixed in dev
