### ISSUE TITLE
readr replaces "." with " " when reading column header

### ISSUE THREAD

**Issue by cogsbox** [hadley/readr#493]
This may be more of a question than an issue. This is also my first time posting an issue ever on github, so if I am doing this wrong I am sorry. I am a noob.

I have a column header, "Study.ID" in my csv file. When I use base R, read.csv(), is stays "Study.ID". when I use read_csv() is become "Study ID". It is difficult to work with columns names that have a space. How can I tell readr to keep the "." and not replace with " "?

Thanks for the help.

**Comment by hadley** [comment]
You can to use ``df$`Study ID` `` to refer to the column in R, and then rename it to something easier to type.

**Comment by kevinushey** [comment]
Are you sure that `readr` is replacing `"."` with `" "`, and not the other way around (`read.csv` replacing a `" "` with a `"."`? What does `read.csv(..., check.names = FALSE)` return for column names?

**Comment by cogsbox** [comment]
read.csv(..., check.names = FALSE) replaces "." with " " also. I am not sure why.

**Comment by cogsbox** [comment]
Either way I am happy with the solution hadley gave.
