### ISSUE TITLE
read_table does not have a `sep` argument

### ISSUE THREAD

**Issue by cogsbox** [hadley/readr#496]
I feel bad opening issues for things that are more like questions. 

If there is a more appropriate place for asking questions about why a package is the way it is please send me somewhere else.

I was reading a [.txt](https://webdav.tuebingen.mpg.de/cause-effect/pair0001.txt) file from the web today and I was trying to use `read_table`, but `read_table` has no separation argument like read.table so when I was reading in the values with `read_table` I ended up with one vector of characters. I tried again with `read.table(url, sep = " ")` and I got the desired two vectors of doubles.

Is `read_table` going to get a `sep` argument or should I be approaching this problem differently.

**Comment by hadley** [comment]
You want read_delim. read_table is for fwf files that are separated by columns of white space.

**Comment by cogsbox** [comment]
Thanks!
