### ISSUE TITLE
Missing "column-types" vignette

### ISSUE THREAD

**Issue by tchakravarty** [hadley/readr#501]
@hadley `vignette("column-types")` mentioned, for example, in the documentation for `read_csv` gives me: 

    Warning message:
    vignette ‘column-types’ not found

**Comment by hadley** [comment]
Maybe you have an old version? It's definitely there: https://cran.r-project.org/web/packages/readr/vignettes/column-types.html

**Comment by tchakravarty** [comment]
Fresh Github install -- might be an RStudio issue.

**Comment by hadley** [comment]
Installing from github doesn't install vignettes by default.  You should just install from CRAN.

**Comment by Momus** [comment]
Trying to find vignette("column-types") :
 https://cran.r-project.org/web/packages/readr/vignettes/column-types.html gives a 404 error. 
Looking at 
https://cran.r-project.org/web/packages/readr/
there are only two available vignettes: readr intro and locales.

**Comment by jimhester** [comment]
Yes the column type vignette was folded into the readr intro.

**Comment by Momus** [comment]
Thank you for your response. The specific information I was looking for was how to use strings to specify columns compactly: "_ci_dd" and such. Forgive me if I missed it in my inattention, but that information is still missing from the vignette. I stumbled into an answer that worked for me, but it would be nice to have an authoritative documentation of this feature, or perhaps a pointer if it is documented elsewhere.

**Comment by Dulani** [comment]
@jimhester If the column-type vignette was removed from the readr intro, then the reference to it in the read_csv documentation should probably be updated too.  As of today, readr v1.1.1 on CRAN still has the reference to `vignette("column-types").`  I'll submit a new issue to reflect this since this one is closed.
