### ISSUE TITLE
col_names in read_csv() doesn't work well

### ISSUE THREAD

**Issue by swLai** [hadley/readr#505]
When I select the lines of code I want to execute in script panel and press Ctrl + Enter will get warnings

_situation_1_
```
library(readr)
a <- read_csv(
 "Line 1 to skip
  Line 2 to skip
  Line 3 to skip
  # comment line to skip
  1, 2, 3, .
  4, 5, 6, 7
  ., 8, ., 9", 
 comment = "#", 
 skip = 3, 
 col_names = c("a", "b", "c", "d"), 
 na = ".")
```
```
problems(a)
# A tibble: 1 x 4
#     row   col  expected    actual
#   <int> <chr>     <chr>     <chr>
# 1     1  <NA> 4 columns 1 columns

a
# A tibble: 4 x 4
#       a     b     c     d
#   <int> <int> <int> <int>
# 1    NA    NA    NA    NA
# 2     1     2     3    NA
# 3     4     5     6     7
# 4    NA     8    NA     9
```

_situation_2_
```
a <- read_csv(
  "Line 1 to skip
  Line 2 to skip
  Line 3 to skip
  # comment line to skip
  a, b, c, d
  1, 2, 3, .
  4, 5, 6, 7
  ., 8, ., 9", 
  comment = "#", 
  skip = 3, 
  col_names = T, 
  na = ".")
```
```
problems(a)
# A tibble: 4 x 4
#     row   col  expected    actual
#   <int> <chr>     <chr>     <chr>
# 1     1  <NA> 1 columns 4 columns
# 2     2  <NA> 1 columns 4 columns
# 3     3  <NA> 1 columns 4 columns
# 4     4  <NA> 1 columns 4 columns

a
# A tibble: 4 x 1
#      X1
#   <chr>
# 1     a
# 2     1
# 3     4
# 4  <NA>
```
But, if I execute the code progressively line by line, it work just fine. Don't know what problems I've encountered.

**Comment by hadley** [comment]
Sorry, I don't understand what the problem is.

**Comment by tjmahr** [comment]
The problem is with the way that the code is formatted here. 

The code tells `read_csv` to skip the first 3 lines and to ignore the lines that begin with the comment marker `#`. But there are no lines in the example that begin with `#` because of the spaces being used to align each line. The comment line is not ignored, and read_csv issues a warning.

```r
string <- 
 "Line 1 to skip
  Line 2 to skip
  Line 3 to skip
  # comment line to skip
  a, b, c, d
  1, 2, 3, .
  4, 5, 6, 7
  ., 8, ., 9"

# Every line after the first has some spaces at the start
unlist(stringr::str_split(string, "\n"))
#> [1] "Line 1 to skip"           "  Line 2 to skip"        
#> [3] "  Line 3 to skip"         "  # comment line to skip"
#> [5] "  a, b, c, d"             "  1, 2, 3, ."            
#> [7] "  4, 5, 6, 7"             "  ., 8, ., 9"
```

The reason why the code works when it is run line-by-line in RStudio is that the cursor skips those initial spaces on each line. Because of this, read_csv can properly detect the comment line, and it will correctly ignore the comment line.

**Comment by hadley** [comment]
Oh, that's why you format code like:

```R
string <- "Line 1 to skip
Line 2 to skip
Line 3 to skip
# comment line to skip
a, b, c, d
1, 2, 3, .
4, 5, 6, 7
., 8, ., 9"
```

I don't think this is readr's responsibility to solve - inline csv is supposed to be only used for very simple cases.
