### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by panditanvita** [hadley/readr#506]
Hello! Thanks for maintaining the packages.

I'm getting this error when trying to install from R and I was wondering if you had any insight - i think it could be an issue with swap space on my virtual server

> install.packages('readr')
Installing package into ‘/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.revolutionanalytics.com/src/contrib/readr_1.0.0.tar.gz'
Content type 'unknown' length 196055 bytes (191 KB)
\===================================
downloaded 191 KB
\* installing *source* package ‘readr’ ...
** package ‘readr’ successfully unpacked and MD5 sums checked
** libs
g++ -I/usr/share/R/include -DNDEBUG   -I"/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include" -I"/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.3/BH/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c Collector.cpp -o Collector.o
virtual memory exhausted: Cannot allocate memory
make: *** [Collector.o] Error 1
ERROR: compilation failed for package ‘readr’
\* removing ‘/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.3/readr’

I also tried installing from the github:

> devtools::install_github("hadley/readr")
Downloading GitHub repo hadley/readr@master
from URL https://api.github.com/repos/hadley/readr/zipball/master
Installing readr
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL '/tmp/RtmpkkfyvZ/devtools79313d2e87f6/hadley-readr-37d6eda'  \
  --library='/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.3' --install-tests 
\* installing *source* package ‘readr’ ...
\** libs
g++ -I/usr/share/R/include -DNDEBUG   -I"/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include" -I"/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.3/BH/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c Collector.cpp -o Collector.o
virtual memory exhausted: Cannot allocate memory
make: *** [Collector.o] Error 1
ERROR: compilation failed for package ‘readr’
\* removing ‘/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.3/readr’
Error: Command failed (1)

this is my session

sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.4 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

**Comment by panditanvita** [comment]
Fixed it - graduated to a 2GiB instance

**Comment by lozalojo** [comment]
I'm having the same problem, it is an ubuntu server with 1gb ram:

> devtools::install_github("hadley/readr")
Downloading GitHub repo hadley/readr@master
from URL https://api.github.com/repos/hadley/readr/zipball/master
Installing readr
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL '/tmp/Rtmp8ej8lw/devtools219d7b644396/tidyverse-readr-f516393'  \
  --library='/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.4' --install-tests

* installing *source* package ‘readr’ ...
** libs
g++  -I/usr/share/R/include -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.4/BH/include"    -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c Collector.cpp -o Collector.o
virtual memory exhausted: Cannot allocate memory
/usr/lib/R/etc/Makeconf:168: recipe for target 'Collector.o' failed
make: *** [Collector.o] Error 1
ERROR: compilation failed for package ‘readr’
* removing ‘/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.4/readr’
Error: Command failed (1)

> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
 [1] httr_1.2.1      compiler_3.4.0  R6_2.2.0        tools_3.4.0
 [5] withr_1.0.2     curl_2.6        memoise_1.1.0   knitr_1.15.1
 [9] git2r_0.18.0    digest_0.6.12   devtools_1.12.0

**Comment by jimhester** [comment]
@lozalojo try increasing the virtual memory limit of your server or get more system memory, this is not a readr issue, you just need more memory to compile the package.
