### ISSUE TITLE
Column name/named parser mismatch.

### ISSUE THREAD

**Issue by Ironholds** [hadley/readr#52]
>data <- read_delim(file = "sampled-1000.tsv.log-20130502.gz",
                   col_names = FALSE,
                   parsers = list(V1 = skip_parser(),
                                  V2 = skip_parser(),
                                  V3 = character_parser(),
                                  V4 = skip_parser(),
                                  V5 = character_parser(),
                                  V6 = character_parser(),
                                  V7 = skip_parser(),
                                  V8 = skip_parser(),
                                  V9 = character_parser(),
                                  V10 = skip_parser(),
                                  V11 = character_parser(),
                                  V12 = character_parser(),
                                  V13 = character_parser(),
                                  V14 = character_parser(),
                                  V15 = character_parser(),
                                  V16 = character_parser()),
                   quote = "", delim = "\t")

Guessing column specification from first 1 lines of data
No column names in file, using X1-X1
Error: The following named parsers don't match the column names: V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16

...I'm probably just missing something, but what's going on here?

**Comment by hadley** [comment]
Should be fixed now

**Comment by Ironholds** [comment]
Thanks!
