### ISSUE TITLE
Guessing column specification fails, last line is not parsed

### ISSUE THREAD

**Issue by astamm** [hadley/readr#55]
Hi,
I am eager to use fostered as it incredibly speeds up the process of loading external datasets into R in an elegant fashion. However, I found two issues regarding CSV file import that makes it less appealing as of right now.

I built this fake dataset in a CSV utf8-encoded file (ASCII files have same problems).

x | y
---- | ----
1   | 0.14195243222639
2   | 0.50174369988963
3   | 0.771776407491416
4   | 0.156515575014055
5   | 0.0212687917519361
6   | 0.0705624825786799
7   | 0.951427533756942
8   | 0.0900125880725682
9   | 0.951599907595664
10 | 0.470190198626369
saved under "testing/small_dataset_uft8.csv"

**Issue 1**
Guessing column specification fails as stated by
> fastread::read_csv(file = "testing/small_data_utf8.csv")
> Guessing column specification from first 11 lines of data
> Reading column names from file: x, y
> Guessing how to parse each column
> x = integer_parser() # or double
> y = double_parser()
> Error in get(as.character(FUN), mode = "function", envir = envir) : 
>   object 'integer_parser' of mode 'function' was not found

which can be solved by manually insert parsers = "id" as in: 
> fastread::read_csv(file = "testing/small_data_utf8.csv", parsers = "id")
> Guessing column specification from first 11 lines of data
> Reading column names from file: x, y
> Source: local data frame [9 x 2]

     |  x    |     y
--- | --- | ---
1| 1| 0.2919461
2| 2| 0.5704769
3| 3| 0.6707377
4| 4| 0.8153851
5| 5| 0.4997104
6| 6| 0.4177210
7| 7| 0.1455466
8| 8| 0.4722528
9| 9| 0.9214854

**Issue 2**
Last line is not parsed as shown in table above. A workaround is to specifically tell *fastread* the expected number of lines in the datasets with the n option as in
> fastread::read_csv(file = "testing/small_data_utf8.csv", parsers = "id", n = 10)
> Guessing column specification from first 11 lines of data
> Reading column names from file: x, y
> Source: local data frame [10 x 2]

     |    x    |     y
--- | --- | ---
1 |  1 | 0.2919461
2 |  2 | 0.5704769
3 |  3 | 0.6707377
4 |  4 | 0.8153851
5 |  5 | 0.4997104
6 |  6 | 0.4177210
7 |  7 | 0.1455466
8 |  8 | 0.4722528
9 |  9 | 0.9214854
10 | 10 | 0.4972297

But this is not really handy.
Best,
-Aymeric

**Comment by astamm** [comment]
Oops, I forgot.

Another workaround for the second issue is to add an extra blank line at the end of the file to be imported.

These workarounds make it work but if the issue could be solved that'd be even better!

Thanks for the great work btw!
-Aymeric

**Comment by hadley** [comment]
Should be better now. If not, please file a minimal reprex.
