### ISSUE TITLE
Come up with better name

### ISSUE THREAD

**Issue by hadley** [hadley/readr#58]

**Comment by leeper** [comment]
If you want a really nerdy reference to debate tournaments, you could try ["spread"](http://en.wikipedia.org/wiki/Policy_debate#Speed). Example: https://www.youtube.com/watch?v=dj4pQe11eZc

**Comment by romainfrancois** [comment]
How about `rio` for R Input Output

**Comment by romainfrancois** [comment]
Nevermind, there is already a `rio` package on cran

**Comment by hadley** [comment]
Changed to readr, thanks @eddelbuettel!
