### ISSUE TITLE
Add a verbose argument

### ISSUE THREAD

**Issue by leeper** [hadley/readr#59]
Would you be open to a pull request for a `verbose` or, conversely, a `quiet` argument?

The `guess*` functions can be pretty `message`-y: [here](https://github.com/hadley/fastread/blob/5f765ff2bfe5dacea8dc39d141c8e9b058d27902/R/spec-build.R#L57-L58), [here](https://github.com/hadley/fastread/blob/5f765ff2bfe5dacea8dc39d141c8e9b058d27902/R/spec-build.R#L70-L71), [here](https://github.com/hadley/fastread/blob/5f765ff2bfe5dacea8dc39d141c8e9b058d27902/R/spec-build.R#L85), [here](https://github.com/hadley/fastread/blob/5f765ff2bfe5dacea8dc39d141c8e9b058d27902/R/spec-build.R#L151-L152), [here](https://github.com/hadley/fastread/blob/5f765ff2bfe5dacea8dc39d141c8e9b058d27902/R/spec-build.R#L157-L158),

**Comment by hadley** [comment]
I've currently gone with completely quiet on construction, and warnings on parser failures. I'll see how that feels.
