### ISSUE TITLE
read_* cannot read file information when using '~' to specify file location

### ISSUE THREAD

**Issue by dpastoor** [hadley/readr#60]
sometimes when working with files outside the Rstudio project need to specify an absolute path (shudder). For a while I thought it was just fastread just didn't have a number of functions implemented because when trying to use functions like read_lines() with a path like

```
read_lines("~/mypath/myfile")
```
the following error results:
```
Error: cannot read file information
```

however if you normalize the path it works just fine
```
read_lines("/Users/restofpath/myfile")
```

**Comment by dpastoor** [comment]
I guess the reason I opened the issue is to check if this was a bug or 'feature'. It seems? like a call to normalizePath would be sufficient, but I didn't know if it'd be more appropriate in `check_file()` or some other place.

**Comment by hadley** [comment]
Should be fixed now.
