### ISSUE TITLE
The 'NA' parameter does not change NAs

### ISSUE THREAD

**Issue by Ironholds** [hadley/readr#64]
Using the test data in the testthat directory:

> test_data <- read_csv(file.path(getwd(),"/basic-df.csv"), na = "turnip")
> test_data
       a  b          c  d
1  FALSE  7 0.18152664  m
2  FALSE  2 0.83322744  z
3  FALSE  8 0.92679048  r
4  FALSE 10 0.37527031  s
5  FALSE  6 0.42026629  g
6  FALSE  3 0.43544999  h
7  FALSE  5 0.02109420  w
8  FALSE  9 0.09155708  u
9  FALSE  1 0.75610687  l
10 FALSE  4 0.35353098 NA

**Comment by astamm** [comment]
I have worked on that on my fork.

Still have to make a pull request and check with Hadley & Romain if it fits the way they thought to handle NAs.

Will make the pull request tmrw.

-Aymeric

On Mar 9, 2015, at 9:04 PM, Oliver Keyes <notifications@github.com<mailto:notifications@github.com>> wrote:


Using the test data in the testthat directory:

test_data <- read_csv(file.path(getwd(),"/basic-df.csv"), na = "turnip")
test_data
a b c d
1 FALSE 7 0.18152664 m
2 FALSE 2 0.83322744 z
3 FALSE 8 0.92679048 r
4 FALSE 10 0.37527031 s
5 FALSE 6 0.42026629 g
6 FALSE 3 0.43544999 h
7 FALSE 5 0.02109420 w
8 FALSE 9 0.09155708 u
9 FALSE 1 0.75610687 l
10 FALSE 4 0.35353098 NA

**Comment by Ironholds** [comment]
Cool!

**Comment by hadley** [comment]
@astamm probably since you started working on that I completely rewrote the backend :/

**Comment by hadley** [comment]
There was a bug, but I don't think it works the way you expect. Hopefully this makes it more clear:

```R
parse_vector("1,2,3,.", tokenizer_csv(na = "."), col_double())
parse_vector("1,2,3,NA", tokenizer_csv(na = "NA"), col_double())
```

**Comment by hadley** [comment]
@astamm if you're interested in contributing more pull requests, I've written up some basic design docs in `vignettes/design.Rmd`. The new design should hopefully be easier to work with - please let me know if anything isn't clear.

**Comment by astamm** [comment]
@hadley yes I would like to contribute to the package as much as possible.

Will read the design vignette soon.

Thanks!
On Mar 10, 2015, at 9:12 AM, Hadley Wickham <notifications@github.com<mailto:notifications@github.com>> wrote:


@astamm<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_astamm&d=BQMCaQ&c=qS4goWBT7poplM69zy_3xhKwEW14JZMSdioCoppxeFU&r=YY0Nl6LrGyElaL-CxD3xdZzVapE6UH4Cpr-mdEV4EX3NxhgDF5KLPTqjD9TVadjr&m=xD96NPTRHq4dpKSiP2SvEvIgAkIJDeuSCKktaSr1_w4&s=_Z_dSgjybDP7ahKUjrjy81wLkrzHMu9bdQlvbWflnRc&e=> if you're interested in contributing more pull requests, I've written up some basic design docs in vignettes/design.Rmd. The new design should hopefully be easier to work with - please let me know if anything isn't clear.
