### ISSUE TITLE
read_csv failed on test file

### ISSUE THREAD

**Issue by smach** [hadley/readr#79]
FYI read.csv() and data.table::fread() both were able to read a test file (base R with warning message,) but read_csv() wouldn't read it at all. Not sure if this is as designed or if you might want read_csv() to be able to handle this somehow. I created this file from saving to CSV from a couple of test Excel entries within Excel.

x3 <- read_csv("http://www.machlis.com/testing.csv")

Then tried

x1 <- read.csv("http://www.machlis.com/testing.csv", stringsAsFactors = FALSE, header = TRUE)
x2 <- data.table::fread("http://www.machlis.com/testing.csv")

**Comment by hadley** [comment]
Which version of excel did you use? It only uses `\r` to separate lines, which I didn't think was possible. I'll make the parser more robust.

**Comment by smach** [comment]
The dreaded Excel for Mac.

**Comment by smach** [comment]
Just booted up the Mac to check: More specifically, Excel for Mac 2011. Tried same file using Excel 2013 on Windows and all was fine.

**Comment by chrishaid** [comment]
Same problem here.  I saved an excel worksheet as a csv in Excel for Mac 2011 on MBP (2.5 GHz Intel Core i5) running OS X 10.9.5.  

Running `read_csv()` on the file causes my R session to crash in RStudio (Version 0.98.1091).
