### ISSUE TITLE
>100 columns in read_csv?

### ISSUE THREAD

**Issue by tslumley** [hadley/readr#81]
In some files from the American Community Survey I get 

Error in parse_(ds, tokenizer, collector) : 
  attempt to set index 100/100 in SET_STRING_ELT

This seems to happen when there are more than 100 columns, for example in this code
> set.seed(2015-3-13)
> x<-matrix(rbinom(300,2,.5),nrow=2)
> write.csv(x,'~/test2.csv')
> read_csv("~/test2.csv")

Looking at parse.h:80-81
```
boost::shared_ptr<Collector> out = Collector::create(collectorSpec);
out->resize(100);
```
and 85-86
```
if (i > out->size())  
     out->resize(i * 2);
```
could there be an off-by-one error in the resizing test?

**Comment by hadley** [comment]
Gaaaa. Thanks for the bug report and figuring out the problem!
