### ISSUE TITLE
Parse more elements to guess type if the 100 first ones are all NA

### ISSUE THREAD

**Issue by juba** [hadley/readr#84]
For certain data files with many rows, some columns have very few values. So it is frequent that the first 100 values for a column are all empty. In this case, `readr` seems to guess the column type as `logical`, but there is no real value to base the guess on.

I know that in this case we can give the column types manually, but it is always a bit tedious. So I wonder if there would be a way to parse more than 100 elements if they are all empty.

Maybe this is not possible at all or would affect speed to much, in this case you can of course close this issue.

Thanks !

**Comment by hadley** [comment]
I'd rather solve this by making it easier to supply the correct types.
