### ISSUE TITLE
Time zone handling issue

### ISSUE THREAD

**Issue by msonnabaum** [hadley/readr#90]
If you run the following:

```r
library("readr")

a <- data.frame(datetime = c(
"2006-01-02T15:04:05-0500"
))

temp_path <- tempfile(fileext = ".csv")
write_csv(a, temp_path)

read_csv(temp_path,
  col_types = list(
    datetime = col_datetime("%Y-%m-%dT%H:%M:%S%z")
  )
)
```

You get:

```
Source: local data frame [1 x 1]

  datetime
1     <NA>
Warning message:
In read_tokens(ds, tokenizer, col_types, col_names, n_max = n_max,  :
  At [1, 1]: expected date like '2006-01-02T15:04:05-0500', got '2006-01-02T15:04:05-0500'
```

It also appears to fail with time zones that use a : between hours and minutes.

Removing the timezones from the dataframe and format string allows it to parse correctly.

**Comment by hadley** [comment]
I had to include a custom `strptime` implementation and it's kind of old, so I don't think there's any support for time zones. I'm definitely going to add a custom (i.e. fast) ISO8601 parser, which would solve your problem.

**Comment by hadley** [comment]
Custom ISO 8601 parser added - and since it's a well defined spec with minimal chances that you'll recognise it by accident:

```R
read_csv("x\n2006-01-02T15:04:05-0500")
#>                     x
#> 1 2006-01-02 20:04:05
```
