### ISSUE TITLE
Minor documentation issue in read_delim {readr}

### ISSUE THREAD

**Issue by TonyLadson** [hadley/readr#91]
In the help file for:
read_delim {readr}

In the **arguments** section, in the description of *progress*

Change "on"  to "only" in the following:

> Display a progress bar? By default it will only display in an interactive session. The display is updated every 50,000 values and will ~~on~~ **only** display if estimated reading time is 5 seconds or more.

**Comment by hadley** [comment]
Want to do a pull request? You use the github editor - just make sure to edit the underlying roxygen comment, not the Rd file.

**Comment by TonyLadson** [comment]
Done!
