### ISSUE TITLE
Dealing with horrible files

### ISSUE THREAD

**Issue by Ironholds** [hadley/readr#94]
Some humans - some terrible, terrible humans - leave tabs in content-insertable fields. Tabs that are not consistently escaped. Would it be possible to add an option to read_delim that, if set to FALSE, continues current behaviour around one row unexpectedly having an extra field and, if set to TRUE, mashes the extra field into the last "expected" field and issues a warning noting the row number?

**Comment by hadley** [comment]
I think so. Could you outline a few examples? (maybe using commas so it's a bit easier to see)

**Comment by Ironholds** [comment]
Totally!

h1 h2 h3
1,  6,  A RUN-ON SENTENCE (sometimes called a "fused sentence")
1,  9,  has at least two parts, either one of which can stand by itself
5,  4,  (in other words, two independent clauses)

We've got an unquoted text field, which shouldn't be a thing that exists but is, because humans are terrible. As a result, any comma is (potentially) a delimiter; it's impossible for a machine to tell.

In R-core, the response is to create an additional field at the end and then (confusingly) warn you about incomplete lines. In readr, the response is to say "more columns than column names, abort!". It would be nice to have a way of solving for this by saying "I don't care if you've got a comma in you, field, I've been told there are six fields and you're no.7 so I'm going to issue a warning and then fields[6] += fields[7]. In you go now."

**Comment by hadley** [comment]
Hmmm, this is the same basic behaviour as `tidyr::separate()` so maybe have the same option? i.e. `extra = c("error", "drop", "merge")`

**Comment by hadley** [comment]
Maybe `warn` (= warning + drop) would be the best default

**Comment by Ironholds** [comment]
Yep; sounds perfect!

**Comment by hadley** [comment]
Related to #189

**Comment by dbuijs** [comment]
Fantastic package! Please excuse if this is out of scope, but there are all sorts of horrible source CSV that I find myself having to deal with by pre-processing outside of R with something like Perl. Totally ok if you think that's still probably the best way to do this. 

The way you've got this package set up however, makes me think that perhaps other forms of CSV lunacy could be dealt with by simply writing a new tokenizer. 

The specific things that I have trouble dealing with entirely within R include:

1. Mismatched encoding/locale, usually something that has been declared explicitly or implicitly as UTF-8 but is actually ISO-8859-1, which has consequences for interpreting newlines and EOF. (There are R solutions for this, including the excellent `rvest` package, but this really needs to be dealt with right at the file level before throwing it at a parser.)

2. Embedded but unescaped newlines.

3. Embedded but unescaped delimiters.

4. Embedded but unescaped quotes.

5. Undeclared/inconsistent padding whitespace (Pretty sure `readr` can handle this already, but included in the list for completeness)

If you've already got or are working on auto-detect/guessing for the number of fields, the delimiter, the quote character and the newline code, you can potentially fix all of these annoying issues (with or without fanfare, as the case may be). 

On a high level, you would add a check (probably just for string or unknown col types) for the number of fields in the current line and if it doesn't match what was auto-detected or declared in the call, jump to a special tokenizer for that line and any subsequent lines until you get a single parsed record that makes sense, then jump back to your standard tokenizer. Optionally, you spit out a warning (or error) for the line(s) and the problem.

If the file is so messy that it can't even get past auto-detect, then you exit and throw an error that the file isn't valid CSV (or delimited) of any flavour, and this is also useful information. 

Are my assumptions here about how readr works and/or is planned reasonable?

**Comment by hadley** [comment]
@dbuijs can you please open a new issue?

**Comment by hadley** [comment]
I think this is ok now - readr will just expand the columns as needed, and you can do the cleanup afterwards. (i.e. it's like `extra = "warn"` with no option to change the behaviour). The code is already getting pretty complicated, so I don't want to mess with it at the moment.
