### ISSUE TITLE
Option to ignore unparsable lines?

### ISSUE THREAD

**Issue by msonnabaum** [hadley/readr#99]
I first posted this in webtools' queue (https://github.com/Ironholds/webtools/issues/1) and we came to the conclusion that this is actually a readr feature request.

The problem occurs when you have a field in double quotes, that contains an unescaped/unencoded double quote inside it. read_delim unsurprisingly gets confused when the delimiter character does not occur directly after the second double quote.

Here's an example of what I ran into using only read_delim:

```{r}

library("readr")

lines <- c(
  '10.44.74.181 - - [20/Mar/2015:21:20:23 +0000] "GET http://www.example.com/fonts/webfont.eot?)%20format("eot") HTTP/1.1" 200 234'
)

temp_path <- tempfile()
conn <-file(temp_path)
writeLines(lines, conn)
close(conn)
temp_path

names <- c("ip_address", "remote_user_ident", "local_user_ident", "timestamp",
           "timestamp_junk","request", "status_code","bytes_sent")
data <- read_delim(temp_path, delim = " ", col_names = names)

```
This results in:

`Error: At [1, 6] expecting delimiter or quote but found 'e'`

Similar to https://github.com/hadley/readr/issues/94, I think it'd be good to have an option to warn/drop these rows that are unparsable.

**Comment by hadley** [comment]
The reason I haven't done this already is because it's not clear in this situation where the end of the row is - in your case you can look for the next newline, but what if there are embedded new lines in the string?

**Comment by Ironholds** [comment]
I've actually had to deal with this problem in other languages (read:perl. Eugh.) with particularly cruddy datasets.

My suggestion - if there's an embedded newline - on how to evaluate it, would be to look at the fields included so far. Readr requires a listing of field types; by extension, it provides a count of how many fields are expected. So you could say "alrighty, we've hit an unexpected newline. Do I have as many fields as the file definition told me I would before I hit a newline? Okay, [ignore/ignore and warn/whatever]"

**Comment by hadley** [comment]
In the mean time, does `quote = ""` work?

**Comment by Ironholds** [comment]
It would, but it's going to cause problems; some of the quoted fields are quoted because they contain spaces, which are the separator for this format. I can look into the performance impact of just binding those together, though?

**Comment by hadley** [comment]
Are you sure? I think the spaces will always be escaped as part of the http request (as they are in this example)

**Comment by Ironholds** [comment]
"GET http://www.example.com/fonts/webfont.eot?)%20format("eot") HTTP/1.1" is actually one field, in its entirety, under the CLF spec :(

**Comment by hadley** [comment]
New behaviour:

```R
lines <- '10.44.74.181 - - [20/Mar/2015:21:20:23 +0000] "GET http://www.example.com/fonts/webfont.eot?)%20format("eot") HTTP/1.1" 200 234\n'

names <- c("ip_address", "remote_user_ident", "local_user_ident", "timestamp",
  "tz","request", "status_code","bytes_sent")
data <- read_delim(lines, delim = " ", col_names = names)
problems(data)
#>  row col           expected actual
#> 1   1   6 delimiter or quote      e
#> 2   1   6 delimiter or quote      )
```

**Comment by msonnabaum** [comment]
Hmm, just did a `devtools::install_github("hadley/readr")` and executed the code you provided, and I get: `Error: You have 8 column names, but 9 columns`.

Maybe a regression from one of the later commits?

**Comment by hadley** [comment]
Well there's now `read_log()` in the interim, but I'll look into it again :/

**Comment by soedr** [comment]
Are there any changes or updates on this? I'd like for `read_delim()` to not read in rows with parsing failures and am using a workaround with 

`problem_row_idx <- purrr::flatten_dbl(problems(messy_data)['row']` 

and dropping rows with `row_number()` in `problem_row_idx`, but I'm sure there's a better solution. Thanks in advance!
